-- Synthetic parent and renamed disposable schema; never an installation test.
BEGIN;
CREATE SCHEMA truss_migration_storage_probe;
CREATE TABLE truss_migration_storage_probe.source_epoch_registry (installation_id text COLLATE pg_catalog."C", source_epoch text COLLATE pg_catalog."C", PRIMARY KEY (installation_id,source_epoch));
CREATE SEQUENCE truss_migration_storage_probe.layout_migration_receipt_row_seq AS bigint MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE; CREATE TABLE truss_migration_storage_probe.layout_migration_receipt (storage_row_id bigint PRIMARY KEY DEFAULT nextval('truss_migration_storage_probe.layout_migration_receipt_row_seq'), installation_id text NOT NULL COLLATE pg_catalog."C", original_source_epoch text NOT NULL COLLATE pg_catalog."C", original_target_incarnation text NOT NULL CHECK (octet_length(original_target_incarnation) BETWEEN 1 AND 1024) COLLATE pg_catalog."C", original_attempt_identity_bytes bytea NOT NULL CHECK (octet_length(original_attempt_identity_bytes) BETWEEN 1 AND 1024), receipt_profile_bytes bytea NOT NULL CHECK (octet_length(receipt_profile_bytes) BETWEEN 1 AND 65536), original_request_bytes bytea NOT NULL CHECK (octet_length(original_request_bytes) > 0), original_receipt_bytes bytea NOT NULL CHECK (octet_length(original_receipt_bytes) > 0), original_attempt_sha256 bytea GENERATED ALWAYS AS (pg_catalog.sha256(original_attempt_identity_bytes)) STORED, original_request_sha256 bytea GENERATED ALWAYS AS (pg_catalog.sha256(original_request_bytes)) STORED, original_receipt_sha256 bytea GENERATED ALWAYS AS (pg_catalog.sha256(original_receipt_bytes)) STORED, CHECK (storage_row_id > 0), CHECK ((octet_length(original_request_bytes)::bigint + octet_length(original_receipt_bytes)::bigint) <= 16777216), FOREIGN KEY (installation_id, original_source_epoch) REFERENCES truss_migration_storage_probe.source_epoch_registry (installation_id, source_epoch) ON DELETE RESTRICT); CREATE INDEX layout_migration_receipt_attempt_route ON truss_migration_storage_probe.layout_migration_receipt USING btree (installation_id, original_attempt_sha256, storage_row_id); REVOKE ALL ON truss_migration_storage_probe.layout_migration_receipt, truss_migration_storage_probe.layout_migration_receipt_row_seq FROM public;
SELECT count(*) AS columns FROM pg_attribute WHERE attrelid='truss_migration_storage_probe.layout_migration_receipt'::regclass AND attnum>0 AND NOT attisdropped;
SELECT count(*) AS foreign_keys FROM pg_constraint WHERE conrelid='truss_migration_storage_probe.layout_migration_receipt'::regclass AND contype='f';
SELECT count(*) AS generated_hashes FROM pg_attribute WHERE attrelid='truss_migration_storage_probe.layout_migration_receipt'::regclass AND attgenerated='s';
SELECT has_table_privilege('public','truss_migration_storage_probe.layout_migration_receipt','INSERT') AS public_insert;
ROLLBACK;
