"""Concrete synthetic source-backed binding; never accepted/native registry authority."""
import json,hashlib,base64
from pathlib import Path
R=Path(__file__).resolve().parents[5];OUT=R/'docs/helix/04-build/evidence/weft-source-binding08';OUT.mkdir(exist_ok=True)
def raw(v):return json.dumps(v,ensure_ascii=False,separators=(',',':')).encode()
def digest(b):return hashlib.sha256(b).hexdigest()
def artifact_bytes(identity,b):return {'identity':identity,'sha256':digest(b),'bytesBase64':base64.b64encode(b).decode()}
def artifact(identity,v):return artifact_bytes(identity,raw(v))
profiles={}
def pin(name,meaning):
 body={'identity':name,'version':'0.1.0-source-fixture','meaning':meaning,'status':'synthetic-source-review','nativeQualified':False,'registered':False};profiles[name]=body
 return {'identity':name,'version':body['version'],'sha256':digest(raw(body))}
layout_path='docs/helix/02-design/contracts/weft-review-columns-v0.8.proposal.json';layout_bytes=(R/layout_path).read_bytes();layout=json.loads(layout_bytes)
# A compact complete declared table/column identity map, with exact source custody by pinned AST.
# It is NOT an admitted native catalog inventory. No names alone establish installed correspondence.
inv={'status':'source-declaration-map-only','nativeQualified':False,'sourceInventory':{'path':layout_path,'sha256':digest(layout_bytes)},'astPath':layout['astPath'],'astSha256':layout['astSha256'],'tables':[]}
for t in layout['tables']:
 inv['tables'].append({'physicalIdentity':'truss.review08.table.'+t['name'],'name':t['name'],'createPointer':t['createPointer'],'columns':[{'physicalIdentity':'truss.review08.column.'+t['name']+'.'+c['name'],'name':c['name'],'definitionPointer':c['definitionPointer']} for c in t['columns']]})
inv_art=artifact('truss-review08-declaration-map',inv)
field={'id':'label','name':'label','kind':'field','scalarType':'string','nullability':'required','cardinality':'one','extensions':{}}
record={'id':'item','name':'Item','kind':'record','members':[{'module':'fixture','element':'label'}],'extensions':{}}
doc={'umf':'0.7.0','id':'truss-weft-source-review-fixture','vocabularies':{},'modules':[{'id':'fixture','namespace':'fixture','elements':[record,field]}]}
doc_bytes=raw(doc);model_input={'documentJson':doc_bytes.decode(),'pin':{'documentId':doc['id'],'revision':'source-fixture-r1','umfVersion':'0.7.0','sha256':digest(doc_bytes)},'selectedModuleIds':['fixture']}
identity={'documentId':doc['id'],'revision':'source-fixture-r1','module':'fixture','element':'item'};field_identity={**identity,'element':'label'}
bp=pin('truss-source-review-binding','Exact original artifacts and declared physical selectors; absence of native/registry authority must refuse execution')
lp=pin('truss-review-layout08','Selected declaration model/SQL; source-only inventory does not prove installed parity')
hp=pin('truss-source-review-props','Top-level JSONB member of object.props, typed owner and exact property ID')
vp=pin('truss-source-review-value','Original UMF scalar string; no coercion/default')
pp=pin('truss-source-review-presence','Absent/null/value are distinct; authored required nonnullable string refuses absence/null')
cp=pin('truss-source-review-string-codec','Preserve Unicode scalar string and exact original field meaning')
sp=pin('truss-source-review-umf-interpretation','Original UMF 0.7.0 string definition, pinned source; no reinterpretation')
np=pin('truss-source-review-jsonb-domain','Declared object.props jsonb; source declaration only, native input/output/encoding unqualified')
rp=pin('truss-source-review-read-context','Actual executor/catalog/layout/authority/decoder admission required; no synthetic context may execute')
res=pin('truss-source-review-resource','Four MiB binding and decoded closure ceilings; no unbounded native result or codec processing')
field_art=artifact('original-fixture-label-definition',field)
codec={'interfaceVersion':'truss-jsonb-leaf-codec/0.1.0','profile':cp,'authoredDefinition':field_art,'sourceInterpretationProfile':sp,'sourceInterpretationDefinition':artifact('source-interpretation-fixture',{'status':'synthetic-source-review','umfVersion':'0.7.0','field':field,'meaning':'scalar Unicode string; required; no coercion'}),'nativeDomainProfile':np,'nativeDomainDefinition':artifact('declared-jsonb-domain-fixture',{'status':'source-only','nativeQualified':False,'relationPhysicalIdentity':'truss.review08.table.object','columnPhysicalIdentity':'truss.review08.column.object.props','declaredType':'jsonb','requiredNativeEvidence':['UTF8 input/output','original codec/domain parity','current authority and native stored-domain integrity']}),'rule':{'family':'string','storageRepresentation':'json-string','encoding':'preserve-unicode-scalars','decodedCarrierKind':'string'},'coercion':'none','readDefault':'none','invalidStoredValue':'complete-result-refusal'}
value={'interfaceVersion':'truss-value-definition/0.1.0','profile':vp,'rootNodeId':'label','acceptedDefinition':field_art,'nodes':[{'nodeId':'label','authoredIdentity':field_identity,'authoredDefinition':field_art,'codecProfile':cp,'codecDefinition':artifact('fixture-string-codec',codec),'shape':{'kind':'scalar','family':'string','storageRepresentation':'json-string'}}]}
presence={'interfaceVersion':'truss-presence-definition/0.1.0','profile':pp,'carrierSchema':'urn:truss:draft:exact-value:0.1.0#/$defs/presence','storageRoot':'nonnull-jsonb-object','absentMember':'present-false','jsonNullMember':'present-null-if-authored-nullable','emptyCollection':'present-empty-typed-value','sqlNullRoot':'integrity-refusal','nativeNullValue':'unsupported-without-separate-profile','defaultApplication':'none-on-read','acceptedDefinition':field_art}
home={'interfaceVersion':'truss-property-home/0.1.0','layoutInventory':inv_art,'recordKind':'object','relationPhysicalIdentity':'truss.review08.table.object','propsColumnPhysicalIdentity':'truss.review08.column.object.props','discriminatorColumnPhysicalIdentity':'truss.review08.column.object.type_id','relationName':'object','propsColumnName':'props','discriminatorColumnName':'type_id','ownerCatalogId':'17','propertyCatalogId':'23','memberName':'23','accessor':'jsonb-top-level-member','presenceProfile':pp,'valueProfile':vp}
context={'interfaceVersion':'truss-read-context-definition/0.1.0','profile':rp,'contextSchema':'urn:truss:draft:direct-cursor:0.1.0#/$defs/context','allowedConsistency':['live','held_snapshot'],'catalogAdmission':'original-binding-matches-admitted-view','layoutAdmission':'original-physical-and-encoding-profiles-match','authorityAdmission':'actual-current-role-and-effective-policy','transactionAdmission':'executor-issued-live-affine-context','snapshotAdmission':'original-registry-custody-and-retained-stores','publicationAdmission':'complete-result-current-disclosure-and-resource-check','onMismatch':'refuse-before-sql','resourceProfile':res,'resourceDefinition':artifact('fixture-resource-requirements',{'bindingBytes':4194304,'decodedArtifactClosureBytes':4194304,'status':'requirements-only','nativeQualified':False}),'requiredHostObligations':['refuse-unregistered-source-fixture','original-stored-domain','current-authority','complete-result-decoder']}
source_art=artifact_bytes('original-fixture-document',doc_bytes)
qualification={'status':'synthetic-source-review','nativeQualified':False,'bindingAdopted':False,'queryExecuted':False,'scope':'One original required string property; not keys/edges/nullable/recursive/native-row support'}
binding={'interfaceVersion':'truss-postgresql-binding/0.1.0','bindingProfile':bp,'bindingProfileId':'truss-postgresql-source-review/0.8.0-fixture','basis':{'modelBundle':artifact('original-logical-model-bundle',[model_input]),'catalogRevision':'1','acceptedCatalog':artifact('synthetic-catalog-state',{'status':'synthetic-not-accepted','revision':'1','types':[{'typeId':'17','logical':identity}],'properties':[{'ownerTypeId':'17','propertyId':'23','logical':field_identity,'home':'props'}]}),'layoutProfile':lp,'layoutInventory':inv_art,'layoutSql':artifact_bytes('selected-review08-layout-sql',(R/'docs/helix/02-design/models/truss-layout-weft-review-0.8.proposal.sql').read_bytes()),'exporterProfile':pin('truss-source-review-exporter','Deterministic original source fixture assembly; not a production exporter'),'namespace':'truss','identityProfile':pin('truss-source-review-identity','Document/module/authored-element identity distinct from storage IDs'),'valueProfile':vp,'keyProfile':pin('truss-source-review-no-key','No logical keys mapped; no key capability implied'),'readContextProfile':rp,'readContextDefinition':artifact('fixture-read-context',context)},'entities':[{'logical':identity,'typeId':'17','acceptedDefinition':artifact('original-fixture-item-definition',record),'source':source_art}],'properties':[{'logical':field_identity,'ownerTypeId':'17','propertyId':'23','home':'props','homeProfile':hp,'homeDefinition':artifact('fixture-label-home',home),'valueProfile':vp,'valueDefinition':artifact('fixture-label-value',value),'presenceProfile':pp,'presenceDefinition':artifact('fixture-label-presence',presence),'acceptedDefinition':field_art,'source':source_art}],'keys':[],'relationships':[],'executionObligations':[{'id':'refuse-unregistered-source-fixture','profile':rp,'definition':artifact('source-fixture-execution-refusal',{'registered':False,'nativeQualified':False,'expected':'refuse-before-sql'})}],'qualification':[artifact('source-fixture-qualification',qualification)]}
(OUT/'binding.json').write_bytes(raw(binding)+b'\n');(OUT/'original-model.json').write_bytes(doc_bytes);(OUT/'profile-definitions.json').write_bytes(raw(profiles)+b'\n')
(OUT/'declaration-map.json').write_bytes(raw(inv)+b'\n')
(OUT/'nested-definitions.json').write_bytes(raw({'home':home,'value':value,'presence':presence,'codec':codec,'context':context})+b'\n')
print(json.dumps({'bindingBytes':len(raw(binding))+1,'tables':len(inv['tables']),'columns':sum(len(t['columns']) for t in inv['tables']),'nativeQualified':False}))
