/** Truss-specific structural authoring from original UMF declarations, not SQL generation. */
import {readDocument,writeDocument} from '/Users/erik/Projects/umf/src/model/document';
import {getPostgresqlDdlDeclarations} from '/Users/erik/Projects/umf/src/adapters/postgresql/declarations';
import {getPostgresqlSource} from '/Users/erik/Projects/umf/src/adapters/postgresql';
import {renderTree} from '/Users/erik/Projects/umf/src/model/native-json';
import {validateDocument} from '/Users/erik/Projects/umf/src/validation/document';
const basePath='docs/helix/02-design/models/truss-layout-core-structural-0.6.proposal.umf.json';
const sourcePath='docs/helix/02-design/contracts/row-home-capacity-reservation-v0.1.proposal.umf.json';
const sqlPath='docs/helix/02-design/contracts/row-home-capacity-reservation-v0.1.proposal.sql';
const modelPath='docs/helix/02-design/models/truss-layout-core-structural-0.7.proposal.umf.json';
const receiptPath='docs/helix/04-build/evidence/design-audit/capacity-reservation-core-source.json';
for(const p of [modelPath,receiptPath])if(await Bun.file(p).exists())throw Error('Original output exists');
const hash=(v:string|ArrayBuffer)=>new Bun.CryptoHasher('sha256').update(v).digest('hex');
const frozen=new Map(await Promise.all([basePath,sourcePath,sqlPath].map(async p=>[p,await Bun.file(p).text()] as const)));
const base=readDocument(frozen.get(basePath)!,'json');
const model=readDocument(frozen.get(basePath)!,'json');
const native=readDocument(frozen.get(sourcePath)!,'json');
if(getPostgresqlSource(native)!==frozen.get(sqlPath))throw Error('Original reservation source mismatch');
const inventory=getPostgresqlDdlDeclarations(native);
if(inventory.declarations.length!==1||inventory.unhandled.length!==0||inventory.complete!==false)throw Error('Unexpected owner declaration scope');
const declaration=inventory.declarations[0];
const relation=JSON.parse(renderTree(declaration.relation));
if(declaration.kind!=='alter-table'||relation.schemaname!=='truss'||relation.relname!=='row_home_capacity')throw Error('Original target mismatch');
const expected=['reservation_writer_xid','reservation_operation_ordinal','reservation_context_bytes','reservation_plan_bytes','reservation_initial_rows','reservation_initial_custody_bytes'];
if(JSON.stringify(declaration.columns.map(c=>c.element.name))!==JSON.stringify(expected))throw Error('Complete column correspondence mismatch');
const module=model.modules.find(m=>m.id==='truss-layout')!;
const record=module.elements.find(e=>e.id==='row_home_capacity')!;
const originalRecord=JSON.parse(JSON.stringify(record));
const fields=[];
for(const c of declaration.columns){
 const column=JSON.parse(renderTree(c.nativeColumn));
 const name=c.element.name!;const id='row_home_capacity.'+name;
 if(module.elements.some(e=>e.id===id))throw Error('Duplicate qualified Field');
 const parts=column.typeName.names.map((v:any)=>v.String.sval);
 const family=parts.at(-1);
 const scalarType=family==='xid8'?'postgresql.xid8':family==='int8'?'integer':family==='bytea'?'binary':undefined;
 if(!scalarType)throw Error('Unreviewed structural family');
 const field={id,name,kind:'field',scalarType,cardinality:'one',nullability:'unspecified',extensions:{'truss.layout.native':{sourceModel:sourcePath,sourcePointer:c.path,nativeType:column.typeName,constraints:column.constraints??[],collation:column.collClause??null,sqlNullMeaning:'Native SQL NULL and coupled CHECK semantics retained; not inferred core absence',scope:'Uninstalled reservation adjunct; native xid8 identity/equality remains unqualified'}}};
 module.elements.push(field as any);fields.push(field);
 record.members!.push({module:module.id,element:id});record.references!.push({role:'member',module:module.id,element:id});
}
record.extensions!['truss.layout.native']={reservationSourceModel:sourcePath,reservationSourceSha256:hash(frozen.get(sourcePath)!),nativeStatement:JSON.parse(renderTree(declaration.nativeStatement)),scope:'Coupled reservation CHECK retained exactly; source syntax is not native authority'};
model.id='truss-layout-core-structural-0.7-reservation-review';
(model.extensions!['truss.layout.native'] as any)={...(model.extensions!['truss.layout.native'] as any),structuralSource:basePath,structuralSourceSha256:hash(frozen.get(basePath)!),reservationSourceModel:sourcePath,reservationSourceSha256:hash(frozen.get(sourcePath)!),scope:'Structural projection of native0.16 plus uncomposed configuration, migration and capacity reservation adjuncts. Inspection cannot certify installed layout, portable xid8 equality or protected runtime.'};
const beforeRelationships=JSON.stringify(base.modules[0].relationships);
if(JSON.stringify(module.relationships)!==beforeRelationships)throw Error('Foreign relationships changed');
const restored=JSON.parse(JSON.stringify(model));restored.id=base.id;restored.extensions=base.extensions;
restored.modules[0].elements=restored.modules[0].elements.filter((e:any)=>!fields.some(f=>f.id===e.id));
restored.modules[0].elements[restored.modules[0].elements.findIndex((e:any)=>e.id===record.id)]=originalRecord;
if(JSON.stringify(restored)!==JSON.stringify(base))throw Error('Original core content changed outside explicit adjunct');
const validation=validateDocument(model);
if(!validation.valid)throw Error('Structural document invalid: '+JSON.stringify(validation.diagnostics));
const serialized=writeDocument(model,'json');
if(JSON.stringify(readDocument(serialized,'json'))!==JSON.stringify(model))throw Error('Saved model meaning differs');
for(const [p,b] of frozen)if(await Bun.file(p).text()!==b)throw Error('Original input changed');
await Bun.write(modelPath,serialized);
const result={scope:'Six original reservation columns authored as core Fields on original Record; unchanged complete original core/FK content; not native semantic, DDL or installation equivalence',sourceSha256:Object.fromEntries([...frozen].map(([p,b])=>[p,hash(b)])),modelPath,modelSha256:hash(serialized),producerSha256:hash(await Bun.file(import.meta.path).arrayBuffer()),recordCount:module.elements.filter(e=>e.kind==='record').length,fieldCount:module.elements.filter(e=>e.kind==='field').length,associationCount:module.relationships?.length??0,originalCoreRestoresExactly:true,originalRelationshipsUnchanged:true,fields:fields.map(f=>({id:f.id,scalarType:f.scalarType,sourcePointer:(f.extensions['truss.layout.native'] as any).sourcePointer})),valid:validation.valid,complete:validation.complete,diagnostics:validation.diagnostics,installerReady:false};
await Bun.write(receiptPath,JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({valid:result.valid,complete:result.complete,records:result.recordCount,fields:result.fieldCount,associations:result.associationCount,originalCoreRestoresExactly:true}));
