/** Traversal wire cases only; stage authentication, complete graph semantics and budgets unqualified. */
const {default:Ajv}=await import(process.argv[2]);const a=new Ajv({strict:true});
for(const n of ['exact-value','history-record','direct-cursor','direct-page-result','direct-traversal-request'])a.addSchema(await Bun.file(`docs/helix/02-design/contracts/${n}-v0.1.schema.json`).json());
const req=a.getSchema('urn:truss:draft:direct-traversal-request:0.1.0')!;
const resume=a.compile(await Bun.file('docs/helix/02-design/contracts/direct-traversal-resume-request-v0.1.schema.json').json());
const next=a.compile(await Bun.file('docs/helix/02-design/contracts/direct-traversal-page-request-v0.1.schema.json').json());
const result=a.compile(await Bun.file('docs/helix/02-design/contracts/direct-traversal-result-v0.1.schema.json').json());
const pin={identity:'fixture',version:'0.1.0',sha256:'a'.repeat(64)};const owner={documentId:'doc',moduleId:'module'};
const context={catalogRevision:'2',layoutProfile:pin,readProfile:pin,authorizedScopeIdentity:'scope',consistency:{kind:'held_snapshot',snapshotIdentity:'snapshot'}};
const start={id:'1',typeId:'1',definitionPin:'fixture',owner};const hop={relationship:{relationshipId:'2',definitionPin:'fixture',owner},direction:'outgoing'};
const workLimits={examinedEdges:'100',pathStates:'100',retainedBytes:'4096'};
const request={interfaceVersion:'truss-direct-traversal/0.1.0',context,start,hops:[hop],resultLimit:'10',workLimits};
const handle={stageIdentity:'stage',generation:'0',querySha256:'b'.repeat(64),context};const cursor={handle,after:{typeId:'1',id:'2'}};
const resumption={handle,expectedWorkVersion:'0',workLimits,resultLimit:'10'};
const page={outcome:'page',context,records:[],continuation:{state:'end'}};
const limited={outcome:'limited',reason:'examined_edges',completeness:'not_established',continuation:{state:'staged',handle,workVersion:'1'}};
let cases=0;const failures:string[]=[];
function test(check:any,name:string,value:unknown,want:boolean){cases++;if(Boolean(check(value))!==want)failures.push(name);}
test(req,'one hop',request,true);test(req,'three hops',{...request,hops:[hop,hop,hop]},true);
test(req,'no hops',{...request,hops:[]},false);test(req,'four hops',{...request,hops:[hop,hop,hop,hop]},false);
test(req,'no unbounded work',{...request,workLimits:{}},false);test(req,'zero result limit',{...request,resultLimit:'0'},false);
test(req,'no host numeric counter',{...request,workLimits:{...workLimits,pathStates:100}},false);
test(req,'direction closed',{...request,hops:[{...hop,direction:'any'}]},false);
test(resume,'resume',resumption,true);test(resume,'resume requires prior version',{handle,workLimits,resultLimit:'10'},false);
test(resume,'cannot replace query',{...resumption,hops:[hop]},false);
test(resume,'forged registry remains semantic',{...resumption,handle:{...handle,stageIdentity:'forged'}},true);
test(resume,'smaller cumulative bound remains semantic',{...resumption,workLimits:{...workLimits,examinedEdges:'1'}},true);
test(next,'next sealed page',{cursor,resultLimit:'10'},true);test(next,'boundary needs typed identity',{cursor:{...cursor,after:{id:'2'}},resultLimit:'10'},false);
test(result,'empty complete page',page,true);test(result,'staged limited',limited,true);
test(result,'restart limited',{...limited,continuation:{state:'restart'}},true);
test(result,'limited cannot disclose frontier',{...limited,records:[]},false);
test(result,'limited cannot claim complete',{...limited,completeness:'complete'},false);
test(result,'unavailable no partial page',{outcome:'unavailable',reason:'snapshot',records:[]},false);
test(result,'end has no cursor',{...page,continuation:{state:'end',cursor}},false);
test(result,'empty more requires semantic refusal',{...page,continuation:{state:'more',cursor}},true);
test(result,'stale generation requires semantic refusal',{...limited,continuation:{...limited.continuation,handle:{...handle,generation:'99'}}},true);
test(result,'assembly capacity refuses without records',{outcome:'unavailable',reason:'resource'},true);
test(result,'cumulative active work limit',{...limited,reason:'active_work'},true);
const releaseRequest=a.compile(await Bun.file('docs/helix/02-design/contracts/direct-traversal-release-request-v0.1.schema.json').json());
const releaseResult=a.compile(await Bun.file('docs/helix/02-design/contracts/direct-traversal-release-result-v0.1.schema.json').json());
test(result,'invalid request diagnostic',{outcome:'invalid',code:'hops',path:['hops']},true);
test(result,'invalid no partial records',{outcome:'invalid',code:'hops',path:[],records:[]},false);
test(releaseRequest,'original handle release',{handle},true);
test(releaseRequest,'cleanup cannot end host transaction',{handle,rollback:true},false);
test(releaseResult,'confirmed release',{outcome:'released'},true);
test(releaseResult,'unresolved requires retained custody',{outcome:'unresolved',recoveryReferences:['original-recovery']},true);
test(releaseResult,'no empty unresolved custody',{outcome:'unresolved',recoveryReferences:[]},false);
test(releaseResult,'confirmed has no leftover recovery',{outcome:'released',recoveryReferences:['original-recovery']},false);
test(releaseResult,'wrong owner unavailable',{outcome:'unavailable',reason:'ownership'},true);
test(releaseResult,'release no hidden stage data',{outcome:'unavailable',reason:'ownership',records:[]},false);
test(releaseResult,'forged recovery needs semantic refusal',{outcome:'unresolved',recoveryReferences:['forged']},true);
console.log(JSON.stringify({scope:'closed traversal operation shapes; semantic cases deliberately shape-valid',cases,failures},null,2));if(failures.length)process.exit(1);export {};
