/** Process-store record shape only; actual issuer/root replacement not executed. */
const {default:Ajv}=await import(process.argv[2]);const a=new Ajv({strict:true});
for(const n of ['direct-cursor','direct-traversal-request','traversal-resource-ledger'])a.addSchema(await Bun.file(`docs/helix/02-design/contracts/${n}-v0.1.schema.json`).json());
const check=a.compile(await Bun.file('docs/helix/02-design/contracts/traversal-store-observation-v0.1.schema.json').json());
const pin={identity:'fixture',version:'0.1.0',sha256:'a'.repeat(64)};const ref={identity:'original',sha256:'b'.repeat(64)};
const context={catalogRevision:'2',layoutProfile:pin,readProfile:pin,authorizedScopeIdentity:'scope',consistency:{kind:'held_snapshot',snapshotIdentity:'snapshot'}};
const v={interfaceVersion:'truss-traversal-store-observation/0.1.0',storeProfile:pin,serviceIdentity:'service',serviceGeneration:'0',assemblyId:'assembly',handle:{stageIdentity:'stage',generation:'0',querySha256:'b'.repeat(64),context},originalAttemptIdentity:'attempt',transition:'publish',previousRootSequence:'4',resultingRootSequence:'5',previousWorkVersion:'1',resultingWorkVersion:'2',accountingVersion:'3',originalQuery:ref,previousState:ref,resultingState:ref,resourceLedger:ref,resultingPhase:'sealed',retention:'process_lifetime'};
const cases:[string,unknown,boolean][]=[['publication root record',v,true],['no crash durability',{...v,retention:'restart_durable'},false],['no caller issued credential',{...v,lease:{}},false],['no future publication hash',{...v,publicationEvidence:ref},false],['no database commit',{...v,committed:true},false],['missing original issuer',Object.fromEntries(Object.entries(v).filter(([k])=>k!=='serviceIdentity')),false],['unchanged root needs semantic refusal',{...v,resultingRootSequence:'4'},true],['wrong issuer generation needs custody refusal',{...v,serviceGeneration:'99'},true],['wrong attempt needs original registry refusal',{...v,originalAttemptIdentity:'substitute'},true]];
const failures=cases.filter(([,v,e])=>Boolean(check(v))!==e).map(([n])=>n);console.log(JSON.stringify({scope:'original store record shape; atomicity/custody unqualified',cases:cases.length,failures},null,2));if(failures.length)process.exit(1);export {};
