/** Scoped current UMF public value validation; no Truss codec/native qualification. */
import {validateCoreFieldValue,validateDocument} from '/Users/erik/Projects/umf/src/index';
import type {Document} from '/Users/erik/Projects/umf/src/model/types';
const doc:Document={umf:'0.8.0',id:'truss-numeric-boundary-review',vocabularies:{},modules:[{id:'m',namespace:'m',elements:[{id:'integer',kind:'field',scalarType:'integer',nullability:'required',extensions:{},facets:{integerWidth:{bits:64,signed:true}}},{id:'decimal',kind:'field',scalarType:'decimal',nullability:'required',extensions:{},facets:{precision:3,scale:1}}]}]};
if(!validateDocument(doc).valid)throw Error('invalid original fixture');
const cases=[['integer-negative-zero','integer',{integerToken:'-0'},true],['decimal-negative-zero','decimal',{decimalToken:'-0.00'},true],['decimal-exact-half','decimal',{decimalToken:'12.5'},true],['decimal-authored-tenth','decimal',{decimalToken:'0.1'},true],['decimal-rounding','decimal',{decimalToken:'0.125'},false],['decimal-nan','decimal',{decimalToken:'NaN'},false],['decimal-infinity','decimal',{decimalToken:'Infinity'},false],['integer-overflow','integer',{integerToken:'9223372036854775808'},false]] as const;
const results=cases.map(([id,field,value,expected])=>{const before=JSON.stringify(value),result=validateCoreFieldValue(doc,{module:'m',element:field},value);if(result.valid!==expected||JSON.stringify(value)!==before)throw Error(id);return {id,value,expectedValid:expected,result,inputUnchanged:true};});
const sourceFiles=['src/model/schema-literals.ts','src/model/schema-properties.ts'];const pins=Object.fromEntries(await Promise.all(sourceFiles.map(async p=>[p,new Bun.CryptoHasher('sha256').update(await Bun.file('/Users/erik/Projects/umf/'+p).arrayBuffer()).digest('hex')])));
await Bun.write('docs/helix/04-build/evidence/design-audit/umf-numeric-boundaries.json',JSON.stringify({scope:'UMF 0.8.0 synthetic integer/decimal public validation and input preservation only; no convenience constructor, float meaning, browser or Truss/native qualification',umfCommit:'16c35e8d943769ccfa7bb57d16785aa7159abe65',sourceSha256:pins,originalDocument:doc,cases:results,nativeQualified:false},null,2)+'\n');
console.log(JSON.stringify({cases:results.length,passed:true,nativeQualified:false}));
