/** Cohort shape only; native original parent/stage eligibility and membership untested. */
const {default:Ajv}=await import(process.argv[2]);const a=new Ajv({strict:true});
const base='docs/helix/02-design/contracts/';const paths=['acceptance-input-v0.1.schema.json','private-custody-snapshot-v0.1.proposal.schema.json','journal-stage-snapshot-v0.2.proposal.schema.json','journal-stage-cleanup-cohort-v0.2.proposal.schema.json'];
for(const p of paths)a.addSchema(await Bun.file(base+p).json());
const v=a.getSchema('urn:truss:proposal:journal-stage-cleanup-cohort:0.2.0')!;
const artifact={identity:'fixture',bytesBase64:'e30=',sha256:'a'.repeat(64)},pin={identity:'fixture',version:'0.1.0',sha256:'b'.repeat(64)};
const raw=await Bun.file(base+'private-custody-snapshot-v0.1.proposal.schema.json').json();
const fields=Object.fromEntries(raw.oneOf[0].properties.fields.required.map((k:string)=>[k,k.endsWith('_hex')?'7b7d':k==='phase'?'application_finalized':k==='operation_kind'?'mutation':'0']));fields.original_writer_xid='7';
const fixture=()=>({interfaceVersion:'truss-journal-stage-cleanup-cohort/0.2.0-proposal',profile:pin,originalOperationSnapshot:{kind:'operation',fields:structuredClone(fields)},stages:[{interfaceVersion:'truss-journal-stage-snapshot/0.2.0-proposal',kind:'journal-stage',fields:{original_writer_xid:'7',operation_ordinal:'0',stage_name:'start',stage_ordinal:'0',effect_generation:'0',body_bytes_hex:'7b7d'}}],...Object.fromEntries(['originalInstallation','originalLayout','originalAdministrativeContext','originalSettlement','originalDependencyClosure','originalResourceReservation','originalStageMembership'].map(k=>[k,structuredClone(artifact)]))}) as any;
const cases:[string,(x:any)=>void,boolean][]=[['complete cohort shape',()=>{},true],['empty with proof',x=>{x.stages=[];x.originalEmptyStageEvidence=artifact},true],['empty without proof',x=>{x.stages=[]},false],['nonempty with empty claim',x=>{x.originalEmptyStageEvidence=artifact},false],['missing parent',x=>{delete x.originalOperationSnapshot},false],['missing settlement',x=>{delete x.originalSettlement},false],['missing membership',x=>{delete x.originalStageMembership},false],['extra deletion success',x=>{x.deleted=true},false],['foreign parent stage needs semantic refusal',x=>{x.stages[0].fields.original_writer_xid='8'},true],['duplicate stage needs semantic refusal',x=>{x.stages.push(structuredClone(x.stages[0]))},true],['forged artifact needs native refusal',x=>{x.originalSettlement.identity='forged'},true]];
const results=cases.map(([name,change,expected])=>{const x=fixture();change(x);const actual=v(x);if(actual!==expected)throw Error(name+JSON.stringify(v.errors));return {name,expected,actual}});
const sources=await Promise.all([...paths.map(p=>base+p),import.meta.path].map(async path=>({path,sha256:new Bun.CryptoHasher('sha256').update(await Bun.file(path).text()).digest('hex')})));
await Bun.write('docs/helix/04-build/evidence/design-audit/journal-stage-cleanup-cohort-audit.json',JSON.stringify({scope:'closed cohort shape only; fixture artifacts are placeholders',bunVersion:Bun.version,sources,results,nativeExecuted:false,adopted:false},null,2)+'\n');console.log(JSON.stringify({cases:results.length,nativeExecuted:false}));
