/** Private completion shape only; original termination/usage/time producer unqualified. */
const {default:Ajv}=await import(process.argv[2]);const a=new Ajv({strict:true});
for(const n of ['direct-cursor','direct-traversal-request','traversal-resource-ledger'])a.addSchema(await Bun.file(`docs/helix/02-design/contracts/${n}-v0.1.schema.json`).json());
const check=a.compile(await Bun.file('docs/helix/02-design/contracts/traversal-work-completion-v0.1.schema.json').json());
const pin={identity:'fixture',version:'0.1.0',sha256:'a'.repeat(64)};const ref={identity:'original',sha256:'b'.repeat(64)};
const context={catalogRevision:'2',layoutProfile:pin,readProfile:pin,authorizedScopeIdentity:'scope',consistency:{kind:'held_snapshot',snapshotIdentity:'snapshot'}};
const v={interfaceVersion:'truss-traversal-work-completion/0.1.0',assemblyId:'assembly',handle:{stageIdentity:'stage',generation:'0',querySha256:'b'.repeat(64),context},storeProfile:pin,completionProfile:pin,permitIdentity:'permit',workerIdentity:'worker',originalAdmission:ref,admittedAccountingVersion:'1',actualIncrements:{examinedEdges:'8',pathStates:'6',activeWorkMilliseconds:'80'},retainedBytes:'1000',reservationBytes:'4096',termination:'confirmed',originalTermination:ref,originalUsage:ref,originalClockSpan:ref};
const cases:[string,unknown,boolean][]=[['complete usage metadata',v,true],['unknown termination cannot settle',{...v,termination:'unknown'},false],['clock custody mandatory',Object.fromEntries(Object.entries(v).filter(([k])=>k!=='originalClockSpan')),false],['no future settlement receipt',{...v,settled:true},false],['no frontier payload',{...v,frontier:[]},false],['no host numeric time',{...v,actualIncrements:{...v.actualIncrements,activeWorkMilliseconds:80}},false],['wrong permit requires custody refusal',{...v,permitIdentity:'other'},true],['forged termination requires native refusal',{...v,originalTermination:{...ref,identity:'forged'}},true],['false zero work needs independent usage refusal',{...v,actualIncrements:{examinedEdges:'0',pathStates:'0',activeWorkMilliseconds:'0'}},true]];
const failures=cases.filter(([,v,e])=>Boolean(check(v))!==e).map(([n])=>n);console.log(JSON.stringify({scope:'completion metadata shapes; termination/usage/time unqualified',cases:cases.length,failures},null,2));if(failures.length)process.exit(1);export {};
