/** Shape witnesses only; no native archive continuity or disclosure qualification. */
const {default:Ajv}=await import(process.argv[2]);const ajv=new Ajv({strict:true});
for(const name of ['acceptance-input','exact-value','history-record','history-event'])ajv.addSchema(await Bun.file(`docs/helix/02-design/contracts/${name}-v0.1.schema.json`).json());
const validate=ajv.compile(await Bun.file('docs/helix/02-design/contracts/retained-history-archive-v0.1.schema.json').json());
const pin={identity:'fixture',version:'0.1.0',sha256:'a'.repeat(64)},artifact={identity:'fixture',bytesBase64:'e30=',sha256:'a'.repeat(64)};
const identity={id:'1',typeId:'1',definitionPin:'definition',owner:{documentId:'doc',moduleId:'module'}};
const baseline={interfaceVersion:'truss-history-record/0.1.0',identity,recordVersion:'1',catalogRevision:'1',createdAt:'fixture',updatedAt:'fixture',properties:[],retained:[],kind:'object',ownership:{state:'rootless'}};
const event={interfaceVersion:'truss-history-event/0.1.0',sourceEpoch:'epoch',historyProfile:'draft',xid:'1',seq:'1',identity,eventVersion:'2',eventCatalogRevision:'1',mutationGroup:{profile:'truss-history-group/0.1.0',eventCount:'1',orderedEventDigest:'0'.repeat(64)},origin:{asserted:{kind:'null'},databaseRole:'role'},operation:'property',propertyId:'1',definitionPin:'property',before:{present:false},after:{present:true,value:{kind:'decimal',text:'1.00'}}};
const fixture={interfaceVersion:'truss-retained-history-archive/0.1.0',sourceEpoch:'epoch',archiveProfile:pin,identity,baseline,throughVersion:'1',events:[],definitions:[{definitionPin:'definition',interpretationProfile:pin,artifact}],baselineEvidence:artifact,completeEventInventory:artifact,retainedOwnerInventory:artifact,retentionEvidence:artifact};
const cases:[string,unknown,boolean][]=[
 ['baseline-only horizon',fixture,true],['event horizon',{...fixture,throughVersion:'2',events:[event],definitions:[...fixture.definitions,{definitionPin:'property',interpretationProfile:pin,artifact}]},true],
 ['missing owner',{...fixture,retainedOwnerInventory:undefined},false],['missing native inventory',{...fixture,completeEventInventory:undefined},false],['numeric version',{...fixture,throughVersion:1},false],['unknown event',{...fixture,events:[{operation:'future'}]},false],
 ['future without events needs semantic refusal',{...fixture,throughVersion:'9'},true],['wrong baseline identity needs semantic refusal',{...fixture,baseline:{...baseline,identity:{...identity,id:'2'}}},true],['event wrong epoch needs semantic refusal',{...fixture,throughVersion:'2',events:[{...event,sourceEpoch:'other'}]},true],['conflicting definition needs semantic refusal',{...fixture,definitions:[...fixture.definitions,{...fixture.definitions[0],artifact:{...artifact,identity:'different'}}]},true]
];
const failures=cases.filter(([,v,e])=>Boolean(validate(v))!==e).map(([n])=>n);const receipt={scope:'Retained archive shape only; identity/epoch/continuity/definition conflicts require semantic refusal; no native qualification',cases:cases.length,failures};await Bun.write('docs/helix/04-build/evidence/design-audit/retained-history-archive.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));if(failures.length)process.exit(1);
