/** Fixture shape only; native completeness and byte/provenance admission remain unproved. */
const {default:Ajv}=await import(process.argv[2]);const root='docs/helix/02-design/contracts/';const ajv=new Ajv({strict:true});
for(const f of ['acceptance-input','exact-value','history-record','key-bindings','key-profile-migration','key-migration-result','key-migration-source-inventory','key-migration-target-correspondence','key-migration-blocked-report','key-migration-components','key-migration-receipt','key-migration-bucket-collection'])ajv.addSchema(await Bun.file(root+f+'-v0.1.schema.json').json());
const sourceCheck=ajv.getSchema('urn:truss:draft:key-migration-source-inventory:0.1.0')!;const targetCheck=ajv.getSchema('urn:truss:draft:key-migration-target-correspondence:0.1.0')!;
const pin={identity:'unqualified-fixture',version:'0.1.0',sha256:'0'.repeat(64)};const artifact={identity:'fixture',bytesBase64:'eA==',sha256:'0'.repeat(64)};
const attempt={kind:'installed',databaseIdentity:'db',schemaName:'truss',installationId:'install',sourceEpoch:'epoch',migrationAttemptId:'attempt',procedure:pin,originalRequest:artifact};
const basis={layout:pin,catalog:artifact,encoding:pin,bucket:pin,installedPolicy:artifact};
const identity={id:'1',typeId:'2',definitionPin:'original',owner:{documentId:'doc',moduleId:'module'}};
const binding={bindingId:'binding',record:{documentId:'doc',moduleId:'module',recordId:'record',definitionPin:'original'},kind:'portable_identity',authoredKeyId:'authored',tupleProfile:pin,transportProfile:pin,components:[{authoredPropertyId:'field',definitionPin:'original'}]};
const fullKey={namespace:artifact,key:artifact,encoding:pin,namespaceSha256:'0'.repeat(64),keySha256:'0'.repeat(64)};
const entry={entryId:'a',binding,localKeyNumber:'0',originalDefinition:artifact,components:{state:'preserved',original:artifact},kind:'live',identity,recordVersion:'0',membership:{state:'held',fullKey}};
const source={interfaceVersion:'truss-key-migration-source-inventory/0.1.0',originalAttempt:attempt,source:basis,inventoryProfile:pin,entryIdentityProfile:pin,entries:[entry],collection:{procedure:pin,observation:artifact,rawEvidence:[artifact],completeScopeEvidence:artifact}};
const target={interfaceVersion:'truss-key-migration-target-correspondence/0.1.0',originalAttempt:attempt,sourceInventory:artifact,target:basis,correspondenceProfile:pin,entries:[{sourceEntryId:'a',state:'held',fullKey,derivation:{kind:'owner_encoder',profile:pin,evidence:artifact}}],completeCoverageEvidence:artifact};
let cases=0;const failures:string[]=[];const probe=(name:string,baseline:any,fn:any,expected:boolean,mutate:(v:any)=>void)=>{const v=structuredClone(baseline);mutate(v);cases++;if(Boolean(fn(v))!==expected)failures.push(name);};
probe('live key/version zero',source,sourceCheck,true,()=>{});
probe('missing held bytes',source,sourceCheck,false,v=>delete v.entries[0].membership.fullKey);
probe('missing components artifact',source,sourceCheck,false,v=>delete v.entries[0].components.original);
probe('empty native observations',source,sourceCheck,false,v=>v.collection.rawEvidence=[]);
probe('missing scope evidence',source,sourceCheck,false,v=>delete v.collection.completeScopeEvidence);
probe('aliased local key',source,sourceCheck,false,v=>v.entries[0].localKeyNumber='00');
probe('reservation with original bytes',source,sourceCheck,true,v=>{const e=v.entries[0];delete e.identity;delete e.recordVersion;delete e.membership;e.kind='reservation';e.originalReservation=artifact;e.originalRecordIdentity=identity;e.fullKey=fullKey;});
probe('sparse live omission',source,sourceCheck,true,v=>{const e=v.entries[0];e.binding={...binding,kind:'storage_uniqueness',missingComponent:'omit_and_report',encodingProfile:pin,components:[{property:{authoredPropertyId:'field',definitionPin:'original'},equalityProfile:pin,nullPolicy:'reject'}]};delete e.binding.authoredKeyId;delete e.binding.tupleProfile;delete e.binding.transportProfile;e.membership={state:'omitted',originalMissingComponentReport:artifact};});
probe('target held',target,targetCheck,true,()=>{});
probe('target lacks derivation',target,targetCheck,false,v=>delete v.entries[0].derivation);
probe('unrepresentable target',target,targetCheck,true,v=>v.entries=[{sourceEntryId:'a',state:'unrepresentable',reason:'missing_components',diagnostics:artifact}]);
probe('duplicate source needs semantic rejection',source,sourceCheck,true,v=>v.entries.push(v.entries[0]));
probe('missing target coverage needs semantic rejection',target,targetCheck,true,v=>v.entries=[]);
probe('wrong original attempt needs semantic rejection',target,targetCheck,true,v=>v.originalAttempt.migrationAttemptId='other');
probe('forged digest needs semantic rejection',source,sourceCheck,true,v=>v.entries[0].membership.fullKey.keySha256='f'.repeat(64));
probe('empty scope needs native proof',source,sourceCheck,true,v=>v.entries=[]);
probe('source identity profile required',source,sourceCheck,false,v=>delete v.entryIdentityProfile);
probe('selected ordinal entry one',source,sourceCheck,true,v=>{v.entryIdentityProfile={...pin,identity:'truss-migration-entry-ordinal',version:'0.1.0'};v.entries[0].entryId='entry:0000000000000000001';});
probe('selected ordinal zero rejects',source,sourceCheck,false,v=>{v.entryIdentityProfile={...pin,identity:'truss-migration-entry-ordinal',version:'0.1.0'};v.entries[0].entryId='entry:0000000000000000000';});
probe('selected ordinal short padding rejects',source,sourceCheck,false,v=>{v.entryIdentityProfile={...pin,identity:'truss-migration-entry-ordinal',version:'0.1.0'};v.entries[0].entryId='entry:1';});
probe('selected ordinal sign rejects',source,sourceCheck,false,v=>{v.entryIdentityProfile={...pin,identity:'truss-migration-entry-ordinal',version:'0.1.0'};v.entries[0].entryId='entry:+000000000000000001';});
probe('selected ordinal whitespace rejects',source,sourceCheck,false,v=>{v.entryIdentityProfile={...pin,identity:'truss-migration-entry-ordinal',version:'0.1.0'};v.entries[0].entryId='entry:0000000000000000001 ';});
probe('selected ordinal bigint maximum shape',source,sourceCheck,true,v=>{v.entryIdentityProfile={...pin,identity:'truss-migration-entry-ordinal',version:'0.1.0'};v.entries[0].entryId='entry:9223372036854775807';});
probe('selected ordinal overflow requires semantic refusal',source,sourceCheck,true,v=>{v.entryIdentityProfile={...pin,identity:'truss-migration-entry-ordinal',version:'0.1.0'};v.entries[0].entryId='entry:9223372036854775808';});
const reportCheck=ajv.getSchema('urn:truss:draft:key-migration-blocked-report:0.1.0')!;
const report={interfaceVersion:'truss-key-migration-blocked-report/0.1.0',sourceInventory:artifact,targetCorrespondence:artifact,reportProfile:pin,conflicts:[{fullKey,sourceEntryIds:['a','b'],policy:pin,evidence:artifact}],unrepresentableEntryIds:[],completeReportEvidence:artifact};
probe('complete conflict shape',report,reportCheck,true,()=>{});
probe('unrepresentable-only report',report,reportCheck,true,v=>{v.conflicts=[];v.unrepresentableEntryIds=['a'];});
probe('empty blocked report',report,reportCheck,false,v=>v.conflicts=[]);
probe('singleton conflict',report,reportCheck,false,v=>v.conflicts[0].sourceEntryIds=['a']);
probe('duplicate member',report,reportCheck,false,v=>v.conflicts[0].sourceEntryIds=['a','a']);
probe('duplicate unrepresentable entry',report,reportCheck,false,v=>v.unrepresentableEntryIds=['a','a']);
probe('missing report scope',report,reportCheck,false,v=>delete v.completeReportEvidence);
probe('invented member needs semantic rejection',report,reportCheck,true,v=>v.conflicts[0].sourceEntryIds=['a','not-in-source']);
probe('cross-class duplicate needs semantic rejection',report,reportCheck,true,v=>v.conflicts.push(v.conflicts[0]));
probe('digest-only equality claim needs semantic rejection',report,reportCheck,true,v=>v.conflicts[0].evidence=artifact);
const componentsCheck=ajv.getSchema('urn:truss:draft:key-migration-components:0.1.0')!;
const components={interfaceVersion:'truss-key-migration-components/0.1.0',captureProfile:pin,identity,recordVersion:'0',binding,originalDefinition:artifact,originalRecordEnvelope:artifact,components:[{property:{authoredPropertyId:'field',definitionPin:'original'},presence:{present:true,value:{kind:'decimal',text:'100.00'}}}]};
probe('original decimal spelling',components,componentsCheck,true,()=>{});
probe('absence remains distinct',components,componentsCheck,true,v=>v.components[0].presence={present:false});
probe('null remains distinct',components,componentsCheck,true,v=>v.components[0].presence={present:true,value:{kind:'null'}});
probe('missing original envelope',components,componentsCheck,false,v=>delete v.originalRecordEnvelope);
probe('empty component list',components,componentsCheck,false,v=>v.components=[]);
probe('absent with value',components,componentsCheck,false,v=>v.components[0].presence.present=false);
probe('host numeric token',components,componentsCheck,false,v=>v.components[0].presence.value.text=100);
probe('wrong component owner needs semantic rejection',components,componentsCheck,true,v=>v.components[0].property.authoredPropertyId='wrong');
probe('wrong original version needs semantic rejection',components,componentsCheck,true,v=>v.recordVersion='9');
const receiptCheck=ajv.getSchema('urn:truss:draft:key-migration-receipt:0.1.0')!;
const row={interfaceVersion:'truss-key-migration-receipt/0.1.0',receiptProfile:pin,originalAttempt:attempt,source:basis,target:basis,sourceInventory:artifact,targetCorrespondence:artifact,priorSelectedBinding:artifact,resultingSelectedBinding:artifact,installedInventory:artifact,transition:artifact,nativeSwitchEvidence:artifact};
probe('complete receipt row shape',row,receiptCheck,true,()=>{});
probe('missing original request',row,receiptCheck,false,v=>delete v.originalAttempt.originalRequest);
probe('missing prior binding',row,receiptCheck,false,v=>delete v.priorSelectedBinding);
probe('missing transition',row,receiptCheck,false,v=>delete v.transition);
probe('inline commit observation forbidden',row,receiptCheck,false,v=>v.commitObservation=artifact);
probe('self hash field forbidden',row,receiptCheck,false,v=>v.receiptSha256='0'.repeat(64));
probe('wrong original attempt needs native rejection',row,receiptCheck,true,v=>v.originalAttempt.migrationAttemptId='other');
probe('target-equals-current needs original proof',row,receiptCheck,true,v=>v.resultingSelectedBinding=artifact);
ajv.addSchema(await Bun.file(root+'import-report-v0.1.schema.json').json());
const transitionCheck=ajv.compile(await Bun.file(root+'feed-key-transition-basis-v0.2.schema.json').json());
const factCheck=ajv.compile(await Bun.file(root+'feed-key-transition-v0.2.schema.json').json());
const configuration={sourceEpoch:'epoch',installationId:'install',generation:'0',keyReuse:'forbid',journalMode:'engine',configurationProfile:pin,installedProducerInventorySha256:'0'.repeat(64)};
const transition={interfaceVersion:'truss-feed-key-transition-basis/0.2.0',transitionProfile:pin,context:{sourceEpoch:'epoch',feedProfile:'v02-fixture',scopeIdentity:'scope'},originalAttempt:attempt,source:basis,target:basis,priorConfiguration:configuration,resultingConfiguration:{...configuration,generation:'1'},priorSelectedBinding:artifact,resultingSelectedBinding:artifact,sourceInventory:artifact,targetCorrespondence:artifact};
const fact={interfaceVersion:'truss-feed-key-transition/0.2.0',transition:artifact,receipt:artifact};
probe('full transition basis',transition,transitionCheck,true,()=>{});
probe('original transition fact',fact,factCheck,true,()=>{});
probe('missing prior configuration',transition,transitionCheck,false,v=>delete v.priorConfiguration);
probe('missing original receipt',fact,factCheck,false,v=>delete v.receipt);
probe('later manifest hash forbidden',transition,transitionCheck,false,v=>v.manifestSha256='0'.repeat(64));
probe('inline commit observation forbidden',fact,factCheck,false,v=>v.commitObservation=artifact);
probe('cross-epoch configuration needs semantic rejection',transition,transitionCheck,true,v=>v.resultingConfiguration.sourceEpoch='other');
probe('nonincrementing generation needs semantic rejection',transition,transitionCheck,true,v=>v.resultingConfiguration.generation='0');
const manifestCheck=ajv.compile(await Bun.file(root+'feed-transaction-v0.2.schema.json').json());
const member={ordinal:'0',key:{kind:'key_profile_transition',sourceEpoch:'epoch',installationId:'install',migrationAttemptId:'attempt'},payloadProfile:pin,payloadSha256:'0'.repeat(64)};
const manifest={interfaceVersion:'truss-feed-transaction/0.2.0',context:transition.context,xid:'100',manifestProfile:pin,configurationPrerequisites:[{configuration,artifact}],members:[member],prerequisites:[],manifestSha256:'0'.repeat(64)};
probe('migration-only manifest',manifest,manifestCheck,true,()=>{});
probe('existing change member',manifest,manifestCheck,true,v=>v.members[0].key={kind:'change',seq:'1'});
probe('empty migration manifest',manifest,manifestCheck,false,v=>v.members=[]);
probe('missing attempt identity',manifest,manifestCheck,false,v=>delete v.members[0].key.migrationAttemptId);
probe('v01 disguised extension',manifest,manifestCheck,false,v=>v.interfaceVersion='truss-feed-transaction/0.1.0');
probe('duplicate member needs semantic rejection',manifest,manifestCheck,true,v=>v.members.push(v.members[0]));
probe('wrong transition epoch needs semantic rejection',manifest,manifestCheck,true,v=>v.members[0].key.sourceEpoch='other');
probe('invented manifest digest needs semantic rejection',manifest,manifestCheck,true,v=>v.manifestSha256='f'.repeat(64));
ajv.addSchema(await Bun.file(root+'feed-fragment-cursor-v0.2.schema.json').json());
const fragmentCheck=ajv.compile(await Bun.file(root+'feed-fragment-request-v0.2.schema.json').json());
const cursorV02={interfaceVersion:'truss-feed-fragment-cursor/0.2.0',context:transition.context,xid:'100',manifestSha256:'0'.repeat(64),deliveryProfile:pin,afterOrdinal:'0'};
const fragmentRequest={manifest,deliveryProfile:pin,limits:{records:'1',encodedBytes:'1000'},continuation:{state:'first'}};
probe('first fragment request',fragmentRequest,fragmentCheck,true,()=>{});
probe('v02 resumed fragment',fragmentRequest,fragmentCheck,true,v=>v.continuation={state:'after',cursor:cursorV02});
probe('old cursor refused',fragmentRequest,fragmentCheck,false,v=>v.continuation={state:'after',cursor:{...cursorV02,interfaceVersion:'truss-feed-fragment-cursor/0.1.0'}});
probe('zero record budget refused',fragmentRequest,fragmentCheck,false,v=>v.limits.records='0');
probe('numeric budget refused',fragmentRequest,fragmentCheck,false,v=>v.limits.encodedBytes=1000);
probe('missing resumed cursor',fragmentRequest,fragmentCheck,false,v=>v.continuation={state:'after'});
probe('wrong manifest resume needs semantic rejection',fragmentRequest,fragmentCheck,true,v=>v.continuation={state:'after',cursor:{...cursorV02,manifestSha256:'f'.repeat(64)}});
probe('out-of-range ordinal needs semantic rejection',fragmentRequest,fragmentCheck,true,v=>v.continuation={state:'after',cursor:{...cursorV02,afterOrdinal:'999'}});
const pageCheck=ajv.compile(await Bun.file(root+'feed-fragment-page-v0.2.schema.json').json());
const page={outcome:'available',fragment:{manifest,records:[{ordinal:'0',payload:artifact}]},continuation:{state:'end'}};
probe('available original fragment',page,pageCheck,true,()=>{});
probe('bounded resource refusal',{outcome:'unavailable',reason:'resource_limit'},pageCheck,true,()=>{});
probe('empty available records',page,pageCheck,false,v=>v.fragment.records=[]);
probe('unavailable leaking fragment',{outcome:'unavailable',reason:'authorization',fragment:page.fragment},pageCheck,false,()=>{});
probe('more without original cursor',page,pageCheck,false,v=>v.continuation={state:'more'});
probe('wrong ordinal needs semantic rejection',page,pageCheck,true,v=>v.fragment.records[0].ordinal='999');
probe('duplicate payload ordinal needs semantic rejection',page,pageCheck,true,v=>v.fragment.records.push(v.fragment.records[0]));
probe('payload hash mismatch needs semantic rejection',page,pageCheck,true,v=>v.fragment.records[0].payload.sha256='f'.repeat(64));
ajv.addSchema(await Bun.file(root+'seed-baseline-inventory-v0.1.schema.json').json());
ajv.addSchema(await Bun.file(root+'seed-baseline-v0.1.schema.json').json());
const seedCheck=ajv.compile(await Bun.file(root+'seed-baseline-v0.2.schema.json').json());
const seed={interfaceVersion:'truss-seed-baseline/0.2.0',attempt:{interfaceVersion:'truss-seed-activation/0.1.0',seedId:'seed',worker:{context:transition.context,consumerId:'consumer',registrationId:'registration',generation:'1'},activationProfile:pin},baselineProfile:pin,layoutProfile:pin,valueProfile:pin,interpretationProfile:pin,catalogRevision:'0',snapshotEvidence:artifact,records:[],revisions:[],sources:[],reservations:[],configurations:[],retainedArchives:[],keyBinding:{basis,selectedBinding:artifact,configuration,origin:{kind:'bootstrap',originalInitialization:artifact},chainAnchor:artifact},keyTransitions:[]};
probe('v02 original bootstrap seed',seed,seedCheck,true,()=>{});
probe('v02 migrated seed',seed,seedCheck,true,v=>{v.keyBinding.origin={kind:'migration',migrationAttemptId:'attempt'};v.keyTransitions=[{producingXid:'100',fact}];});
probe('missing selected binding',seed,seedCheck,false,v=>delete v.keyBinding);
probe('missing original anchor',seed,seedCheck,false,v=>delete v.keyBinding.chainAnchor);
probe('missing transition collection',seed,seedCheck,false,v=>delete v.keyTransitions);
probe('missing bootstrap original',seed,seedCheck,false,v=>delete v.keyBinding.origin.originalInitialization);
probe('migration without chain needs semantic rejection',seed,seedCheck,true,v=>v.keyBinding.origin={kind:'migration',migrationAttemptId:'attempt'});
probe('wrong cut binding epoch needs semantic rejection',seed,seedCheck,true,v=>v.keyBinding.configuration.sourceEpoch='other');
const seedInventoryCheck=ajv.compile(await Bun.file(root+'seed-baseline-inventory-v0.2.schema.json').json());
const seedInventory={interfaceVersion:'truss-seed-baseline-inventory/0.2.0',attempt:seed.attempt,inventoryProfile:pin,baselineSha256:'0'.repeat(64),visibilityManifestSha256:'0'.repeat(64),entries:[{ordinal:'0',identity:{kind:'key_binding',sourceEpoch:'epoch',installationId:'install'},payloadSha256:'0'.repeat(64),retainedOwnerEvidence:artifact}],extractionObservation:artifact};
probe('binding inventory identity',seedInventory,seedInventoryCheck,true,()=>{});
probe('transition inventory identity',seedInventory,seedInventoryCheck,true,v=>v.entries[0].identity={kind:'key_profile_transition',sourceEpoch:'epoch',installationId:'install',migrationAttemptId:'attempt'});
probe('empty v02 inventory',seedInventory,seedInventoryCheck,false,v=>v.entries=[]);
probe('missing binding installation',seedInventory,seedInventoryCheck,false,v=>delete v.entries[0].identity.installationId);
probe('missing native extraction',seedInventory,seedInventoryCheck,false,v=>delete v.extractionObservation);
probe('duplicate binding needs semantic rejection',seedInventory,seedInventoryCheck,true,v=>v.entries.push(v.entries[0]));
probe('transition-only lacks singleton needs semantic rejection',seedInventory,seedInventoryCheck,true,v=>v.entries[0].identity={kind:'key_profile_transition',sourceEpoch:'epoch',installationId:'install',migrationAttemptId:'attempt'});
probe('wrong binding epoch needs semantic rejection',seedInventory,seedInventoryCheck,true,v=>v.entries[0].identity.sourceEpoch='other');
const anchorCheck=ajv.compile(await Bun.file(root+'seed-key-binding-anchor-v0.2.schema.json').json());
const anchor={interfaceVersion:'truss-seed-key-binding-anchor/0.2.0',anchorProfile:pin,context:transition.context,installationId:'install',basis,selectedBinding:artifact,configuration,kind:'bootstrap',originalInitialization:artifact,originalInstalledInventory:artifact};
const retainedAnchor={...anchor,kind:'retained_cut',originalSnapshotEvidence:artifact,originalBindingState:artifact,retainedHistoryHorizon:artifact,archiveClosure:[artifact],completeScopeEvidence:artifact} as any;delete retainedAnchor.originalInitialization;delete retainedAnchor.originalInstalledInventory;
probe('bootstrap anchor',anchor,anchorCheck,true,()=>{});
probe('retained-cut anchor',retainedAnchor,anchorCheck,true,()=>{});
probe('missing original initialization',anchor,anchorCheck,false,v=>delete v.originalInitialization);
probe('empty retained archive closure',retainedAnchor,anchorCheck,false,v=>v.archiveClosure=[]);
probe('missing retained horizon',retainedAnchor,anchorCheck,false,v=>delete v.retainedHistoryHorizon);
probe('reverse baseline reference forbidden',anchor,anchorCheck,false,v=>v.baselineSha256='0'.repeat(64));
probe('cross-epoch anchor needs semantic rejection',anchor,anchorCheck,true,v=>v.configuration.sourceEpoch='other');
probe('invented original snapshot needs native rejection',retainedAnchor,anchorCheck,true,v=>v.originalSnapshotEvidence=artifact);
ajv.addSchema(await Bun.file(root+'feed-progress-v0.2.schema.json').json());
const proofCheck=ajv.compile(await Bun.file(root+'feed-application-proof-v0.2.schema.json').json());
const txBoundary={domain:'complete-feed-transaction/0.2.0',context:transition.context,xid:'100',manifestSha256:'0'.repeat(64)};
const proof={interfaceVersion:'truss-feed-application-proof/0.2.0',worker:seed.attempt.worker,downstreamIdentity:'downstream',prior:{state:'seed',context:transition.context,seedId:'seed',activationEvidenceSha256:'0'.repeat(64),seedProfile:pin},applied:txBoundary,intervalEvidence:artifact,committedApplicationEvidence:artifact};
probe('v02 submitted proof',proof,proofCheck,true,()=>{});
probe('old transaction domain refused',proof,proofCheck,false,v=>v.applied.domain='complete-feed-transaction/0.1.0');
probe('missing seed profile',proof,proofCheck,false,v=>delete v.prior.seedProfile);
probe('missing commit evidence',proof,proofCheck,false,v=>delete v.committedApplicationEvidence);
probe('serialized verified flag forbidden',proof,proofCheck,false,v=>v.verified=true);
probe('wrong generation needs semantic rejection',proof,proofCheck,true,v=>v.worker.generation='999');
probe('wrong prior epoch needs semantic rejection',proof,proofCheck,true,v=>v.prior.context.sourceEpoch='other');
probe('invented commit evidence needs native rejection',proof,proofCheck,true,v=>v.committedApplicationEvidence=artifact);
ajv.addSchema(await Bun.file(root+'feed-committed-application-v0.1.schema.json').json());
const commitCheck=ajv.compile(await Bun.file(root+'feed-committed-application-v0.2.schema.json').json());
const committedEvidence={interfaceVersion:'truss-feed-committed-application/0.2.0',applicationIdentity:'application',worker:seed.attempt.worker,downstreamIdentity:'downstream',downstreamProfile:pin,applicationProfile:pin,evidenceProfile:pin,prior:proof.prior,applied:txBoundary,operation:{kind:'transaction',manifest:artifact},intervalEvidence:artifact,admissionEvidence:artifact,durableTransitionInventory:artifact,commitObservation:{profile:pin,evidence:artifact}};
probe('v02 committed evidence shape',committedEvidence,commitCheck,true,()=>{});
probe('old committed evidence version',committedEvidence,commitCheck,false,v=>v.interfaceVersion='truss-feed-committed-application/0.1.0');
probe('old applied boundary domain',committedEvidence,commitCheck,false,v=>v.applied.domain='complete-feed-transaction/0.1.0');
probe('missing durable transition inventory',committedEvidence,commitCheck,false,v=>delete v.durableTransitionInventory);
probe('missing independent commit observation',committedEvidence,commitCheck,false,v=>delete v.commitObservation);
probe('boolean commit substituted',committedEvidence,commitCheck,false,v=>v.commitObservation=true);
probe('unrelated original manifest needs semantic rejection',committedEvidence,commitCheck,true,v=>v.operation.manifest=artifact);
probe('invented transition inventory needs native rejection',committedEvidence,commitCheck,true,v=>v.durableTransitionInventory=artifact);
ajv.addSchema(await Bun.file(root+'feed-interval-coverage-v0.1.schema.json').json());
const coverageCheck=ajv.compile(await Bun.file(root+'feed-interval-coverage-v0.2.schema.json').json());
const discoverySchema=await Bun.file(root+'feed-discovery-v0.2.schema.json').json();const discoveryCheck=ajv.compile(discoverySchema);const discoveryResultCheck=ajv.compile({$ref:discoverySchema.$id+'#/$defs/result'});
const discoveryRequest={interfaceVersion:'truss-feed-discovery/0.2.0',worker:seed.attempt.worker,after:proof.prior,discoveryProfile:pin,limits:{encodedBytes:'1000',scannedTransactions:'100'}};
const coverage={interfaceVersion:'truss-feed-coverage/0.2.0',context:transition.context,fromInclusiveXid:'100',throughExclusiveXid:'101',observedSafeWatermarkXid:'101',sourceEnumerationEvidence:artifact,retentionProtectionEvidence:artifact,transactions:[],coverageProfile:pin};
probe('v02 discovery request',discoveryRequest,discoveryCheck,true,()=>{});
probe('old discovery version refused',discoveryRequest,discoveryCheck,false,v=>v.interfaceVersion='truss-feed-discovery/0.1.0');
probe('zero native scan budget',discoveryRequest,discoveryCheck,false,v=>v.limits.scannedTransactions='0');
probe('next transition manifest',{outcome:'next',manifest,safeWatermarkXid:'101',observation:artifact},discoveryResultCheck,true,()=>{});
probe('unavailable cannot disclose manifest',{outcome:'unavailable',reason:'authorization',manifest},discoveryResultCheck,false,()=>{});
probe('coverage shape',coverage,coverageCheck,true,()=>{});
probe('old coverage version refused',coverage,coverageCheck,false,v=>v.interfaceVersion='truss-feed-coverage/0.1.0');
probe('omitted migration membership needs native rejection',coverage,coverageCheck,true,()=>{});
const applicationSchema=await Bun.file(root+'feed-application-v0.2.schema.json').json();const applicationCheck=ajv.compile(applicationSchema);const applicationResultCheck=ajv.compile({$ref:applicationSchema.$id+'#/$defs/result'});
const applicationRequest={interfaceVersion:'truss-feed-application/0.2.0',installation:{outcome:'installed',worker:seed.attempt.worker,downstreamApplied:proof.prior,installationEvidenceSha256:'0'.repeat(64)},transaction:{state:'complete',manifest,orderedPayloads:[artifact]},applicationProfile:pin};
probe('v02 complete application',applicationRequest,applicationCheck,true,()=>{});
probe('old application version',applicationRequest,applicationCheck,false,v=>v.interfaceVersion='truss-feed-application/0.1.0');
probe('empty complete payload inventory',applicationRequest,applicationCheck,false,v=>v.transaction.orderedPayloads=[]);
probe('missing actual installed progress',applicationRequest,applicationCheck,false,v=>delete v.installation.downstreamApplied);
probe('applied submitted evidence',{outcome:'applied',proofSubmission:proof,committedApplicationEvidence:artifact},applicationResultCheck,true,()=>{});
probe('unknown leaking proof',{outcome:'commit_unknown',recoveryReference:'original',originalAttemptEvidence:artifact,proofSubmission:proof},applicationResultCheck,false,()=>{});
probe('unavailable leaking committed evidence',{outcome:'unavailable',reason:'authorization',committedApplicationEvidence:artifact},applicationResultCheck,false,()=>{});
probe('forged installed marker needs native rejection',applicationRequest,applicationCheck,true,()=>{});
const ackCheck=ajv.compile(await Bun.file(root+'feed-acknowledgment-result-v0.2.schema.json').json());
const ack={outcome:'advanced',applied:{state:'transaction',boundary:txBoundary},durability:'pending'};
probe('pending source acknowledgment',ack,ackCheck,true,()=>{});
probe('hidden committed source flag',ack,ackCheck,false,v=>v.durability='committed');
probe('unavailable leaking checkpoint',{outcome:'unavailable',reason:'authorization',current:ack.applied},ackCheck,false,()=>{});
probe('old checkpoint boundary',ack,ackCheck,false,v=>v.applied.boundary.domain='complete-feed-transaction/0.1.0');
probe('authorized conflict shape',{outcome:'conflict',current:ack.applied},ackCheck,true,()=>{});
probe('invented acknowledged native progress needs semantic rejection',ack,ackCheck,true,()=>{});
const compositionCheck=ajv.compile(await Bun.file(root+'seed-profile-composition-v0.2.schema.json').json());
const composition={interfaceVersion:'truss-seed-profile-composition/0.2.0',compositionProfile:pin,baselineProfile:pin,inventoryProfile:pin,anchorProfile:pin,extractionProfile:pin,visibilityProfile:pin,stageProfile:pin,activationProfile:pin,confirmationProfile:pin,downstreamProfile:pin,originalQualificationEvidence:artifact};
probe('complete seed composition tuple',composition,compositionCheck,true,()=>{});
probe('missing activation pin',composition,compositionCheck,false,v=>delete v.activationProfile);
probe('missing original qualification',composition,compositionCheck,false,v=>delete v.originalQualificationEvidence);
probe('qualification boolean forbidden',composition,compositionCheck,false,v=>v.qualified=true);
probe('unsupported tuple needs semantic rejection',composition,compositionCheck,true,v=>v.stageProfile.identity='unsupported');
probe('forged qualification needs native rejection',composition,compositionCheck,true,v=>v.originalQualificationEvidence=artifact);
const collectionCheck=ajv.getSchema('urn:truss:draft:key-migration-bucket-collection:0.1.0')!;
const collection={interfaceVersion:'truss-key-migration-bucket-collection/0.1.0',originalAttempt:attempt,source:basis,collectorProfile:pin,entryIdentityProfile:pin,originalInstalledInventory:artifact,originalExclusion:artifact,originalCut:artifact,applicability:{originalCatalog:artifact,originalBindingInventory:artifact,completeObjectDomain:artifact,exactApplicabilityEvidence:artifact},entries:[{entryId:'entry:0000000000000000001',locator:{kind:'live_binding',identity,localKeyNumber:'0',originalBinding:artifact,originalDefinition:artifact,projection:{state:'held',storageRowId:'1',originalRow:artifact}},sourceEntry:artifact}],exhaustion:{live:artifact,reservations:artifact},completeScopeEvidence:artifact};
probe('collection held locator',collection,collectionCheck,true,()=>{});
probe('collection empty shape retains exhaustion',collection,collectionCheck,true,v=>v.entries=[]);
probe('collection omitted live locator',collection,collectionCheck,true,v=>v.entries[0].locator.projection={state:'omitted',originalMissingComponentReport:artifact});
probe('collection reservation locator',collection,collectionCheck,true,v=>v.entries[0].locator={kind:'reservation',storageRowId:'2',originalStoreDefinition:artifact,originalReservation:artifact});
probe('collection missing reservation exhaustion',collection,collectionCheck,false,v=>delete v.exhaustion.reservations);
probe('collection missing applicability domain',collection,collectionCheck,false,v=>delete v.applicability.completeObjectDomain);
probe('collection count instead of source entry',collection,collectionCheck,false,v=>{delete v.entries[0].sourceEntry;v.entries[0].count='1';});
probe('collection zero storage row rejects',collection,collectionCheck,false,v=>v.entries[0].locator.projection.storageRowId='0');
probe('collection mismatched cut requires semantic refusal',collection,collectionCheck,true,v=>v.originalCut=artifact);
probe('collection duplicate locator requires semantic refusal',collection,collectionCheck,true,v=>v.entries.push({...v.entries[0],entryId:'entry:0000000000000000002'}));
const migrationResultCheck=ajv.getSchema('urn:truss:draft:key-migration-result:0.1.0')!;
const pureRefusal={outcome:'refused',reason:'resource',containment:{phase:'pre_native'}};
const nativeRefusal={outcome:'refused',reason:'resource',containment:{phase:'preflight_terminated',originalAttempt:attempt,terminationEvidence:artifact}};
const rolledBack={outcome:'rolled_back',originalAttempt:attempt,failedStage:'target_staging',terminationEvidence:artifact};
const unknownCommit={outcome:'commit_unknown',originalAttempt:attempt,originalEvidence:artifact,recoveryReference:'original'};
const uncertainApplication={outcome:'recovery_required',reason:'application_unknown',failedStage:'target_staging',originalAttempt:attempt,originalEvidence:artifact,recoveryReference:'original'};
probe('migration pure refusal',pureRefusal,migrationResultCheck,true,()=>{});
probe('migration terminated native preflight',nativeRefusal,migrationResultCheck,true,()=>{});
probe('migration native refusal lacks termination',nativeRefusal,migrationResultCheck,false,v=>delete v.containment.terminationEvidence);
probe('migration rollback evidence',rolledBack,migrationResultCheck,true,()=>{});
probe('migration rollback lacks termination',rolledBack,migrationResultCheck,false,v=>delete v.terminationEvidence);
probe('migration unknown commit',unknownCommit,migrationResultCheck,true,()=>{});
probe('migration unknown commit cannot leak success',unknownCommit,migrationResultCheck,false,v=>v.commit={});
probe('migration application recovery',uncertainApplication,migrationResultCheck,true,()=>{});
probe('migration has no generic unavailable outcome',pureRefusal,migrationResultCheck,false,v=>v.outcome='unavailable');
const receipt={scope:'Migration/feed/seed/proof/application structural probes including deliberately shape-valid semantic/native counterexamples; no native qualification',cases,failures};await Bun.write('docs/helix/04-build/evidence/design-audit/key-migration-inventory.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));if(failures.length)process.exit(1);
