/** Publication metadata shape, never host atomicity or native graph evidence. */
const {default:Ajv}=await import(process.argv[2]);const a=new Ajv({strict:true});
for(const n of ['direct-cursor','direct-traversal-request','traversal-resource-ledger'])a.addSchema(await Bun.file(`docs/helix/02-design/contracts/${n}-v0.1.schema.json`).json());
const check=a.compile(await Bun.file('docs/helix/02-design/contracts/traversal-publication-evidence-v0.1.schema.json').json());
const pin={identity:'fixture',version:'0.1.0',sha256:'a'.repeat(64)};const ref={identity:'original',sha256:'b'.repeat(64)};
const context={catalogRevision:'2',layoutProfile:pin,readProfile:pin,authorizedScopeIdentity:'scope',consistency:{kind:'held_snapshot',snapshotIdentity:'snapshot'}};
const value={interfaceVersion:'truss-traversal-publication-evidence/0.1.0',assemblyId:'assembly',handle:{stageIdentity:'stage',generation:'0',querySha256:'b'.repeat(64),context},storeProfile:pin,publicationProfile:pin,originalQuery:ref,previousState:ref,resultingState:ref,resourceLedger:ref,previousWorkVersion:'1',resultingWorkVersion:'2',accountingVersion:'3',resultingPhase:'sealed',originalAttemptIdentity:'attempt',originalStoreObservation:ref};
const cases:[string,unknown,boolean][]=[['confirmed metadata',value,true],['missing ledger',Object.fromEntries(Object.entries(value).filter(([k])=>k!=='resourceLedger')),false],['no future cleanup',{...value,released:true},false],['no native commit assertion',{...value,committed:true},false],['no private result payload',{...value,records:[]},false],['numeric version rejects',{...value,resultingWorkVersion:2},false],['nonincrementing version semantic refusal',{...value,resultingWorkVersion:'1'},true],['wrong state reference semantic refusal',{...value,resultingState:{...ref,identity:'substitute'}},true],['forged actual-store observation issuer refusal',{...value,originalStoreObservation:{...ref,identity:'forged'}},true]];
const failures=cases.filter(([,v,e])=>Boolean(check(v))!==e).map(([n])=>n);console.log(JSON.stringify({scope:'publication metadata shape, not original custody/atomic effect',cases:cases.length,failures},null,2));if(failures.length)process.exit(1);export {};
