/** Cleanup metadata shape only; actual resource custody/deletion unqualified. */
const {default:Ajv}=await import(process.argv[2]);const a=new Ajv({strict:true});
for(const n of ['direct-cursor','direct-traversal-request','traversal-resource-ledger'])a.addSchema(await Bun.file(`docs/helix/02-design/contracts/${n}-v0.1.schema.json`).json());
const check=a.compile(await Bun.file('docs/helix/02-design/contracts/traversal-cleanup-evidence-v0.1.schema.json').json());
const pin={identity:'fixture',version:'0.1.0',sha256:'a'.repeat(64)};const ref={identity:'original',sha256:'b'.repeat(64)};
const context={catalogRevision:'2',layoutProfile:pin,readProfile:pin,authorizedScopeIdentity:'scope',consistency:{kind:'held_snapshot',snapshotIdentity:'snapshot'}};
const v={interfaceVersion:'truss-traversal-cleanup-evidence/0.1.0',assemblyId:'assembly',handle:{stageIdentity:'stage',generation:'0',querySha256:'b'.repeat(64),context},storeProfile:pin,cleanupProfile:pin,originalReleaseAttemptIdentity:'attempt',originalInvalidation:ref,originalQuiescence:ref,originalResourceInventory:ref,originalDeletion:ref,resultingLedger:ref,completionTombstoneIdentity:'completion',remainingMetadataChargeBytes:'512',termination:'confirmed',stageOwnedResources:'released'};
const cases:[string,unknown,boolean][]=[['complete cleanup metadata',v,true],['unknown termination rejects',{...v,termination:'unknown'},false],['missing deletion rejects',Object.fromEntries(Object.entries(v).filter(([k])=>k!=='originalDeletion')),false],['no purged state payload',{...v,privateState:{}},false],['no implicit host rollback',{...v,hostRolledBack:true},false],['host numeric charge rejects',{...v,remainingMetadataChargeBytes:512},false],['incomplete inventory needs custody refusal',{...v,originalResourceInventory:{...ref,identity:'partial'}},true],['forged quiescence needs native refusal',{...v,originalQuiescence:{...ref,identity:'forged'}},true],['unbacked metadata refund needs accounting refusal',{...v,remainingMetadataChargeBytes:'0'},true]];
const failures=cases.filter(([,v,e])=>Boolean(check(v))!==e).map(([n])=>n);console.log(JSON.stringify({scope:'cleanup metadata shapes; actual custody/deletion unqualified',cases:cases.length,failures},null,2));if(failures.length)process.exit(1);export {};
