"""Source-only column dictionary; no native catalog or installation claims."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[5]
SOURCES=[('baseline','docs/helix/02-design/models/truss-layout-0.2.umf.json'),('row-candidate','docs/helix/02-design/contracts/row-home-tree-v0.1.proposal.umf.json'),('row-candidate','docs/helix/02-design/contracts/row-home-scalar-v0.1.proposal.umf.json')]
def decode(n):
    if n['kind']=='object':return {k:decode(v) for k,v in n['members'].items()}
    if n['kind']=='array':return [decode(v) for v in n['items']]
    return n.get('value')
def text(n):
    return n.get('String',{}).get('sval','?')
tables=[];effects=[];pins=[]
for surface,path in SOURCES:
    b=(ROOT/path).read_bytes();d=json.loads(b)
    pins.append({'path':path,'sha256':hashlib.sha256(b).hexdigest(),'surface':surface})
    stmts=decode(d['modules'][0]['elements'][0]['extensions']['umf.postgresql']['root'])['stmts']
    for ordinal,s in enumerate(stmts):
        node=s['stmt'];c=node.get('CreateStmt')
        if not c:
            effects.append({'surface':surface,'source':path,'ordinal':ordinal,'statement':node});continue
        table={'surface':surface,'source':path,'statementOrdinal':ordinal,'relation':c['relation'],'columns':[],'tableConstraints':[],'completeCreateStatement':c}
        for elt in c['tableElts']:
            col=elt.get('ColumnDef')
            if not col:
                table['tableConstraints'].append(elt);continue
            cons=[x['Constraint'] for x in col.get('constraints',[]) if 'Constraint' in x]
            table['columns'].append({'name':col['colname'],'ordinal':len(table['columns'])+1,'declaredType':col['typeName'],'explicitNotNull':any(x['contype']=='CONSTR_NOTNULL' for x in cons),'inlinePrimaryKey':any(x['contype']=='CONSTR_PRIMARY' for x in cons),'defaults':[x['raw_expr'] for x in cons if x['contype']=='CONSTR_DEFAULT'],'completeColumnDefinition':col})
        pk={text(k) for x in table['tableConstraints'] for k in x.get('Constraint',{}).get('keys',[]) if x.get('Constraint',{}).get('contype')=='CONSTR_PRIMARY'}
        for col in table['columns']:col['notNullFromDeclaredPrimaryKey']=col['inlinePrimaryKey'] or col['name'] in pk
        tables.append(table)
if len(tables)!=22 or len({(t['surface'],t['relation']['relname']) for t in tables})!=22:raise ValueError('selected table inventory')
result={'interfaceVersion':'truss-weft-layout-dictionary/0.1.0','scope':'All CREATE TABLE columns and original native definitions in three selected UMF source models; other statements retained separately; excludes proposal compositions and native resolution','nativeQualified':False,'sources':pins,'tables':tables,'otherStatements':effects}
base=ROOT/'docs/helix/02-design/contracts'
(base/'weft-layout-dictionary-v0.1.proposal.json').write_text(json.dumps(result,indent=2)+'\n')
lines=['# Physical columns for the Weft source handoff','','Generated by `collect-weft-layout-dictionary.py` from three pinned UMF models.','Companion to [CONTRACT-012](CONTRACT-012-weft-storage-handoff.md).','Source-only: baseline and additive row candidate remain distinct.','The [machine dictionary](weft-layout-dictionary-v0.1.proposal.json) preserves complete column/table definitions and every other statement.','','Nullability below includes authored PRIMARY KEY effects, not resolved native inventory.','Defaults, full constraints, type modifiers, collations, ALTER effects and indexes remain in the machine dictionary and exact SQL linked by CONTRACT-012.','']
for t in tables:
    name=t['relation']['relname'];lines.extend([f'## {name} ({t["surface"]})','','| Ordinal | Column | Declared native type | SQL NULL allowed by source | Default declared |','| --- | --- | --- | --- | --- |'])
    for c in t['columns']:
        typ='.'.join(text(x) for x in c['declaredType']['names'])
        if c['declaredType'].get('arrayBounds'):typ+='[]'
        if c['declaredType'].get('typmods'):typ+=' (modifiers retained in dictionary)'
        null='no' if c['explicitNotNull'] or c['notNullFromDeclaredPrimaryKey'] else 'yes'
        lines.append(f'| {c["ordinal"]} | `{c["name"]}` | `{typ}` | {null} | {"yes" if c["defaults"] else "no"} |')
    lines.append('')
(base/'weft-layout-columns-v0.1.proposal.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'tables':len(tables),'columns':sum(len(t['columns']) for t in tables),'markdownLines':len(lines),'nativeQualified':False}))
