import {test,expect} from 'bun:test';
import {collectCatalogReportDocumentBasis} from '../packages/umf-bun/src/catalog-report-document-basis';
// Deliberately synthetic negative/bijection unit fixture; native custody is tested separately.
function basis(){const declaration={documentId:'doc',documentRevision:'r1',artifact:{sha256:'a'.repeat(64)}};return {original:{input:{documents:[declaration]},documents:[{sha256:declaration.artifact.sha256}]},documents:[{documentId:'doc',interpretation:{sourceValidation:{valid:true,complete:false},transition:{original:'retained'}}}],umfProfile:{identity:'test',version:'1',sha256:'b'.repeat(64)}} as any}
function rows(){return [{doc_id:'doc',doc_revision:'r1',content_sha256:'a'.repeat(64),ord:'0',writer_xid:'42',operation_ordinal:'0',effect_generation:'11'}]}
test('document basis preserves partial original observation without making complete report',async()=>{const result=await collectCatalogReportDocumentBasis({unsafe:async()=>rows()},basis(),'1');expect(result.documents).toEqual(rows().map(({writer_xid,operation_ordinal,effect_generation,...document})=>document));expect(result.nativeObservation).toEqual({writerXid:'42',operationOrdinal:'0',effectGeneration:'11'});expect(JSON.parse(Buffer.from(result.observations[0].evidence.bytesBase64,'base64').toString()).observation.sourceValidation.complete).toBe(false);expect(result.scope).toBe('original_report_document_basis_only');expect(result.observations[0]).not.toHaveProperty('completeness')});
test('omitted and extra native archive observations refuse',async()=>{for(const native of [[],[...rows(),...rows()]])await expect(collectCatalogReportDocumentBasis({unsafe:async()=>native},basis(),'1')).rejects.toThrow('bijection')});
test('native identity revision digest and ordinal substitutions refuse',async()=>{for(const [field,value] of [['doc_id','other'],['doc_revision','r2'],['content_sha256','c'.repeat(64)],['ord','00']]){const native=rows();(native[0] as any)[field]=value;await expect(collectCatalogReportDocumentBasis({unsafe:async()=>native},basis(),'1')).rejects.toThrow('correspondence')}});

test('missing or noncanonical native generation cannot be guessed',async()=>{for(const value of [undefined,'00','-1','9223372036854775808']){const native=rows();(native[0] as any).effect_generation=value;await expect(collectCatalogReportDocumentBasis({unsafe:async()=>native},basis(),'1')).rejects.toThrow('observation tuple')}});
