import {test,expect} from 'bun:test';
import {createCatalogInputPreparation} from '../packages/umf-bun/src/catalog-input';
const directory=process.env.TRUSS_UMF_PRODUCER;if(!directory)throw Error('Original Record producer directory required');
const preparation=await createCatalogInputPreparation(directory,'/Users/erik/Projects/umf/package.json');
const fixture=await Bun.file('docs/helix/02-design/contracts/bindings/acceptance-input-capacity-v0.1.fixture.json').json();
function request(){const input=structuredClone(fixture.input);input.binding={state:'absent'};input.transforms=[];
 input.documents=['first-doc','second-doc'].map(documentId=>{const original=' \n'+JSON.stringify({umf:'0.7.0',id:documentId,vocabularies:{},extensions:{},modules:[{id:'m',namespace:'m',elements:[{id:'Item',kind:'record',members:[{module:'m',element:'label'}],extensions:{}},{id:'label',kind:'field',scalarType:'string',nullability:'required',cardinality:'one',extensions:{}}]}]})+'\n';const bytes=Buffer.from(original);return {documentId,documentRevision:'original-r1',artifact:{identity:documentId,bytesBase64:bytes.toString('base64'),sha256:new Bun.CryptoHasher('sha256').update(bytes).digest('hex')},umfProfile:preparation.umfProfile,ingress:{kind:'native'}}});return input}
const run=(input:unknown)=>preparation.prepare(new TextEncoder().encode(JSON.stringify(input)));
test('real owner validates original ordered UMF sources with reversible interpretation',()=>{const input=request();const result=run(input);expect(result.documents.map(d=>d.documentId)).toEqual(['first-doc','second-doc']);for(let i=0;i<2;i++){const doc=result.documents[i]!;expect(doc.originalText).toBe(Buffer.from(input.documents[i].artifact.bytesBase64,'base64').toString());expect(doc.umfVersion).toBe('0.7.0');expect(doc.interpretation.target.umf).toBe('0.8.0');expect(doc.validation.sourceValidation.valid).toBe(true);expect(doc.validation.transition).not.toBeNull()}expect(result.scope).toBe('original_umf_preparation_only')});
test('foreign original interpretation profile cannot borrow validation',()=>{const input=request();input.documents[0].umfProfile={...preparation.umfProfile,sha256:'0'.repeat(64)};expect(()=>run(input)).toThrow('Unsupported original UMF profile')});
test('archive document identity must equal original owner source',()=>{const input=request();input.documents[0].documentId='other';expect(()=>run(input)).toThrow('Original document identity mismatch')});
test('shape-only original {} source does not become accepted UMF',()=>{const input=request();const bytes=Buffer.from('{}');input.documents[0].artifact={identity:'invalid',bytesBase64:bytes.toString('base64'),sha256:new Bun.CryptoHasher('sha256').update(bytes).digest('hex')};expect(()=>run(input)).toThrow()});

test('native archive carrier has exact five original fields without interpretation substitution',()=>{const result=run(request());expect(Object.keys(result.archiveDocuments[0]).sort()).toEqual(['documentId','originalText','revision','umfVersion','validation']);expect(Object.isFrozen(result.archiveDocuments[0].validation)).toBe(true)});

test('source declaration extraction preserves original owner and Field references',()=>{const result=run(request());expect(result.declarations.map(d=>d.records[0].documentId)).toEqual(['first-doc','second-doc']);const record=result.declarations[0].records[0];expect([record.moduleId,record.elementId]).toEqual(['m','Item']);expect(record.fields[0].declaration).toBe(result.documents[0].interpretation.source.modules[0].elements[1]);expect(record.fields[0].reference).toEqual({module:'m',element:'label'});expect(Object.isFrozen(record.fields[0].declaration)).toBe(true)});
