import {test,expect} from 'bun:test';
import {loadUmfProducer,loadUmfDeclarationProducer} from '../packages/umf-bun/src/index';
import {createCatalogInputPreparation} from '../packages/umf-bun/src/catalog-input';
import {collectCatalogAssertionObservations} from '../packages/umf-bun/src/catalog-assertion-observations';
const recordDirectory=process.env.TRUSS_UMF_PRODUCER;const metadataDirectory=process.env.TRUSS_UMF_DECLARATION_PRODUCER;
if(!recordDirectory||!metadataDirectory)throw Error('Both original pinned owner producer directories required');
const record=await loadUmfProducer(recordDirectory);const metadata=await loadUmfDeclarationProducer(metadataDirectory);
const original=JSON.stringify({umf:'0.7.0',id:'source',vocabularies:{},extensions:{},modules:[{id:'m',namespace:'m',elements:[{id:'R',kind:'record',members:[{module:'m',element:'label'}],keys:[{id:'K',name:'key',fields:[{module:'m',element:'label'}],primary:true}],extensions:{}},{id:'label',name:'label',kind:'field',scalarType:'string',nullability:'required',cardinality:'one',extensions:{}}],relationships:[{id:'self',name:'self',source:[{module:'m',element:'R'}],target:[{module:'m',element:'R',key:'K'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:0,max:1},targetLifecycle:'independent',directed:true}]}]});
const inspected=record.inspect(original);
test('original authored keys are inspected through owner API with source pointer and unverified provenance',()=>{const observation=metadata.inspectKeys(inspected.source,{module:'m',element:'R'});expect(observation.meaning.state).toBe('known');expect(observation.meaning.keys[0].id).toBe('K');expect(observation.path).toBe('/modules/0/elements/0/keys');expect(observation.provenance).toBe('unverified')});
test('relationship meaning is version scoped and cannot borrow upgraded envelope semantics',()=>{const original=metadata.inspectRelationships(inspected.source,{module:'m'});expect(original.meaning.state).toBe('known');expect(original.meaning.relationships[0].id).toBe('self');expect(()=>metadata.inspectRelationships(inspected.target,{module:'m'})).toThrow()});
test('schema properties use explicit reversible target and preserve complete owner diagnostic observations',()=>{const before=JSON.stringify(inspected.target);const observation=metadata.inspectSchemaProperties(inspected.target,{scope:'element',module:'m',element:'label'});expect(observation.path).toBe('/modules/0/elements/1');expect(observation.source.umf).toBe('0.8.0');expect(observation.diagnostics).toEqual(inspected.targetValidation!.diagnostics);expect(observation.provenance).toBe('unverified');expect(JSON.stringify(inspected.target)).toBe(before)});

async function prepared(umf:'0.7.0'|'0.8.0'){const preparation=await createCatalogInputPreparation(recordDirectory!,'/Users/erik/Projects/umf/package.json');const input=structuredClone((await Bun.file('docs/helix/02-design/contracts/bindings/acceptance-input-capacity-v0.1.fixture.json').json()).input);const bytes=Buffer.from(umf==='0.7.0'?original:JSON.stringify(inspected.target));input.binding={state:'absent'};input.transforms=[];input.documents=[{documentId:'source',documentRevision:'r1',artifact:{identity:'source',bytesBase64:bytes.toString('base64'),sha256:new Bun.CryptoHasher('sha256').update(bytes).digest('hex')},umfProfile:preparation.umfProfile,ingress:{kind:'native'}}];return preparation.prepare(new TextEncoder().encode(JSON.stringify(input)))}
test('prepared original sources collect owner observations with independent version basis and exact evidence',async()=>{const result=collectCatalogAssertionObservations(await prepared('0.7.0'),metadata);expect(result.observations.length).toBe(6);const relationship=result.observations.find(o=>o.operation==='relationships')!;expect((relationship.result as any).observation.meaning.state).toBe('known');expect(relationship.basis).toBe('original');const decoded=JSON.parse(Buffer.from(relationship.evidence.bytesBase64,'base64').toString());expect(decoded.operation).toBe('relationships');expect(decoded.result).toEqual(relationship.result);expect(Object.isFrozen(relationship.result)).toBe(true)});
test('unavailable original 0.8 relationship inspection remains explicit and preserves owner failure',async()=>{const result=collectCatalogAssertionObservations(await prepared('0.8.0'),metadata);const relationship=result.observations.find(o=>o.operation==='relationships')!;expect((relationship.result as any).state).toBe('unavailable');expect((relationship.result as any).code).toBe('RELATIONSHIP_RESULT');expect((relationship.result as any).path).toBe('');expect(result.observations.find(o=>o.operation==='schema_properties')!.basis).toBe('original');expect(result.scope).toBe('original_owner_assertion_observations_only')});
