/** Review-only fixed epoch storage, generated by the UMF PostgreSQL owner. */
import {backend} from '/Users/erik/Projects/umf/native/postgresql/runtime';
import {readDocument} from '/Users/erik/Projects/umf/src/model/document';
import {importPostgresqlSql,exportPostgresqlSql} from '/Users/erik/Projects/umf/src/adapters/postgresql';
const source=`
-- Candidate only: no issuer, transition authority or installed admission.
CREATE TABLE truss.source_epoch_registry (
 installation_id text COLLATE pg_catalog."C" NOT NULL,
 source_epoch text COLLATE pg_catalog."C" NOT NULL,
 target_incarnation text COLLATE pg_catalog."C" NOT NULL,
 predecessor_epoch text COLLATE pg_catalog."C",
 transition_reason text COLLATE pg_catalog."C" NOT NULL,
 profile_bytes bytea NOT NULL,
 evidence_bytes bytea NOT NULL,
 evidence_sha256 bytea GENERATED ALWAYS AS (pg_catalog.sha256(evidence_bytes)) STORED,
 PRIMARY KEY (installation_id, source_epoch),
 UNIQUE (source_epoch),
 FOREIGN KEY (installation_id) REFERENCES truss.installation_marker (installation_id),
 FOREIGN KEY (installation_id, predecessor_epoch)
   REFERENCES truss.source_epoch_registry (installation_id, source_epoch),
 CHECK (octet_length(source_epoch) BETWEEN 1 AND 256),
 CHECK (octet_length(target_incarnation) BETWEEN 1 AND 1024),
 CHECK (octet_length(profile_bytes) BETWEEN 1 AND 65536),
 CHECK (octet_length(evidence_bytes) BETWEEN 1 AND 1048576),
 CHECK (transition_reason IN ('initial','restore')),
 CHECK ((transition_reason = 'initial' AND predecessor_epoch IS NULL)
   OR (transition_reason = 'restore' AND predecessor_epoch IS NOT NULL)),
 CHECK (predecessor_epoch IS NULL OR predecessor_epoch <> source_epoch)
);
CREATE TABLE truss.source_epoch_current (
 singleton_id smallint PRIMARY KEY CHECK (singleton_id = 1),
 installation_id text COLLATE pg_catalog."C" NOT NULL,
 source_epoch text COLLATE pg_catalog."C" NOT NULL,
 FOREIGN KEY (installation_id, source_epoch)
   REFERENCES truss.source_epoch_registry (installation_id, source_epoch)
);
REVOKE ALL ON truss.source_epoch_registry, truss.source_epoch_current FROM PUBLIC;
`;
const model=await importPostgresqlSql(source,backend,{id:'truss-source-epoch-storage-candidate'});
const serialized=JSON.stringify(model)+'\n';const ddl=await exportPostgresqlSql(model,backend);
if(await exportPostgresqlSql(readDocument(serialized,'json'),backend)!==ddl)throw Error('Reload/export mismatch');
const modelPath='docs/helix/02-design/contracts/source-epoch-storage-v0.1.proposal.umf.json';
const ddlPath='docs/helix/04-build/evidence/source-epoch-storage.owner-export.sql';
await Bun.write(modelPath,serialized);await Bun.write(ddlPath,ddl);
const hash=(s:string)=>new Bun.CryptoHasher('sha256').update(s).digest('hex');
const owner=Bun.spawnSync(['git','-C','/Users/erik/Projects/umf','rev-parse','HEAD']);if(owner.exitCode)throw Error('Owner revision unavailable');
await Bun.write('docs/helix/04-build/evidence/design-audit/source-epoch-storage.json',JSON.stringify({scope:'Owner SQL import, UMF retention and exact saved reload/export only; no native install, epoch issuance or authority qualification',ownerCommit:new TextDecoder().decode(owner.stdout).trim(),modelPath,modelSha256:hash(serialized),ddlPath,ddlSha256:hash(ddl),reloadedExportExact:true,qualified:false},null,2)+'\n');
console.log('Epoch candidate UMF and owner DDL saved; reload/export exact.');
