/** Build an isolated owner producer from committed source, never sibling working edits. */
import {mkdtemp,writeFile,readFile,symlink} from 'node:fs/promises';
const repository=process.argv[2];if(!repository)throw Error('UMF Git repository required');
const mode=process.argv[3]??'record';if(!['record','numeric','numeric-current','values','declarations','assertion-fields','assertions-current'].includes(mode))throw Error('Original producer mode must be record, numeric, numeric-current, values, declarations, assertion-fields or assertions-current');
const revision=mode==='assertions-current'?'a917e1b41361d67031851fd7f5baca77934faf08':mode==='numeric-current'?'e3555b9aac9e4c3caa952203958c4b0c33cdf519':(mode==='record'||mode==='declarations'||mode==='assertion-fields')?'c45c72a2a8a3c4fba61c40c5927dd9091acf8cc3':'9e4bed3efe922c11e4b5a888ba6854de14f1b29f';
const operations=mode==='assertions-current'?['readDocument','inspectCoreSchemaProperties','inspectCoreKeys','inspectCoreRelationships','inspectCoreElementKind','inspectCoreNullability','inspectCoreCardinality','inspectCoreFacets']:mode==='assertion-fields'?['inspectCoreElementKind','inspectCoreNullability','inspectCoreCardinality','inspectCoreFacets']:mode==='declarations'?['inspectCoreSchemaProperties','inspectCoreKeys','inspectCoreRelationships']:mode==='record'?['readDocument','validateDocument','validateCoreRecordValues','upgradeSchemaPropertiesEnvelope','verifySchemaPropertiesUpgrade','rollbackSchemaPropertiesEnvelope']:mode==='values'?['validateCoreFieldValue','encodeCoreKeyTuple','verifyCoreKeyTuple']:['exactDecimal','integerFromBigInt','integerToBigInt','admitJavascriptNumber','numericToNumberLossless'];
const output=await mkdtemp('/private/tmp/truss-umf-runtime-');
const archive=Bun.spawnSync(['git','archive',revision],{cwd:repository});if(archive.exitCode)throw Error('Pinned source archive unavailable');
await writeFile(output+'/source.tar',archive.stdout);
await symlink(repository+'/node_modules',output+'/node_modules');
const extract=Bun.spawnSync(['tar','-xf',output+'/source.tar','-C',output]);if(extract.exitCode)throw Error('Source extraction failed');
await writeFile(output+'/producer.ts',mode==='assertions-current'?`export {readDocument} from './src/model/document';\nexport {inspectCoreSchemaProperties} from './src/model/schema-properties';\nexport {inspectCoreKeys} from './src/model/keys';\nexport {inspectCoreRelationships} from './src/model/relationships';\nexport {inspectCoreElementKind} from './src/model/field-kind';\nexport {inspectCoreNullability} from './src/model/nullability';\nexport {inspectCoreCardinality} from './src/model/cardinality';\nexport {inspectCoreFacets} from './src/model/facets';\n`:mode==='assertion-fields'?`export {inspectCoreElementKind} from './src/model/field-kind';\nexport {inspectCoreNullability} from './src/model/nullability';\nexport {inspectCoreCardinality} from './src/model/cardinality';\nexport {inspectCoreFacets} from './src/model/facets';\n`:mode==='declarations'?`export {inspectCoreSchemaProperties} from './src/model/schema-properties';\nexport {inspectCoreKeys} from './src/model/keys';\nexport {inspectCoreRelationships} from './src/model/relationships';\n`:mode==='values'?`export {validateCoreFieldValue} from './src/model/schema-properties';\nexport {encodeCoreKeyTuple,verifyCoreKeyTuple} from './src/model/key-tuple';\n`:(mode==='numeric'||mode==='numeric-current')?`export {${operations.join(',')}} from './src/adapters/javascript-numeric';\n`:`export {readDocument} from './src/model/document';\nexport {validateDocument} from './src/validation/document';\nexport {validateCoreRecordValues} from './src/model/record-values';\nexport {upgradeSchemaPropertiesEnvelope,verifySchemaPropertiesUpgrade,rollbackSchemaPropertiesEnvelope} from './src/model/schema-properties-transition';\n`);
const build=await Bun.build({entrypoints:[output+'/producer.ts'],outdir:output,target:'browser',format:'esm',naming:'producer.js'});if(!build.success)throw Error('Owner producer build failed');
const buildDependencies=Object.fromEntries(await Promise.all(['yaml','ajv'].map(async name=>{const bytes=await readFile(repository+'/node_modules/'+name+'/package.json');return [name,{version:JSON.parse(bytes.toString()).version,packageSha256:new Bun.CryptoHasher('sha256').update(bytes).digest('hex')}] as const})));
const hash=(b:Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex');
await writeFile(output+'/producer-manifest.json',JSON.stringify({revision,producerMode:mode,buildDependencies,archiveSha256:hash(archive.stdout),bundleSha256:hash(await readFile(output+'/producer.js')),operations,scope:'Original logical UMF producers only; no native acceptance/containment qualification.'},null,2)+'\n');
console.log(output);
