/** Owner checkpoint only; current probe bundles are never runtime registrations. */
import {loadUmfProducer} from '../packages/umf-bun/src/index';
import {preflightSourceJson} from '../packages/postgresql/src/acceptance-json';
const originalDirectory=process.env.TRUSS_UMF_PRODUCER,probeDirectory=process.env.TRUSS_UMF_CURRENT_ASSERTION_PROBE;
if(!originalDirectory||!probeDirectory)throw Error('Original Record and current assertion probe directories required');
const manifest=await Bun.file(probeDirectory+'/producer-manifest.json').json();const bundle=await Bun.file(probeDirectory+'/producer.js').arrayBuffer();
const hash=(bytes:Uint8Array|ArrayBuffer)=>new Bun.CryptoHasher('sha256').update(bytes).digest('hex');
if(manifest.revision!=='a917e1b41361d67031851fd7f5baca77934faf08'||manifest.producerMode!=='assertions-current'||manifest.bundleSha256!==hash(bundle))throw Error('Current assertion probe pin mismatch');
const current=await import(probeDirectory+'/producer.js'),original=await loadUmfProducer(originalDirectory);
const text=JSON.stringify({umf:'0.7.0',id:'owner-probe',vocabularies:{},extensions:{},modules:[{id:'m',namespace:'m',elements:[{id:'R',kind:'record',members:[{module:'m',element:'value'}],keys:[{id:'K',name:'key',fields:[{module:'m',element:'value'}],primary:true}],extensions:{}},{id:'value',kind:'field',scalarType:'string',nullability:'required',cardinality:'one',facets:{length:{max:10,unit:'unicode-scalar'},future:{value:'opaque'}},extensions:{}}],relationships:[{id:'self',name:'self',source:[{module:'m',element:'R'}],target:[{module:'m',element:'R',key:'K'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:0,max:1},targetLifecycle:'independent',directed:true}]}]});
const prior=original.inspect(text),observations=[];
const calls=[['inspectCoreSchemaProperties',{scope:'element',module:'m',element:'value'}],['inspectCoreKeys',{module:'m',element:'R'}],['inspectCoreRelationships',{module:'m'}],...['inspectCoreElementKind','inspectCoreNullability','inspectCoreCardinality','inspectCoreFacets'].map(name=>[name,{module:'m',element:'value'}])] as const;
for(const [basis,sourceText] of [['original_07',text],['reversible_08_probe',JSON.stringify(prior.target)]] as const){
 preflightSourceJson(new TextEncoder().encode(sourceText));const source=current.readDocument(sourceText,'json');
 for(const [operation,identity] of calls){let result;try{result={state:'observed',observation:current[operation as string](source,identity)}}catch(error){result={state:'unavailable',code:(error as any).code??null,path:(error as any).path??null,message:(error as Error).message}}
  const bytes=new TextEncoder().encode(JSON.stringify({basis,sourceSha256:hash(new TextEncoder().encode(sourceText)),operation,identity,result}));observations.push({basis,operation,state:result.state,meaningState:(result as any).observation?.meaning?.state??null,code:(result as any).code??null,evidence:{bytesBase64:Buffer.from(bytes).toString('base64'),sha256:hash(bytes)}});
 }
}
const changed=(repository:string,args:string[])=>{const result=Bun.spawnSync(['git',...args],{cwd:repository});if(result.exitCode)throw Error('Owner source comparison unavailable');return result.stdout.toString().trim().split('\n').filter(Boolean)};
const receipt={probeSourceSha256:hash(await Bun.file(new URL(import.meta.url)).arrayBuffer()),currentUmfSemanticChangePathsSince30e:changed('/Users/erik/Projects/umf',['diff','--name-only','30e489aab5762dcbf36363e48f8fa36b5712b779',manifest.revision,'--','src/model','src/validation','spec/core']),currentWeftCompilerChangePathsSince5856:changed('/Users/erik/Projects/weft',['diff','--name-only','5856c73db0342363e64802905a94abb96209d757','origin/main','--','crates','spec','Cargo.toml','Cargo.lock']),currentUmfRevision:manifest.revision,currentWeftRevision:'5856c73db0342363e64802905a94abb96209d757',producerManifest:manifest,originalRecordProfile:{revision:original.sourceRevision,bundleSha256:original.bundleSha256},observations,scope:'Actual current owner inspection checkpoint only. No runtime pin adoption, registered profile, complete assertion inventory, native enforcement or accepted report.'};
await Bun.write('docs/helix/04-build/evidence/umf-current-assertion-inspection.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(observations.map(({basis,operation,state,meaningState,code})=>({basis,operation,state,meaningState,code}))));
