/** Actual full declared new-cohort staging. No acceptance/finalizer qualification. */
import {SQL} from 'bun';
import {loadUmfDeclarationProducer,loadUmfFieldAssertionProducer} from '../packages/umf-bun/src/index';
import {collectCatalogReportPreparation} from '../packages/umf-bun/src/catalog-report-preparation';
import {createCatalogInputPreparation} from '../packages/umf-bun/src/catalog-input';
import {stageNewCatalogCohort} from '../packages/umf-bun/src/catalog-new-stage';
import {prepareDefaultCatalogHomes} from '../packages/umf-bun/src/catalog-default-homes';
import {collectCatalogReportDocumentBasis,recheckCatalogReportDocumentBasis} from '../packages/umf-bun/src/catalog-report-document-basis';
const directory=process.env.TRUSS_UMF_PRODUCER;if(!directory)throw Error('Original owner directory required');
const declarationDirectory=process.env.TRUSS_UMF_DECLARATION_PRODUCER,fieldDirectory=process.env.TRUSS_UMF_FIELD_ASSERTION_PRODUCER;if(!declarationDirectory||!fieldDirectory)throw Error('Both original assertion producer directories required');
const owner=await loadUmfDeclarationProducer(declarationDirectory),fieldOwner=await loadUmfFieldAssertionProducer(fieldDirectory);
const url=process.env.TRUSS_OPERATION_TEST_URL;if(!url?.startsWith('postgres://postgres@127.0.0.1:15434/'))throw Error('Dedicated disposable endpoint required');
const preparation=await createCatalogInputPreparation(directory,'/Users/erik/Projects/umf/package.json');
const sql=new SQL(url,{max:1});const connection={unsafe:async(query:string,parameters:unknown[]=[])=>await sql.unsafe(query,parameters as any[])};
const checks:string[]=[];function assert(value:boolean,label:string){if(!value)throw Error(label);checks.push(label)}
const components=['operation-admission','operation-commit-barrier','catalog-generation-observer','catalog-document-batch','catalog-lineage-producer','catalog-source-integrity','catalog-type-match','catalog-type-stage','catalog-property-match','catalog-property-stage','catalog-key-match','catalog-key-stage','catalog-key-batch','catalog-relationship-match','catalog-relationship-stage','catalog-report-documents','catalog-new-inventory','catalog-observation-recheck','catalog-input-custody','catalog-prestate-capture','catalog-new-prestate-parity','catalog-new-counts','catalog-provisional-empty'];
function request(missingName=false){const input=structuredClone(fixture.input);input.binding={state:'absent'};input.transforms=[];const model={umf:'0.7.0',id:'cohort',vocabularies:{},extensions:{},modules:[{id:'m',namespace:'m',elements:[...['A','B'].map(id=>({id,kind:'record',members:[{module:'m',element:id+'-label'}],keys:[{id:'label-key',name:'label-key',fields:[{module:'m',element:id+'-label'}],primary:true}],extensions:{}})),...['A','B'].map(id=>({id:id+'-label',...(!missingName?{name:id+'-label'}:{}),kind:'field',scalarType:'string',nullability:'required',cardinality:'one',extensions:{}}))],relationships:[{id:'A-B',name:'A-B',source:[{module:'m',element:'A'}],target:[{module:'m',element:'B',key:'label-key'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:0,max:2},targetLifecycle:'independent',directed:true}]}]};const bytes=Buffer.from(' \n'+JSON.stringify(model)+'\n');input.documents=[{documentId:'cohort',documentRevision:'r1',artifact:{identity:'original-cohort',bytesBase64:bytes.toString('base64'),sha256:new Bun.CryptoHasher('sha256').update(bytes).digest('hex')},umfProfile:preparation.umfProfile,ingress:{kind:'native'}}];return preparation.prepare(new TextEncoder().encode(JSON.stringify(input)))}
const fixture=await Bun.file('docs/helix/02-design/contracts/bindings/acceptance-input-capacity-v0.1.fixture.json').json();
const homes=['A','B'].map(elementId=>({documentId:'cohort',moduleId:'m',elementId,fieldModule:'m',fieldId:elementId+'-label',home:'json' as const}));
try{
 const version=await sql.unsafe('SHOW server_version');assert(version[0].server_version.startsWith('17.9'),'actual PostgreSQL17.9');
 await sql.unsafe(await Bun.file('docs/helix/04-build/evidence/qualified-property-layout-0.15.owner-export.sql').text());
 for(const component of components)await sql.unsafe(await Bun.file('packages/postgresql/native/'+component+'.sql').text());
 const installedObservers=await sql.unsafe("SELECT count(*)::text AS n FROM pg_trigger WHERE tgname='runtime_catalog_generation' AND tgenabled='A' AND NOT tgisinternal");assert(installedObservers[0].n==='11','eleven ALWAYS catalog generation observers installed');
 const prepared=request();
 await sql.unsafe('BEGIN');await sql.unsafe('SAVEPOINT earlier_shared_head');await sql.unsafe('SELECT rev FROM truss.schema_head FOR SHARE');let earlierShared=false;try{await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate()')}catch(e){earlierShared=((e as any).errno??(e as any).code)==='55000'}assert(earlierShared,'catalog prestate refuses upgrade of earlier shared head admission');await sql.unsafe('ROLLBACK TO SAVEPOINT earlier_shared_head');const capture=await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate() AS bytes');const originalPrestate=JSON.parse(Buffer.from(capture[0].bytes,'hex').toString());assert(originalPrestate.head.rev===0&&originalPrestate.types.length===0&&originalPrestate.properties.length===0&&originalPrestate.keys.length===0&&originalPrestate.relationships.length===0&&originalPrestate.endpoints.length===0,'actual original empty catalog start cut captured under head exclusion');
 await sql.unsafe("SELECT * FROM truss.runtime_admit_operation('catalog-acceptance',decode('01','hex'),decode($1::text,'hex'),decode($2::text,'hex'),decode('04','hex'),decode('05','hex'),decode('06','hex'))",[prepared.original.originalUtf8Hex,capture[0].bytes]);
 const retainedPrestate=await sql.unsafe("SELECT encode(original_prestate_bytes,'hex') AS bytes FROM truss.row_home_operation");assert(retainedPrestate[0].bytes===capture[0].bytes,'original native prestate bytes retained unchanged in operation custody');
 await sql.unsafe('SAVEPOINT late_prestate');let latePrestate=false;try{await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate()')}catch(e){latePrestate=((e as any).errno??(e as any).code)==='55000'}assert(latePrestate,'later catalog state cannot replace original pre-admission capture');await sql.unsafe('ROLLBACK TO SAVEPOINT late_prestate');
 let incomplete=false;try{await stageNewCatalogCohort(connection,request(),homes.slice(1),{})}catch{incomplete=true}assert(incomplete,'incomplete property home inventory refuses before persistence');
 const altered=structuredClone(prepared);altered.declarations[0].records[0].fields[0].declaration.name='substituted';let unsupported=false;try{await stageNewCatalogCohort(connection,altered,homes,{})}catch(e){unsupported=(e as Error).message==='Original validated catalog preparation required'}assert(unsupported,'reconstructed altered Field candidate refuses before native staging');
 let otherInput=false;try{await stageNewCatalogCohort(connection,request(true),homes,{})}catch(e){otherInput=((e as any).errno??(e as any).code)==='55000'}assert(otherInput,'different complete original input cannot borrow native operation admission');
 const substituted={...prepared,archiveDocuments:[{...prepared.archiveDocuments[0],originalText:prepared.archiveDocuments[0].originalText+' '}]};await sql.unsafe('SAVEPOINT substituted_source');let sourceSubstitution=false;try{await connection.unsafe('SELECT truss.runtime_require_catalog_document_carrier($1::text::jsonb)',[JSON.stringify(substituted.archiveDocuments)])}catch(e){sourceSubstitution=((e as any).errno??(e as any).code)==='55000'}await sql.unsafe('ROLLBACK TO SAVEPOINT substituted_source');await sql.unsafe('RELEASE SAVEPOINT substituted_source');assert(sourceSubstitution,'same interpreted source cannot substitute different original artifact bytes under admitted input');
 const cleared=await sql.unsafe('SELECT (SELECT count(*) FROM truss.schema_rev WHERE rev>0)::text AS revisions,(SELECT count(*) FROM truss.type_def)::text AS types');assert(cleared[0].revisions==='0'&&cleared[0].types==='0','failed cohort savepoint removes earlier revision and Record effects');
 for(const mutation of ["UPDATE truss.row_home_operation SET original_input_bytes=decode('00','hex')","UPDATE truss.row_home_operation SET operation_ordinal=1","DELETE FROM truss.row_home_operation"]){await sql.unsafe('SAVEPOINT operation_originals');let refused=false;try{await sql.unsafe(mutation)}catch(e){refused=((e as any).errno??(e as any).code)==='55000'}assert(refused,'original operation custody refuses '+mutation.split(' ')[0]+' substitution/removal');await sql.unsafe('ROLLBACK TO SAVEPOINT operation_originals')}
 const defaults=prepareDefaultCatalogHomes(prepared);assert(JSON.stringify(defaults.homes)===JSON.stringify(homes),'default homes derive from original absent-binding input, never guessed native IDs');const result=await stageNewCatalogCohort(connection,prepared,defaults.homes,{source:'original test'});
 assert(result.types.length===2&&result.properties.length===2&&result.keys.length===2&&result.relationships.length===1,'entire original declared catalog stages using actual native IDs');
 assert(result.types[0].type_id==='1'&&result.types[1].type_id==='2','native sorted allocator assigns Record identities');
 const generation=await sql.unsafe('SELECT effect_generation::text AS generation FROM truss.row_home_operation');assert(generation[0].generation==='11','every surviving new catalog/archive/lineage/endpoint row contributes original operation generation');
 await sql.unsafe('SAVEPOINT stale_readiness');await sql.unsafe("UPDATE truss.row_home_operation SET phase='effects_ready',readiness_generation=effect_generation");await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');const invalidated=await sql.unsafe('SELECT phase,effect_generation::text AS generation,readiness_generation FROM truss.row_home_operation');assert(invalidated[0].phase==='admitted'&&invalidated[0].generation==='12'&&invalidated[0].readiness_generation===null,'catalog event invalidates previously marked readiness');await sql.unsafe('ROLLBACK TO SAVEPOINT stale_readiness');const restoredGeneration=await sql.unsafe('SELECT effect_generation::text AS generation FROM truss.row_home_operation');assert(restoredGeneration[0].generation==='11','savepoint rollback removes non-surviving catalog generation contribution');
 const properties=await sql.unsafe('SELECT type_id::text AS owner,prop_id::text AS id FROM truss.prop_def ORDER BY type_id');assert(properties[0].id!==properties[1].id,'distinct original owners retain their allocated property identities');
 const keys=await sql.unsafe('SELECT type_id::text AS owner,prop_ids::text AS ids FROM truss.key_def ORDER BY type_id');assert(keys.every((key:{ids:string},index:number)=>key.ids==='{'+properties[index].id+'}'),'every original key resolves actual owning property ID');
 const endpoints=await sql.unsafe('SELECT source_type::text AS source,target_type::text AS target FROM truss.rel_endpoint ORDER BY source_type,target_type');assert(endpoints.length===1&&endpoints[0].source==='1'&&endpoints[0].target==='2','relationship endpoints resolve actual Record allocations');
 const archived=await sql.unsafe('SELECT document FROM truss.schema_doc');assert(archived[0].document===prepared.archiveDocuments[0].originalText,'verbatim original source whitespace survives complete staging');
 let duplicate=false;try{await stageNewCatalogCohort(connection,prepared,homes,{})}catch(e){duplicate=((e as any).errno??(e as any).code)==='55000'}assert(duplicate,'existing identity cannot pass genuinely-new cohort staging');
 const retained=await sql.unsafe('SELECT count(*)::text AS count FROM truss.schema_rev WHERE rev>0');assert(retained[0].count==='1','failed repeated cohort preserves original staged revision only');
 await sql.unsafe('SAVEPOINT replica_catalog_event');await sql.unsafe("SET LOCAL session_replication_role='replica'");await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');const replicaGeneration=await sql.unsafe('SELECT effect_generation::text AS generation FROM truss.row_home_operation');assert(replicaGeneration[0].generation==='12','ALWAYS catalog observer survives replica dispatch');await sql.unsafe('ROLLBACK TO SAVEPOINT replica_catalog_event');
 await sql.unsafe('SAVEPOINT catalog_truncate');let truncateRefusal=false;try{await sql.unsafe('TRUNCATE TABLE truss.rel_endpoint CASCADE')}catch(e){truncateRefusal=((e as any).errno??(e as any).code)==='55000'}assert(truncateRefusal,'catalog truncate cannot bypass row generation and complete effect inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT catalog_truncate');
 const documentBasis=await collectCatalogReportDocumentBasis(connection,prepared,result.provisionalRevision);assert(documentBasis.documents.length===1&&documentBasis.documents[0].doc_id==='cohort'&&documentBasis.documents[0].content_sha256===prepared.original.input.documents[0].artifact.sha256,'report document basis matches actual original input and native source archive');
 assert(documentBasis.nativeObservation.effectGeneration==='11'&&documentBasis.nativeObservation.operationOrdinal==='0','report document basis captures actual original native operation and generation');
 await recheckCatalogReportDocumentBasis(connection,documentBasis);assert(true,'current original report observation rechecks successfully');
 await sql.unsafe('SAVEPOINT stale_document_basis');await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');let staleBasis=false;try{await recheckCatalogReportDocumentBasis(connection,documentBasis)}catch(e){staleBasis=((e as any).errno??(e as any).code)==='55000'}assert(staleBasis,'later catalog event makes captured report document basis stale');await sql.unsafe('ROLLBACK TO SAVEPOINT stale_document_basis');await recheckCatalogReportDocumentBasis(connection,documentBasis);assert(true,'rolled-back catalog contribution restores the original surviving observation cut');
 for(const [field,value] of [['writerXid','1'],['operationOrdinal','1'],['effectGeneration','00'],['effectGeneration','12']] as const){await sql.unsafe('SAVEPOINT unrelated_observation');let unrelated=false;try{await recheckCatalogReportDocumentBasis(connection,{...documentBasis,nativeObservation:{...documentBasis.nativeObservation,[field]:value}})}catch(e){unrelated=((e as any).errno??(e as any).code)==='55000'}assert(unrelated,field+' substitution refuses report observation recheck');await sql.unsafe('ROLLBACK TO SAVEPOINT unrelated_observation')}
 const observed=JSON.parse(Buffer.from(documentBasis.observations[0].evidence.bytesBase64,'base64').toString());assert(JSON.stringify(observed.observation)===JSON.stringify(prepared.documents[0].interpretation),'original owner observation and reversible transition preserved inside exact evidence artifact');
 const composed=await collectCatalogReportPreparation(connection,prepared,result.provisionalRevision,owner,fieldOwner);
 assert(JSON.stringify(composed.counts)===JSON.stringify({typesAdded:'2',propertiesAdded:'2',keysAdded:'2',relationshipsAdded:'1',endpointsAdded:'1',elementsRetired:'0'}),'composed report preparation derives all six counts under original native cut');
 assert(composed.documentBasis.nativeObservation.effectGeneration==='11'&&composed.observationCoverage.availability==='available','composed preparation retains matching native cut and actual available owner observations');
 assert(composed.provisional.length===0,'empty provisional report inventory has original native proof across the full retained catalog');
 await sql.unsafe('SAVEPOINT nonempty_provisional');await sql.unsafe('UPDATE truss.type_def SET provisional=true,definition_source_kind=NULL,definition_rev=NULL,definition_doc_ord=NULL,definition_document_id=NULL WHERE type_id=1');let provisionalRefusal=false;try{await sql.unsafe('SELECT truss.runtime_require_empty_provisional_catalog(1)')}catch(e){provisionalRefusal=((e as any).errno??(e as any).code)==='0A000'}assert(provisionalRefusal,'nonempty provisional catalog cannot become an empty report inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT nonempty_provisional');await sql.unsafe('RELEASE SAVEPOINT nonempty_provisional');
 assert(composed.validationEvidence.documentInterpretations[0].evidence.sha256===composed.documentBasis.observations[0].evidence.sha256,'composed producer interpretation preserves the original archived observation evidence');
 assert(composed.validationEvidence.diagnostics.length===prepared.documents[0].interpretation.sourceValidation.diagnostics.length+prepared.documents[0].interpretation.targetValidation!.diagnostics.length,'composed validation retains complete original and target-basis producer diagnostic inventories');
 assert(composed.scope==='original_new_catalog_report_preparation_only'&&composed.extensions.entries.length===0,'composed basis does not fabricate accepted status or extensions');
 await sql.unsafe('SAVEPOINT mixed_preparation');let changed=false;const changingConnection={unsafe:async(query:string,parameters:unknown[]=[])=>{const rows=await connection.unsafe(query,parameters);if(query.includes('runtime_collect_report_documents'))await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');return rows}};
 try{await collectCatalogReportPreparation(changingConnection,prepared,result.provisionalRevision,owner,fieldOwner)}catch(e){changed=(e as Error).message==='Mixed original report preparation cut'}assert(changed,'later catalog event between document and count observations refuses composed preparation');await sql.unsafe('ROLLBACK TO SAVEPOINT mixed_preparation');await sql.unsafe('RELEASE SAVEPOINT mixed_preparation');
 const inventory=await sql.unsafe('SELECT family,identity::text AS identity FROM truss.runtime_collect_new_catalog_inventory($1::int)',[result.provisionalRevision]);
 const families=Object.fromEntries(['type','property','key','relationship','endpoint'].map(family=>[family,inventory.filter((row:{family:string})=>row.family===family).length]));assert(JSON.stringify(families)===JSON.stringify({type:2,property:2,key:2,relationship:1,endpoint:1}),'native collector returns actual complete new-family identity inventory');
 const counts=await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_counts(1)');assert(JSON.stringify(counts[0])===JSON.stringify({types_added:'2',properties_added:'2',keys_added:'2',relationships_added:'1',endpoints_added:'1',elements_retired:'0'}),'all six count fields derive from source-correlated surviving identities and unchanged retained cut');
 const endpoint=JSON.parse(inventory.find((row:{family:string})=>row.family==='endpoint').identity);assert(endpoint[1]==='1'&&endpoint[2]==='2','collected endpoint is original relationship/source/target tuple');
 await sql.unsafe('SAVEPOINT changed_archive_bytes');await sql.unsafe("UPDATE truss.schema_doc SET document=document||' ',content_sha256=encode(sha256(convert_to(document||' ','UTF8')),'hex') WHERE rev=1");let archiveCountRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_counts(1)')}catch(e){archiveCountRefusal=((e as any).errno??(e as any).code)==='55000'}assert(archiveCountRefusal,'count producer refuses source-byte substitution even with matching new native digest');await sql.unsafe('ROLLBACK TO SAVEPOINT changed_archive_bytes');
 await sql.unsafe('SAVEPOINT retained_genesis_edit');await sql.unsafe("UPDATE truss.schema_rev SET origin='{\"changed\":true}'::jsonb WHERE rev=0");let retainedEdit=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){retainedEdit=((e as any).errno??(e as any).code)==='55000'}assert(retainedEdit,'new-only inventory cannot hide changed original retained revision metadata');await sql.unsafe('ROLLBACK TO SAVEPOINT retained_genesis_edit');
 await sql.unsafe('SAVEPOINT unplanned_revision');await sql.unsafe("INSERT INTO truss.schema_rev(rev,origin) VALUES(2,'{}'::jsonb)");let unplannedRevision=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){unplannedRevision=((e as any).errno??(e as any).code)==='55000'}assert(unplannedRevision,'unplanned extra catalog revision cannot disappear from effect inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT unplanned_revision');
 for(const [label,mutation] of [
  ['missing original Field',"DELETE FROM truss.prop_def WHERE prop_id=1"],
  ['missing original Key',"DELETE FROM truss.key_def WHERE type_id=1"],
  ['altered original Field scalar type',"UPDATE truss.prop_def SET scalar_type='integer' WHERE prop_id=1"],
  ['altered original Field nullability',"UPDATE truss.prop_def SET nullability='absent-allowed' WHERE prop_id=1"],
  ['substituted Key component',"UPDATE truss.key_def SET prop_ids=ARRAY[2] WHERE type_id=1"],
  ['altered Key primary flag',"UPDATE truss.key_def SET is_primary=false WHERE type_id=1"],
  ['altered relationship upper bound',"UPDATE truss.rel_def SET source_max=2"],
  ['altered relationship target key',"UPDATE truss.rel_def SET target_key=NULL"],
 ] as const){await sql.unsafe('SAVEPOINT changed_definition');await sql.unsafe(mutation);let refused=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){refused=((e as any).errno??(e as any).code)==='55000'}assert(refused,label+' refuses inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT changed_definition')}
 await sql.unsafe('SAVEPOINT swapped_endpoint');await sql.unsafe('UPDATE truss.rel_endpoint SET source_type=target_type');let endpointRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){endpointRefusal=((e as any).errno??(e as any).code)==='55000'}assert(endpointRefusal,'equal-count substituted endpoint identity refuses collection');await sql.unsafe('ROLLBACK TO SAVEPOINT swapped_endpoint');
 await sql.unsafe('SAVEPOINT missing_endpoint');await sql.unsafe('DELETE FROM truss.rel_endpoint');let missingRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){missingRefusal=((e as any).errno??(e as any).code)==='55000'}assert(missingRefusal,'missing authored endpoint refuses collection');await sql.unsafe('ROLLBACK TO SAVEPOINT missing_endpoint');
 await sql.unsafe('SAVEPOINT inventory_retired');await sql.unsafe('UPDATE truss.type_def SET retired_rev=1 WHERE type_id=1');let lifecycleRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){lifecycleRefusal=((e as any).errno??(e as any).code)==='0A000'}assert(lifecycleRefusal,'new-only collector cannot hide retirement or report it as addition');await sql.unsafe('ROLLBACK TO SAVEPOINT inventory_retired');
 const head=await sql.unsafe('SELECT rev::text AS revision FROM truss.schema_head');assert(head[0].revision==='0','provisional cohort never publishes accepted head');
 let barrier=false;try{await sql.unsafe('COMMIT')}catch(e){barrier=((e as any).errno??(e as any).code)==='55000'}assert(barrier,'unfinished complete acceptance cannot commit');
 let operationTruncate=false;try{await sql.unsafe('TRUNCATE TABLE truss.row_home_operation CASCADE')}catch(e){operationTruncate=((e as any).errno??(e as any).code)==='55000'}assert(operationTruncate,'operation truncate guard refuses even with no pending admission trigger');
 let endedObservation=false;try{await recheckCatalogReportDocumentBasis(connection,documentBasis)}catch(e){endedObservation=((e as any).errno??(e as any).code)==='55000'}assert(endedObservation,'ended native transaction cannot reuse captured report observation');
 const empty=await sql.unsafe('SELECT count(*)::text AS count FROM truss.type_def');assert(empty[0].count==='0','failed commit removes all provisional catalog effects');
 const sourcePins=Object.fromEntries(await Promise.all(components.map(async component=>[component,new Bun.CryptoHasher('sha256').update(await Bun.file('packages/postgresql/native/'+component+'.sql').arrayBuffer()).digest('hex')])));
 const receipt={sourcePins,reportPreparationProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-report-preparation.ts').arrayBuffer()).digest('hex'),assertionProfiles:{declarations:composed.ownerObservations.profile,fields:composed.ownerObservations.fieldProfile},reportDocumentProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-report-document-basis.ts').arrayBuffer()).digest('hex'),defaultHomeProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-default-homes.ts').arrayBuffer()).digest('hex'),stageProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-new-stage.ts').arrayBuffer()).digest('hex'),originalInputSha256:new Bun.CryptoHasher('sha256').update(Buffer.from(prepared.original.originalUtf8Hex,'hex')).digest('hex'),engine:version[0].server_version,umfProfile:preparation.umfProfile,checks,scope:'Actual original complete declared new catalog staging and atomic refusal only. Root profile/authority, retained lifecycle, acceptance report/head/finalizer and public entrypoint are unqualified.'};await Bun.write('docs/helix/04-build/evidence/catalog-new-cohort.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({checks:checks.length}));
}finally{await sql.close()}
