import {createRequire} from 'node:module';
const {chromium}=createRequire('/Users/erik/Projects/umf/package.json')('playwright');
const build=await Bun.build({entrypoints:['packages/postgresql/src/acceptance-json.ts'],target:'browser',format:'esm'});if(!build.success)throw Error('Decoder browser build failed');const bundle=await build.outputs[0].text();
const corpus=await Bun.file('docs/helix/03-test/acceptance-outer-json-expected.proposal.json').json();
const fixture=await Bun.file('docs/helix/02-design/contracts/bindings/acceptance-input-capacity-v0.1.fixture.json').json();
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/decoder.js'?new Response(bundle,{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>Truss acceptance decoder</title>')}});
const browser=await chromium.launch({headless:true});
try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);const results=await page.evaluate(async({corpusText,fixtureText})=>{
 const corpus=JSON.parse(corpusText),fixture=JSON.parse(fixtureText);
 const api=await import('/decoder.js');const observations=[];
 for(const c of corpus.cases){const bytes=Uint8Array.from(c.utf8Hex.match(/../g)??[],(h:string)=>parseInt(h,16));let result;try{result={status:'decoded',value:api.decodeAcceptanceJson(bytes)}}catch(e){if(!(e instanceof api.AcceptanceJsonError))throw e;result={status:'refused',reason:e.reason}}if(JSON.stringify(result)!==JSON.stringify(c.expected))throw Error('Independent browser oracle mismatch: '+c.name);observations.push({name:c.name,outcome:result.status})}
 const decoded=api.decodeAcceptanceJson(new TextEncoder().encode(JSON.stringify(fixture.input)));if(JSON.stringify(decoded)!==JSON.stringify(fixture.input))throw Error('Complete custody lost');observations.push({name:'complete original native/converted input fixture',outcome:'decoded'});return observations;
 },{corpusText:JSON.stringify(corpus),fixtureText:JSON.stringify(fixture)});const hash=(value:string)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');const receipt={browser:browser.version(),sourceSha256:hash(await Bun.file('packages/postgresql/src/acceptance-json.ts').text()),bundleSha256:hash(bundle),corpusSha256:hash(await Bun.file('docs/helix/03-test/acceptance-outer-json-expected.proposal.json').text()),observations:results,scope:'Actual portable decoder bytes/value/refusal in Chromium plus complete planning fixture custody. No shared operation-account/heap qualification, schema/artifact/profile/native admission or committed acceptance.'};await Bun.write('docs/helix/04-build/evidence/design-audit/acceptance-json-browser.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({browser:receipt.browser,cases:results.length,scope:receipt.scope}));}finally{await browser.close();server.stop(true)}
