import {createRequire} from 'node:module';
const {chromium}=createRequire('/Users/erik/Projects/umf/package.json')('playwright');
const ownerManifest=await Bun.file('website/static/schema/manifest.json').json();
if(ownerManifest.owner!=='DocumentDrivenDX/umf'||!(/^[a-f0-9]{40}$/).test(ownerManifest.revision))throw Error('Original UMF browser owner pin required');
for(const [name,expected] of Object.entries(ownerManifest.assets)){
 const actual=new Bun.CryptoHasher('sha256').update(await Bun.file('website/static/schema/'+name).arrayBuffer()).digest('hex');
 if(actual!==expected)throw Error('Original UMF browser asset mismatch: '+name);
 const published=new Bun.CryptoHasher('sha256').update(await Bun.file('website/public/schema/'+name).arrayBuffer()).digest('hex');
 if(published!==expected)throw Error('Generated site schema asset mismatch: '+name);
}
const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(req){let path=new URL(req.url).pathname;if(!path.startsWith('/truss/'))return new Response('Not found',{status:404});path=path.slice(7);if(!path||path.endsWith('/'))path+='index.html';const file=Bun.file('website/public/'+path);return await file.exists()?new Response(file):new Response('Not found',{status:404});}});
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage();const errors:string[]=[];page.on('pageerror',(e:unknown)=>errors.push(String(e)));
 const base=`http://127.0.0.1:${server.port}/truss/`;
 await page.goto(base+'model/');const frame=page.frameLocator('iframe[title="Truss storage schema — UMF browser"]');
 await frame.locator('.definition-list').waitFor();
 if(!(await frame.locator('#inspector').innerText()).includes('Core structure valid'))throw Error('Core model did not validate');
 const definitions=await frame.locator('.definition-list a').count();
 await page.goto(base+'schema/#'+new URLSearchParams({schema:'truss-layout',definition:JSON.stringify(['truss-layout','prop_def'])}));
 await page.locator('.definition-heading').waitFor();
 if(!(await page.locator('table').innerText()).includes('declaration_module'))throw Error('Current layout field missing');
 await page.locator('table a').filter({hasText:'declaration_module'}).click();
 await page.locator('.definition-heading').filter({hasText:'declaration_module'}).waitFor();
 const downloadEvent=page.waitForEvent('download');await page.getByText('Download source',{exact:true}).click();const download=await downloadEvent;
 const downloaded=await Bun.file((await download.path())!).text();const original=await Bun.file('website/static/schema/truss-layout.umf.json').text();if(downloaded!==original)throw Error('Download changed source');
 await page.goto(base+'schema/#'+new URLSearchParams({schema:'truss-layout',definition:JSON.stringify(['truss-layout','source_epoch_registry'])}));
 await page.locator('.definition-heading').filter({hasText:'source_epoch_registry'}).waitFor();
 if(!(await page.locator('table').innerText()).includes('predecessor_epoch'))throw Error('Epoch candidate columns missing');
 const nativeEvent=page.waitForEvent('download');await page.getByText('Download retained native source',{exact:true}).click();const nativeDownload=await nativeEvent;
 const nativeBytes=new Uint8Array(await Bun.file((await nativeDownload.path())!).arrayBuffer());
 const structural=await Bun.file('website/static/schema/truss-layout.umf.json').json();
 const nativeExpected=new Uint8Array(await Bun.file(structural.extensions['truss.layout.native'].sourceModel).arrayBuffer());
 if(nativeBytes.length!==nativeExpected.length||nativeBytes.some((b,i)=>b!==nativeExpected[i]))throw Error('Native archive download changed original bytes');
 await page.goto(base+'schema/#'+new URLSearchParams({schema:'truss-layout',definition:JSON.stringify(['truss-layout','operation_configuration'])}));
 await page.locator('.definition-heading').filter({hasText:'operation_configuration'}).waitFor();
 const captureTable=await page.locator('table').innerText();
 for(const name of ['original_writer_xid','original_context_sha256','configuration_generation','admission_profile_bytes','installed_inventory_sha256'])if(!captureTable.includes(name))throw Error('Configuration capture column missing: '+name);
 const adjunctEvent=page.waitForEvent('download');await page.getByText('Download configuration adjunct source',{exact:true}).click();const adjunctDownload=await adjunctEvent;
 const adjunctBytes=new Uint8Array(await Bun.file((await adjunctDownload.path())!).arrayBuffer()),adjunctExpected=new Uint8Array(await Bun.file(structural.extensions['truss.layout.native'].additionalSourceModel).arrayBuffer());
 if(adjunctBytes.length!==adjunctExpected.length||adjunctBytes.some((b,i)=>b!==adjunctExpected[i]))throw Error('Adjunct archive changed original bytes');
 await page.goto(base+'schema/#'+new URLSearchParams({schema:'truss-layout',definition:JSON.stringify(['truss-layout','layout_migration_receipt'])}));
 await page.locator('.definition-heading').filter({hasText:'layout_migration_receipt'}).waitFor();
 const migrationTable=await page.locator('table').innerText();
 for(const name of ['storage_row_id','original_attempt_identity_bytes','original_request_bytes','original_receipt_bytes','original_receipt_sha256'])if(!migrationTable.includes(name))throw Error('Migration receipt column missing: '+name);
 const migrationEvent=page.waitForEvent('download');await page.getByText('Download migration adjunct source',{exact:true}).click();const migrationDownload=await migrationEvent;
 const migrationBytes=new Uint8Array(await Bun.file((await migrationDownload.path())!).arrayBuffer()),migrationExpected=new Uint8Array(await Bun.file(structural.extensions['truss.layout.native'].migrationSourceModel).arrayBuffer());
 if(migrationBytes.length!==migrationExpected.length||migrationBytes.some((b,i)=>b!==migrationExpected[i]))throw Error('Migration archive changed original bytes');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'schema/');await page.locator('.definition-list').waitFor();
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile page overflow');if(errors.length)throw Error(errors.join('\n'));
 const receipt={browser:browser.version(),ownerRevision:ownerManifest.revision,definitions,checks:['Hugo Model page embeds working owner browser','current structural model validates','prop_def deep link and declaration_module field navigation','download is byte-identical UTF-8 source','epoch registry and predecessor columns browse correctly','retained native source download is byte-exact','configuration capture columns browse and adjunct download is byte-exact','migration receipt columns browse and adjunct download is byte-exact','390px mobile browser has no horizontal page overflow','no browser errors'],scope:'Actual generated site under /truss/ in Chromium; structural inspection only, no deployment or native runtime qualification.'};
 await Bun.write('docs/helix/04-build/evidence/design-audit/schema-browser-site.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
}finally{await browser.close();server.stop(true)}
