import {collectCatalogAdmissionConfigurationBasis,requireOriginalCatalogAdmissionConfigurationBasis,recheckOriginalCatalogAdmissionConfigurationBasis} from '../packages/umf-bun/src/catalog-admission-configuration-basis';
import {collectCatalogConfigurationBasis,requireOriginalCatalogConfigurationBasis,recheckOriginalCatalogConfigurationBasis} from '../packages/umf-bun/src/catalog-configuration-basis';
import {collectCatalogEpochContextBasis,requireOriginalCatalogEpochContextBasis,recheckOriginalCatalogEpochContextBasis} from '../packages/umf-bun/src/catalog-epoch-context-basis';
import {collectCatalogCapturedOriginBasis,requireOriginalCapturedOriginBasis,recheckOriginalCapturedOriginBasis} from '../packages/umf-bun/src/catalog-captured-origin-basis';
import {collectCatalogAssertedOriginBasis} from '../packages/umf-bun/src/catalog-asserted-origin-basis';
import {collectCatalogOriginalExecutionBasis,requireOriginalCatalogNativeContext} from '../packages/umf-bun/src/catalog-original-execution-basis';
/** Actual full declared new-cohort staging. No acceptance/finalizer qualification. */
import {SQL} from 'bun';
import {loadUmfDeclarationProducer,loadUmfFieldAssertionProducer} from '../packages/umf-bun/src/index';
import {createCatalogReportCorrespondence} from '../packages/umf-bun/src/catalog-report-correspondence';
import {collectCatalogReportPreparation} from '../packages/umf-bun/src/catalog-report-preparation';
import {createCatalogInputPreparation} from '../packages/umf-bun/src/catalog-input';
import {stageNewCatalogCohort} from '../packages/umf-bun/src/catalog-new-stage';
import {prepareDefaultCatalogHomes} from '../packages/umf-bun/src/catalog-default-homes';
import {collectCatalogReportDocumentBasis,recheckCatalogReportDocumentBasis} from '../packages/umf-bun/src/catalog-report-document-basis';
const directory=process.env.TRUSS_UMF_PRODUCER;if(!directory)throw Error('Original owner directory required');
const declarationDirectory=process.env.TRUSS_UMF_DECLARATION_PRODUCER,fieldDirectory=process.env.TRUSS_UMF_FIELD_ASSERTION_PRODUCER;if(!declarationDirectory||!fieldDirectory)throw Error('Both original assertion producer directories required');
const owner=await loadUmfDeclarationProducer(declarationDirectory),fieldOwner=await loadUmfFieldAssertionProducer(fieldDirectory);
const url=process.env.TRUSS_OPERATION_TEST_URL;if(!url?.startsWith('postgres://postgres@127.0.0.1:15434/'))throw Error('Dedicated disposable endpoint required');
const preparation=await createCatalogInputPreparation(directory,'/Users/erik/Projects/umf/package.json');
const sql=new SQL(url,{max:1});const connection={unsafe:async(query:string,parameters:unknown[]=[])=>await sql.unsafe(query,parameters as any[])};
const checks:string[]=[];function assert(value:boolean,label:string){if(!value)throw Error(label);checks.push(label)}
const components=['operation-admission','operation-commit-barrier','catalog-generation-observer','catalog-document-batch','catalog-lineage-producer','catalog-source-integrity','catalog-type-match','catalog-type-stage','catalog-property-match','catalog-property-stage','catalog-key-match','catalog-key-stage','catalog-key-batch','catalog-relationship-match','catalog-relationship-stage','catalog-report-documents','catalog-new-inventory','catalog-observation-recheck','catalog-input-custody','catalog-prestate-capture','catalog-new-prestate-parity','catalog-new-counts','catalog-provisional-empty','catalog-report-immutability','catalog-original-context'];
function request(missingName=false){const input=structuredClone(fixture.input);input.binding={state:'absent'};input.transforms=[];const model={umf:'0.7.0',id:'cohort',vocabularies:{},extensions:{},modules:[{id:'m',namespace:'m',elements:[...['A','B'].map(id=>({id,kind:'record',members:[{module:'m',element:id+'-label'}],keys:[{id:'label-key',name:'label-key',fields:[{module:'m',element:id+'-label'}],primary:true}],extensions:{}})),...['A','B'].map(id=>({id:id+'-label',...(!missingName?{name:id+'-label'}:{}),kind:'field',scalarType:'string',nullability:'required',cardinality:'one',extensions:{}}))],relationships:[{id:'A-B',name:'A-B',source:[{module:'m',element:'A'}],target:[{module:'m',element:'B',key:'label-key'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:0,max:2},targetLifecycle:'independent',directed:true}]}]};const bytes=Buffer.from(' \n'+JSON.stringify(model)+'\n');input.documents=[{documentId:'cohort',documentRevision:'r1',artifact:{identity:'original-cohort',bytesBase64:bytes.toString('base64'),sha256:new Bun.CryptoHasher('sha256').update(bytes).digest('hex')},umfProfile:preparation.umfProfile,ingress:{kind:'native'}}];return preparation.prepare(new TextEncoder().encode(JSON.stringify(input)))}
const fixture=await Bun.file('docs/helix/02-design/contracts/bindings/acceptance-input-capacity-v0.1.fixture.json').json();
const homes=['A','B'].map(elementId=>({documentId:'cohort',moduleId:'m',elementId,fieldModule:'m',fieldId:elementId+'-label',home:'json' as const}));
try{
 const version=await sql.unsafe('SHOW server_version');assert(version[0].server_version.startsWith('17.9'),'actual PostgreSQL17.9');
 await sql.unsafe(await Bun.file('docs/helix/04-build/evidence/qualified-property-layout-0.15.owner-export.sql').text());
 for(const component of components)await sql.unsafe(await Bun.file('packages/postgresql/native/'+component+'.sql').text());
 const installedObservers=await sql.unsafe("SELECT count(*)::text AS n FROM pg_trigger WHERE tgname='runtime_catalog_generation' AND tgenabled='A' AND NOT tgisinternal");assert(installedObservers[0].n==='11','eleven ALWAYS catalog generation observers installed');
 const reportGuards=await sql.unsafe("SELECT count(*)::text AS n FROM pg_trigger WHERE tgrelid='truss.catalog_acceptance_report'::regclass AND tgname IN ('runtime_catalog_report_immutable','runtime_catalog_report_no_truncate') AND tgenabled='A' AND NOT tgisinternal");assert(reportGuards[0].n==='2','both immutable report guards installed with ALWAYS dispatch');
 await sql.unsafe("CREATE FUNCTION pg_temp.actor_boundary_probe() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$BEGIN PERFORM * FROM truss.runtime_admit_operation('catalog-acceptance',decode('01','hex'),decode('01','hex'),decode('01','hex'),decode('01','hex'),decode('01','hex'),decode('01','hex')); END$$");
 await sql.unsafe('BEGIN');await sql.unsafe('SAVEPOINT definer_actor');await sql.unsafe('SET LOCAL ROLE pg_read_all_data');let definerActor=false;
 try{await sql.unsafe('SELECT pg_temp.actor_boundary_probe()')}catch(e){definerActor=((e as any).errno??(e as any).code)==='55000'&&(e as Error).message.includes('invoker actor boundary')}
 await sql.unsafe('ROLLBACK TO SAVEPOINT definer_actor');assert(definerActor,'nested definer owner cannot replace selected invoker actor at admission');
 const noDefinerRows=await sql.unsafe('SELECT count(*)::text AS n FROM truss.row_home_operation');assert(noDefinerRows[0].n==='0','definer actor refusal precedes operation registry effects');await sql.unsafe('ROLLBACK');
 await sql.unsafe('BEGIN');await sql.unsafe('CREATE ROLE "Truss Actor / probe" NOLOGIN');await sql.unsafe('SET LOCAL ROLE "Truss Actor / probe"');
 const quotedActor=await sql.unsafe("SELECT current_user::text AS actor,current_setting('role') AS setting");assert(quotedActor[0].actor==='Truss Actor / probe'&&quotedActor[0].setting===quotedActor[0].actor,'native selected role setting preserves quoted actor name exactly');await sql.unsafe('ROLLBACK');
 await sql.unsafe('BEGIN');await sql.unsafe('SAVEPOINT reserved_actor');let reservedActor=false;try{await sql.unsafe('CREATE ROLE "none" NOLOGIN')}catch(e){reservedActor=((e as any).errno??(e as any).code)==='42939'}assert(reservedActor,'native none sentinel cannot collide with a created role on tested build');await sql.unsafe('ROLLBACK');
 const prepared=request();
 await sql.unsafe('BEGIN');await sql.unsafe('SAVEPOINT earlier_shared_head');await sql.unsafe('SELECT rev FROM truss.schema_head FOR SHARE');let earlierShared=false;try{await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate()')}catch(e){earlierShared=((e as any).errno??(e as any).code)==='55000'}assert(earlierShared,'catalog prestate refuses upgrade of earlier shared head admission');await sql.unsafe('ROLLBACK TO SAVEPOINT earlier_shared_head');const capture=await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate() AS bytes');const originalPrestate=JSON.parse(Buffer.from(capture[0].bytes,'hex').toString());assert(originalPrestate.head.rev===0&&originalPrestate.types.length===0&&originalPrestate.properties.length===0&&originalPrestate.keys.length===0&&originalPrestate.relationships.length===0&&originalPrestate.endpoints.length===0,'actual original empty catalog start cut captured under head exclusion');
 await sql.unsafe("SELECT * FROM truss.runtime_admit_operation('catalog-acceptance',decode('01','hex'),decode($1::text,'hex'),decode($2::text,'hex'),decode('04','hex'),decode('05','hex'),decode('06','hex'))",[prepared.original.originalUtf8Hex,capture[0].bytes]);
 const retainedPrestate=await sql.unsafe("SELECT encode(original_prestate_bytes,'hex') AS bytes FROM truss.row_home_operation");assert(retainedPrestate[0].bytes===capture[0].bytes,'original native prestate bytes retained unchanged in operation custody');
 await sql.unsafe('SAVEPOINT late_prestate');let latePrestate=false;try{await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate()')}catch(e){latePrestate=((e as any).errno??(e as any).code)==='55000'}assert(latePrestate,'later catalog state cannot replace original pre-admission capture');await sql.unsafe('ROLLBACK TO SAVEPOINT late_prestate');
 let incomplete=false;try{await stageNewCatalogCohort(connection,request(),homes.slice(1),{})}catch{incomplete=true}assert(incomplete,'incomplete property home inventory refuses before persistence');
 const altered=structuredClone(prepared);altered.declarations[0].records[0].fields[0].declaration.name='substituted';let unsupported=false;try{await stageNewCatalogCohort(connection,altered,homes,{})}catch(e){unsupported=(e as Error).message==='Original validated catalog preparation required'}assert(unsupported,'reconstructed altered Field candidate refuses before native staging');
 let otherInput=false;try{await stageNewCatalogCohort(connection,request(true),homes,{})}catch(e){otherInput=((e as any).errno??(e as any).code)==='55000'}assert(otherInput,'different complete original input cannot borrow native operation admission');
 const substituted={...prepared,archiveDocuments:[{...prepared.archiveDocuments[0],originalText:prepared.archiveDocuments[0].originalText+' '}]};await sql.unsafe('SAVEPOINT substituted_source');let sourceSubstitution=false;try{await connection.unsafe('SELECT truss.runtime_require_catalog_document_carrier($1::text::jsonb)',[JSON.stringify(substituted.archiveDocuments)])}catch(e){sourceSubstitution=((e as any).errno??(e as any).code)==='55000'}await sql.unsafe('ROLLBACK TO SAVEPOINT substituted_source');await sql.unsafe('RELEASE SAVEPOINT substituted_source');assert(sourceSubstitution,'same interpreted source cannot substitute different original artifact bytes under admitted input');
 const cleared=await sql.unsafe('SELECT (SELECT count(*) FROM truss.schema_rev WHERE rev>0)::text AS revisions,(SELECT count(*) FROM truss.type_def)::text AS types');assert(cleared[0].revisions==='0'&&cleared[0].types==='0','failed cohort savepoint removes earlier revision and Record effects');
 for(const mutation of ["UPDATE truss.row_home_operation SET original_input_bytes=decode('00','hex')","UPDATE truss.row_home_operation SET operation_ordinal=1","DELETE FROM truss.row_home_operation"]){await sql.unsafe('SAVEPOINT operation_originals');let refused=false;try{await sql.unsafe(mutation)}catch(e){refused=((e as any).errno??(e as any).code)==='55000'}assert(refused,'original operation custody refuses '+mutation.split(' ')[0]+' substitution/removal');await sql.unsafe('ROLLBACK TO SAVEPOINT operation_originals')}
 const defaults=prepareDefaultCatalogHomes(prepared);assert(JSON.stringify(defaults.homes)===JSON.stringify(homes),'default homes derive from original absent-binding input, never guessed native IDs');const result=await stageNewCatalogCohort(connection,prepared,defaults.homes,{source:'original test'});
 assert(result.types.length===2&&result.properties.length===2&&result.keys.length===2&&result.relationships.length===1,'entire original declared catalog stages using actual native IDs');
 assert(result.types[0].type_id==='1'&&result.types[1].type_id==='2','native sorted allocator assigns Record identities');
 const generation=await sql.unsafe('SELECT effect_generation::text AS generation FROM truss.row_home_operation');assert(generation[0].generation==='11','every surviving new catalog/archive/lineage/endpoint row contributes original operation generation');
 await sql.unsafe('SAVEPOINT stale_readiness');await sql.unsafe("UPDATE truss.row_home_operation SET phase='effects_ready',readiness_generation=effect_generation");await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');const invalidated=await sql.unsafe('SELECT phase,effect_generation::text AS generation,readiness_generation FROM truss.row_home_operation');assert(invalidated[0].phase==='admitted'&&invalidated[0].generation==='12'&&invalidated[0].readiness_generation===null,'catalog event invalidates previously marked readiness');await sql.unsafe('ROLLBACK TO SAVEPOINT stale_readiness');const restoredGeneration=await sql.unsafe('SELECT effect_generation::text AS generation FROM truss.row_home_operation');assert(restoredGeneration[0].generation==='11','savepoint rollback removes non-surviving catalog generation contribution');
 const properties=await sql.unsafe('SELECT type_id::text AS owner,prop_id::text AS id FROM truss.prop_def ORDER BY type_id');assert(properties[0].id!==properties[1].id,'distinct original owners retain their allocated property identities');
 const keys=await sql.unsafe('SELECT type_id::text AS owner,prop_ids::text AS ids FROM truss.key_def ORDER BY type_id');assert(keys.every((key:{ids:string},index:number)=>key.ids==='{'+properties[index].id+'}'),'every original key resolves actual owning property ID');
 const endpoints=await sql.unsafe('SELECT source_type::text AS source,target_type::text AS target FROM truss.rel_endpoint ORDER BY source_type,target_type');assert(endpoints.length===1&&endpoints[0].source==='1'&&endpoints[0].target==='2','relationship endpoints resolve actual Record allocations');
 const archived=await sql.unsafe('SELECT document FROM truss.schema_doc');assert(archived[0].document===prepared.archiveDocuments[0].originalText,'verbatim original source whitespace survives complete staging');
 let duplicate=false;try{await stageNewCatalogCohort(connection,prepared,homes,{})}catch(e){duplicate=((e as any).errno??(e as any).code)==='55000'}assert(duplicate,'existing identity cannot pass genuinely-new cohort staging');
 const retained=await sql.unsafe('SELECT count(*)::text AS count FROM truss.schema_rev WHERE rev>0');assert(retained[0].count==='1','failed repeated cohort preserves original staged revision only');
 await sql.unsafe('SAVEPOINT replica_catalog_event');await sql.unsafe("SET LOCAL session_replication_role='replica'");await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');const replicaGeneration=await sql.unsafe('SELECT effect_generation::text AS generation FROM truss.row_home_operation');assert(replicaGeneration[0].generation==='12','ALWAYS catalog observer survives replica dispatch');await sql.unsafe('ROLLBACK TO SAVEPOINT replica_catalog_event');
 await sql.unsafe('SAVEPOINT catalog_truncate');let truncateRefusal=false;try{await sql.unsafe('TRUNCATE TABLE truss.rel_endpoint CASCADE')}catch(e){truncateRefusal=((e as any).errno??(e as any).code)==='55000'}assert(truncateRefusal,'catalog truncate cannot bypass row generation and complete effect inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT catalog_truncate');
 const documentBasis=await collectCatalogReportDocumentBasis(connection,prepared,result.provisionalRevision);assert(documentBasis.documents.length===1&&documentBasis.documents[0].doc_id==='cohort'&&documentBasis.documents[0].content_sha256===prepared.original.input.documents[0].artifact.sha256,'report document basis matches actual original input and native source archive');
 assert(documentBasis.nativeObservation.effectGeneration==='11'&&documentBasis.nativeObservation.operationOrdinal==='0','report document basis captures actual original native operation and generation');
 await recheckCatalogReportDocumentBasis(connection,documentBasis);assert(true,'current original report observation rechecks successfully');
 await sql.unsafe('SAVEPOINT stale_document_basis');await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');let staleBasis=false;try{await recheckCatalogReportDocumentBasis(connection,documentBasis)}catch(e){staleBasis=((e as any).errno??(e as any).code)==='55000'}assert(staleBasis,'later catalog event makes captured report document basis stale');await sql.unsafe('ROLLBACK TO SAVEPOINT stale_document_basis');await recheckCatalogReportDocumentBasis(connection,documentBasis);assert(true,'rolled-back catalog contribution restores the original surviving observation cut');
 for(const [field,value] of [['writerXid','1'],['operationOrdinal','1'],['effectGeneration','00'],['effectGeneration','12']] as const){await sql.unsafe('SAVEPOINT unrelated_observation');let unrelated=false;try{await recheckCatalogReportDocumentBasis(connection,{...documentBasis,nativeObservation:{...documentBasis.nativeObservation,[field]:value}})}catch(e){unrelated=((e as any).errno??(e as any).code)==='55000'}assert(unrelated,field+' substitution refuses report observation recheck');await sql.unsafe('ROLLBACK TO SAVEPOINT unrelated_observation')}
 const observed=JSON.parse(Buffer.from(documentBasis.observations[0].evidence.bytesBase64,'base64').toString());assert(JSON.stringify(observed.observation)===JSON.stringify(prepared.documents[0].interpretation),'original owner observation and reversible transition preserved inside exact evidence artifact');
 const transformedInput={...prepared.original.input,transforms:structuredClone(fixture.input.transforms)};const transformed=preparation.prepare(new TextEncoder().encode(JSON.stringify(transformedInput)));let transformRefusal=false;try{await stageNewCatalogCohort(connection,transformed,homes,{})}catch(e){transformRefusal=(e as Error).message==='Complete transform execution and report producer required'}assert(transformRefusal,'declared transform cannot pass new-only native staging as if absent');
 const composed=await collectCatalogReportPreparation(connection,prepared,result.provisionalRevision,owner,fieldOwner);
 assert(composed.coreAssertionIdentities.entries.length===11&&composed.coreAssertionIdentities.entries.filter(e=>e.ruleName==='core.keys').length===2&&composed.coreAssertionIdentities.entries.filter(e=>e.ruleName==='core.relationships').length===1,'composed original source identities include both Record keys and relationship alongside core Field facts');assert(composed.coreAssertionIdentities.complete===false&&composed.coreAssertionIdentities.entries.every(e=>e.enforcement==='none'&&e.source.sha256===prepared.original.input.documents[0].artifact.sha256),'native composition retains source custody and explicit incomplete unqualified assertion inventory');
 const correspondence=await createCatalogReportCorrespondence('/Users/erik/Projects/umf/package.json');
 const untrusted=(await Bun.file('docs/helix/03-test/report-wire-untrusted.fixture.json').json()).report;
 const report={...untrusted,rev:composed.provisionalRevision,acceptedInput:prepared.original.input,documents:composed.documentBasis.documents,counts:composed.counts,provisional:composed.provisional,diagnostics:composed.validationEvidence.diagnostics,documentInterpretations:composed.validationEvidence.documentInterpretations};
 const reportWire=new TextEncoder().encode(JSON.stringify(report));
 const originalCut=composed.documentBasis.nativeObservation;
 const originalContext=await sql.unsafe('SELECT * FROM truss.runtime_collect_catalog_original_context($1,$2,$3)',[originalCut.writerXid,originalCut.operationOrdinal,originalCut.effectGeneration]);
 const retainedContext=await sql.unsafe("SELECT encode(original_context_bytes,'hex') AS context_hex FROM truss.row_home_operation WHERE original_writer_xid=pg_current_xact_id_if_assigned() AND phase='admitted'");
 assert(originalContext.length===1&&originalContext[0].context_hex===retainedContext[0].context_hex,'native actor collector returns exact original admitted context bytes');
 const actorNow=await sql.unsafe('SELECT current_user::text AS acting,session_user::text AS login,current_database() AS database,pg_backend_pid()::text AS pid');
 assert(originalContext[0].database_role===actorNow[0].acting&&originalContext[0].login_role===actorNow[0].login&&originalContext[0].database_name===actorNow[0].database&&originalContext[0].backend_pid===actorNow[0].pid,'original native acting/login/database/backend facts match current issuer');
 await sql.unsafe('SAVEPOINT unrelated_original_context');let unrelatedContext=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_catalog_original_context($1,$2,$3)',['1',originalCut.operationOrdinal,originalCut.effectGeneration])}catch(e){unrelatedContext=((e as any).errno??(e as any).code)==='55000'}assert(unrelatedContext,'borrowed transaction identity cannot expose original native actor context');await sql.unsafe('ROLLBACK TO SAVEPOINT unrelated_original_context');await sql.unsafe('RELEASE SAVEPOINT unrelated_original_context');
 const executionBasis=await collectCatalogOriginalExecutionBasis(connection,prepared,composed);assert(Buffer.from(executionBasis.contextEvidence.bytesBase64,'base64').toString('hex')===originalContext[0].context_hex,'host actor basis preserves exact native context bytes');assert(executionBasis.databaseRole===actorNow[0].acting&&executionBasis.scope==='original_native_actor_context_basis_only','host actor basis carries actual role without inventing full originalExecution');
 requireOriginalCatalogNativeContext(executionBasis,connection,prepared,composed);assert(true,'original native actor basis retains exact collector issuance and context');
 for(const [candidate,conn,prep,basis] of [[{...executionBasis},connection,prepared,composed],[executionBasis,{...connection},prepared,composed],[executionBasis,connection,prepared,{...composed}]] as const){let copied=false;try{requireOriginalCatalogNativeContext(candidate,conn,prep,basis)}catch(e){copied=(e as Error).message==='Original native context collector custody required'}assert(copied,'copied actor basis, connection or report preparation cannot borrow native issuance');}
 const originalAsserted=new TextEncoder().encode('{"actor":"asserted actor","decimal":"9007199254740993.000"}');
 const originBasis=await collectCatalogAssertedOriginBasis(connection,prepared,composed,executionBasis,originalAsserted);
 assert(originBasis.origin.databaseRole===actorNow[0].acting&&originBasis.journalOrigin.databaseRole===actorNow[0].acting,'origin mapping uses rechecked original native actor');
 assert(Buffer.from(originBasis.assertedEvidence.bytesBase64,'base64').equals(Buffer.from(originalAsserted))&&originBasis.nativeActorEvidence===executionBasis.contextEvidence,'origin basis retains separate exact asserted and native artifacts');
 let forgedOriginActor=false;try{await collectCatalogAssertedOriginBasis(connection,prepared,composed,{...executionBasis,databaseRole:'forged'},originalAsserted)}catch(e){forgedOriginActor=(e as Error).message==='Original native context collector custody required'}assert(forgedOriginActor,'copied actor cannot grant a forged role to origin mapping');
 const roleIdentities=await sql.unsafe('SELECT (SELECT oid::text FROM pg_catalog.pg_roles WHERE rolname=current_user) AS acting,(SELECT oid::text FROM pg_catalog.pg_roles WHERE rolname=session_user) AS login');assert(executionBasis.actorRoleOid===roleIdentities[0].acting&&executionBasis.loginRoleOid===roleIdentities[0].login,'original acting/login role OIDs match actual native identities');
 const corresponding=await correspondence.verify(connection,prepared,composed,reportWire);assert(corresponding.verifiedFields.length===9&&corresponding.scope==='nine_original_report_producer_fields_only','nine report fields correspond to original owner and actual native observations without accepted authority');
 let countForgery=false;try{await correspondence.verify(connection,prepared,composed,new TextEncoder().encode(JSON.stringify({...report,counts:{...report.counts,typesAdded:'3'}})))}catch(e){countForgery=(e as Error).message.includes('producer correspondence required: counts')}assert(countForgery,'schema-valid forged native count refuses report correspondence');
 let clonedBasis=false;try{await correspondence.verify(connection,prepared,{...composed},reportWire)}catch(e){clonedBasis=(e as Error).message.includes('bound catalog report preparation')}assert(clonedBasis,'copied composed report basis cannot borrow original native cut');
 await sql.unsafe('SAVEPOINT stale_report_correspondence');await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');let staleCorrespondence=false;try{await correspondence.verify(connection,prepared,composed,reportWire)}catch(e){staleCorrespondence=((e as any).errno??(e as any).code)==='55000'}assert(staleCorrespondence,'later actual native event invalidates report producer correspondence');await sql.unsafe('ROLLBACK TO SAVEPOINT stale_report_correspondence');await sql.unsafe('RELEASE SAVEPOINT stale_report_correspondence');
 await correspondence.verify(connection,prepared,composed,reportWire);assert(true,'rolled-back native contribution restores original report correspondence');
 assert(JSON.stringify(composed.counts)===JSON.stringify({typesAdded:'2',propertiesAdded:'2',keysAdded:'2',relationshipsAdded:'1',endpointsAdded:'1',elementsRetired:'0'}),'composed report preparation derives all six counts under original native cut');
 assert(composed.documentBasis.nativeObservation.effectGeneration==='11'&&composed.observationCoverage.availability==='available','composed preparation retains matching native cut and actual available owner observations');
 assert(composed.provisional.length===0,'empty provisional report inventory has original native proof across the full retained catalog');
 await sql.unsafe('SAVEPOINT nonempty_provisional');await sql.unsafe('UPDATE truss.type_def SET provisional=true,definition_source_kind=NULL,definition_rev=NULL,definition_doc_ord=NULL,definition_document_id=NULL WHERE type_id=1');let provisionalRefusal=false;try{await sql.unsafe('SELECT truss.runtime_require_empty_provisional_catalog(1)')}catch(e){provisionalRefusal=((e as any).errno??(e as any).code)==='0A000'}assert(provisionalRefusal,'nonempty provisional catalog cannot become an empty report inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT nonempty_provisional');await sql.unsafe('RELEASE SAVEPOINT nonempty_provisional');
 assert(composed.validationEvidence.documentInterpretations[0].evidence.sha256===composed.documentBasis.observations[0].evidence.sha256,'composed producer interpretation preserves the original archived observation evidence');
 assert(composed.validationEvidence.diagnostics.length===prepared.documents[0].interpretation.sourceValidation.diagnostics.length+prepared.documents[0].interpretation.targetValidation!.diagnostics.length,'composed validation retains complete original and target-basis producer diagnostic inventories');
 assert(composed.scope==='original_new_catalog_report_preparation_only'&&composed.extensions.entries.length===0,'composed basis does not fabricate accepted status or extensions');
 await sql.unsafe('SAVEPOINT mixed_preparation');let changed=false;const changingConnection={unsafe:async(query:string,parameters:unknown[]=[])=>{const rows=await connection.unsafe(query,parameters);if(query.includes('runtime_collect_report_documents'))await sql.unsafe('UPDATE truss.prop_def SET name=name WHERE prop_id=1');return rows}};
 try{await collectCatalogReportPreparation(changingConnection,prepared,result.provisionalRevision,owner,fieldOwner)}catch(e){changed=(e as Error).message==='Mixed original report preparation cut'}assert(changed,'later catalog event between document and count observations refuses composed preparation');await sql.unsafe('ROLLBACK TO SAVEPOINT mixed_preparation');await sql.unsafe('RELEASE SAVEPOINT mixed_preparation');
 const inventory=await sql.unsafe('SELECT family,identity::text AS identity FROM truss.runtime_collect_new_catalog_inventory($1::int)',[result.provisionalRevision]);
 const families=Object.fromEntries(['type','property','key','relationship','endpoint'].map(family=>[family,inventory.filter((row:{family:string})=>row.family===family).length]));assert(JSON.stringify(families)===JSON.stringify({type:2,property:2,key:2,relationship:1,endpoint:1}),'native collector returns actual complete new-family identity inventory');
 const counts=await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_counts(1)');assert(JSON.stringify(counts[0])===JSON.stringify({types_added:'2',properties_added:'2',keys_added:'2',relationships_added:'1',endpoints_added:'1',elements_retired:'0'}),'all six count fields derive from source-correlated surviving identities and unchanged retained cut');
 const endpoint=JSON.parse(inventory.find((row:{family:string})=>row.family==='endpoint').identity);assert(endpoint[1]==='1'&&endpoint[2]==='2','collected endpoint is original relationship/source/target tuple');
 await sql.unsafe('SAVEPOINT changed_archive_bytes');await sql.unsafe("UPDATE truss.schema_doc SET document=document||' ',content_sha256=encode(sha256(convert_to(document||' ','UTF8')),'hex') WHERE rev=1");let archiveCountRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_counts(1)')}catch(e){archiveCountRefusal=((e as any).errno??(e as any).code)==='55000'}assert(archiveCountRefusal,'count producer refuses source-byte substitution even with matching new native digest');await sql.unsafe('ROLLBACK TO SAVEPOINT changed_archive_bytes');
 await sql.unsafe('SAVEPOINT retained_genesis_edit');await sql.unsafe("UPDATE truss.schema_rev SET origin='{\"changed\":true}'::jsonb WHERE rev=0");let retainedEdit=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){retainedEdit=((e as any).errno??(e as any).code)==='55000'}assert(retainedEdit,'new-only inventory cannot hide changed original retained revision metadata');await sql.unsafe('ROLLBACK TO SAVEPOINT retained_genesis_edit');
 await sql.unsafe('SAVEPOINT unplanned_revision');await sql.unsafe("INSERT INTO truss.schema_rev(rev,origin) VALUES(2,'{}'::jsonb)");let unplannedRevision=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){unplannedRevision=((e as any).errno??(e as any).code)==='55000'}assert(unplannedRevision,'unplanned extra catalog revision cannot disappear from effect inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT unplanned_revision');
 for(const [label,mutation] of [
  ['missing original Field',"DELETE FROM truss.prop_def WHERE prop_id=1"],
  ['missing original Key',"DELETE FROM truss.key_def WHERE type_id=1"],
  ['altered original Field scalar type',"UPDATE truss.prop_def SET scalar_type='integer' WHERE prop_id=1"],
  ['altered original Field nullability',"UPDATE truss.prop_def SET nullability='absent-allowed' WHERE prop_id=1"],
  ['substituted Key component',"UPDATE truss.key_def SET prop_ids=ARRAY[2] WHERE type_id=1"],
  ['altered Key primary flag',"UPDATE truss.key_def SET is_primary=false WHERE type_id=1"],
  ['altered relationship upper bound',"UPDATE truss.rel_def SET source_max=2"],
  ['altered relationship target key',"UPDATE truss.rel_def SET target_key=NULL"],
 ] as const){await sql.unsafe('SAVEPOINT changed_definition');await sql.unsafe(mutation);let refused=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){refused=((e as any).errno??(e as any).code)==='55000'}assert(refused,label+' refuses inventory');await sql.unsafe('ROLLBACK TO SAVEPOINT changed_definition')}
 await sql.unsafe('SAVEPOINT swapped_endpoint');await sql.unsafe('UPDATE truss.rel_endpoint SET source_type=target_type');let endpointRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){endpointRefusal=((e as any).errno??(e as any).code)==='55000'}assert(endpointRefusal,'equal-count substituted endpoint identity refuses collection');await sql.unsafe('ROLLBACK TO SAVEPOINT swapped_endpoint');
 await sql.unsafe('SAVEPOINT missing_endpoint');await sql.unsafe('DELETE FROM truss.rel_endpoint');let missingRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){missingRefusal=((e as any).errno??(e as any).code)==='55000'}assert(missingRefusal,'missing authored endpoint refuses collection');await sql.unsafe('ROLLBACK TO SAVEPOINT missing_endpoint');
 await sql.unsafe('SAVEPOINT inventory_retired');await sql.unsafe('UPDATE truss.type_def SET retired_rev=1 WHERE type_id=1');let lifecycleRefusal=false;try{await sql.unsafe('SELECT * FROM truss.runtime_collect_new_catalog_inventory(1)')}catch(e){lifecycleRefusal=((e as any).errno??(e as any).code)==='0A000'}assert(lifecycleRefusal,'new-only collector cannot hide retirement or report it as addition');await sql.unsafe('ROLLBACK TO SAVEPOINT inventory_retired');
 const head=await sql.unsafe('SELECT rev::text AS revision FROM truss.schema_head');assert(head[0].revision==='0','provisional cohort never publishes accepted head');
 let barrier=false;try{await sql.unsafe('COMMIT')}catch(e){barrier=((e as any).errno??(e as any).code)==='55000'}assert(barrier,'unfinished complete acceptance cannot commit');
 let operationTruncate=false;try{await sql.unsafe('TRUNCATE TABLE truss.row_home_operation CASCADE')}catch(e){operationTruncate=((e as any).errno??(e as any).code)==='55000'}assert(operationTruncate,'operation truncate guard refuses even with no pending admission trigger');
 let endedObservation=false;try{await recheckCatalogReportDocumentBasis(connection,documentBasis)}catch(e){endedObservation=((e as any).errno??(e as any).code)==='55000'}assert(endedObservation,'ended native transaction cannot reuse captured report observation');
 const empty=await sql.unsafe('SELECT count(*)::text AS count FROM truss.type_def');assert(empty[0].count==='0','failed commit removes all provisional catalog effects');
 for(const component of ['operation-asserted-origin-admission','catalog-captured-context'])await sql.unsafe(await Bun.file('packages/postgresql/native/'+component+'.sql').text());
 await sql.unsafe('BEGIN');const capturedStart=await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate() AS bytes');
 const retainedAsserted=new TextEncoder().encode(' {"actor":"asserted only","decimal":"123.000"}\n');
 await sql.unsafe("SELECT * FROM truss.runtime_admit_operation_with_asserted_origin('catalog-acceptance',decode('01','hex'),decode($1,'hex'),decode($2,'hex'),decode('04','hex'),decode('05','hex'),decode('06','hex'),decode($3,'hex'),decode('010203','hex'))",[prepared.original.originalUtf8Hex,capturedStart[0].bytes,Buffer.from(retainedAsserted).toString('hex')]);
 const capturedStage=await stageNewCatalogCohort(connection,prepared,homes,{});
 const capturedReport=await collectCatalogReportPreparation(connection,prepared,capturedStage.provisionalRevision,owner,fieldOwner);
 const capturedOrigin=await collectCatalogCapturedOriginBasis(connection,prepared,capturedReport,new Uint8Array([1,2,3]));
 assert(Buffer.from(capturedOrigin.assertedEvidence.bytesBase64,'base64').equals(Buffer.from(retainedAsserted)),'complete staged original context3 pipeline returns native-retained asserted bytes');
 requireOriginalCapturedOriginBasis(capturedOrigin,connection,prepared,capturedReport);assert(true,'captured origin basis retains original native/report/executor issuance');
 let copiedCapture=false;try{requireOriginalCapturedOriginBasis({...capturedOrigin},connection,prepared,capturedReport)}catch(e){copiedCapture=(e as Error).message==='Original captured origin collector custody required'}assert(copiedCapture,'copied captured origin basis cannot borrow original native custody');
 let changedCaptureProfile=false;try{await collectCatalogCapturedOriginBasis(connection,prepared,capturedReport,new Uint8Array([4]))}catch(e){changedCaptureProfile=(e as Error).message==='Original captured actor/profile correspondence required'}assert(changedCaptureProfile,'different original capture profile bytes refuse origin composition');
 await recheckOriginalCapturedOriginBasis(capturedOrigin,connection,prepared,capturedReport);assert(true,'original captured origin survives exact native context/cut recheck');
 await sql.unsafe('SAVEPOINT changed_captured_origin_cut');await sql.unsafe('UPDATE truss.prop_def SET name=name');
 let staleCaptured=false;try{await recheckOriginalCapturedOriginBasis(capturedOrigin,connection,prepared,capturedReport)}catch(e){staleCaptured=((e as any).errno??(e as any).code)==='55000'}assert(staleCaptured,'later native catalog effects invalidate captured origin observation');
 await sql.unsafe('ROLLBACK TO SAVEPOINT changed_captured_origin_cut');await sql.unsafe('RELEASE SAVEPOINT changed_captured_origin_cut');
 await recheckOriginalCapturedOriginBasis(capturedOrigin,connection,prepared,capturedReport);assert(true,'rolled-back contribution restores original captured origin correspondence');
 await sql.unsafe('ROLLBACK');let endedCaptured=false;try{await recheckOriginalCapturedOriginBasis(capturedOrigin,connection,prepared,capturedReport)}catch(e){endedCaptured=((e as any).errno??(e as any).code)==='55000'}assert(endedCaptured,'ended native transaction cannot reuse original captured origin basis');
 await sql.unsafe('BEGIN');await sql.unsafe(await Bun.file('docs/helix/04-build/evidence/source-epoch-storage.owner-export.sql').text());
 for(const component of ['source-epoch-immutability','source-epoch-lock','source-epoch-issue','operation-epoch-context-admission','catalog-epoch-context','catalog-original-configuration'])await sql.unsafe(await Bun.file('packages/postgresql/native/'+component+'.sql').text());
 await sql.unsafe("INSERT INTO truss.installation_marker VALUES (1,'truss-bootstrap-marker/0.1.0','component-installation','component-only',decode(repeat('00',32),'hex'),'component',decode(repeat('00',32),'hex'),'owned-fixture','truss',now(),'component-clock-unqualified')");
 const issuedEpoch=await sql.unsafe("SELECT truss.runtime_issue_source_epoch('component-installation',NULL,'component-incarnation',decode('0102','hex'),decode('0304','hex')) AS epoch");
 const epochStart=await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate() AS bytes');
 await sql.unsafe("SELECT * FROM truss.runtime_admit_operation_with_epoch_context('catalog-acceptance',decode('01','hex'),decode($1,'hex'),decode($2,'hex'),decode('04','hex'),decode('05','hex'),decode('06','hex'),decode($3,'hex'),decode('010203','hex'),'component-installation',$4,'component-incarnation')",[prepared.original.originalUtf8Hex,epochStart[0].bytes,Buffer.from(retainedAsserted).toString('hex'),issuedEpoch[0].epoch]);
 const epochStage=await stageNewCatalogCohort(connection,prepared,homes,{});const epochReport=await collectCatalogReportPreparation(connection,prepared,epochStage.provisionalRevision,owner,fieldOwner);
 const epochBasis=await collectCatalogEpochContextBasis(connection,prepared,epochReport,new Uint8Array([1,2,3]));
 assert(epochBasis.sourceEpoch===issuedEpoch[0].epoch&&epochBasis.installationId==='component-installation'&&Buffer.from(epochBasis.sourceEpochEvidence.bytesBase64,'base64').toString('hex')==='0304','actual staged context4 pipeline retains native-issued epoch and original registry evidence');
 assert(Buffer.from(epochBasis.assertedEvidence.bytesBase64,'base64').equals(Buffer.from(retainedAsserted)),'context4 epoch and asserted evidence belong to one original operation');
 requireOriginalCatalogEpochContextBasis(epochBasis,connection,prepared,epochReport);assert(true,'epoch-context basis retains original report/preparation/executor issuance');
 let copiedEpochBasis=false;try{requireOriginalCatalogEpochContextBasis({...epochBasis},connection,prepared,epochReport)}catch(e){copiedEpochBasis=(e as Error).message==='Original captured origin collector custody required'}assert(copiedEpochBasis,'copied epoch-context basis cannot borrow original operation authority');
 await sql.unsafe('SAVEPOINT absent_configuration');let absentConfiguration=false;
 try{await collectCatalogConfigurationBasis(connection,prepared,epochReport,epochBasis)}catch(e){absentConfiguration=((e as any).errno??(e as any).code)==='55000'}assert(absentConfiguration,'missing configuration row is unavailable, never defaulted');
 await sql.unsafe('ROLLBACK TO SAVEPOINT absent_configuration');await sql.unsafe('RELEASE SAVEPOINT absent_configuration');
 const originalConfiguration=' {"mode":"component-only"}\n',originalBinding='{"binding":"component-only"}',originalInventory='{"inventory":"component-only"}';
 await sql.unsafe("INSERT INTO truss.installation_admission (head_id,installation_id_utf8,source_epoch_utf8,configuration_generation,key_reuse,journal_mode,configuration_bytes,selected_binding_bytes,installed_inventory_bytes) VALUES (1,convert_to('component-installation','UTF8'),convert_to($1,'UTF8'),0,'forbid','engine',convert_to($2,'UTF8'),convert_to($3,'UTF8'),convert_to($4,'UTF8'))",[issuedEpoch[0].epoch,originalConfiguration,originalBinding,originalInventory]);
 await sql.unsafe('SAVEPOINT configuration_before_first_collection');
 await sql.unsafe("UPDATE truss.installation_admission SET configuration_generation=1,configuration_bytes=convert_to('later-component-bytes','UTF8')");
 const laterFirstCollection=await collectCatalogConfigurationBasis(connection,prepared,epochReport,epochBasis);
 assert(laterFirstCollection.configurationGeneration==='1'&&Buffer.from(laterFirstCollection.configuration.bytesBase64,'base64').toString('utf8')==='later-component-bytes'&&laterFirstCollection.scope==='current_configuration_byte_basis_under_original_operation_only','first configuration collection observes current bytes, not a historical at-admission snapshot');
 await sql.unsafe('ROLLBACK TO SAVEPOINT configuration_before_first_collection');await sql.unsafe('RELEASE SAVEPOINT configuration_before_first_collection');
 const configurationBasis=await collectCatalogConfigurationBasis(connection,prepared,epochReport,epochBasis);
 assert(configurationBasis.configurationGeneration==='0'&&configurationBasis.keyReuse==='forbid'&&configurationBasis.journalMode==='engine','native configuration scalars remain exact under original epoch/cut');
 assert(Buffer.from(configurationBasis.configuration.bytesBase64,'base64').toString('utf8')===originalConfiguration&&Buffer.from(configurationBasis.selectedBinding.bytesBase64,'base64').toString('utf8')===originalBinding&&Buffer.from(configurationBasis.installedInventory.bytesBase64,'base64').toString('utf8')===originalInventory,'all three original native configuration artifacts preserve exact bytes and generated digests');
 requireOriginalCatalogConfigurationBasis(configurationBasis,connection,prepared,epochReport,epochBasis);assert(true,'configuration basis retains original report/epoch/executor issuance');
 let copiedConfiguration=false;try{requireOriginalCatalogConfigurationBasis({...configurationBasis},connection,prepared,epochReport,epochBasis)}catch(e){copiedConfiguration=(e as Error).message==='Original configuration collector custody required'}assert(copiedConfiguration,'copied configuration basis cannot borrow original producer custody');
 await recheckOriginalCatalogConfigurationBasis(configurationBasis,connection,prepared,epochReport,epochBasis);assert(true,'original configuration survives exact native recheck');
 for(const [label,mutation] of [
  ['generation',"UPDATE truss.installation_admission SET configuration_generation=1"],
  ['configuration bytes',"UPDATE truss.installation_admission SET configuration_bytes=convert_to('changed','UTF8')"],
  ['binding bytes',"UPDATE truss.installation_admission SET selected_binding_bytes=convert_to('changed','UTF8')"],
  ['inventory bytes',"UPDATE truss.installation_admission SET installed_inventory_bytes=convert_to('changed','UTF8')"],
 ] as const){
  await sql.unsafe('SAVEPOINT changed_configuration');await sql.unsafe(mutation);let refused=false;
  try{await recheckOriginalCatalogConfigurationBasis(configurationBasis,connection,prepared,epochReport,epochBasis)}catch(e){refused=(e as Error).message==='Original configuration bytes/generation changed'}assert(refused,'changed '+label+' invalidates original configuration basis');
  await sql.unsafe('ROLLBACK TO SAVEPOINT changed_configuration');await sql.unsafe('RELEASE SAVEPOINT changed_configuration');
 }
 await recheckOriginalCatalogConfigurationBasis(configurationBasis,connection,prepared,epochReport,epochBasis);assert(true,'rolled-back configuration changes restore original correspondence');
 for(const [label,mutation] of [
  ['installation',"UPDATE truss.installation_admission SET installation_id_utf8=convert_to('foreign','UTF8')"],
  ['epoch',"UPDATE truss.installation_admission SET source_epoch_utf8=convert_to('foreign','UTF8')"],
  ['aggregate artifact bounds',"UPDATE truss.installation_admission SET configuration_bytes=convert_to(repeat('a',16777217),'UTF8')"],
 ] as const){
  await sql.unsafe('SAVEPOINT invalid_configuration');await sql.unsafe(mutation);let refused=false;
  try{await collectCatalogConfigurationBasis(connection,prepared,epochReport,epochBasis)}catch(e){refused=((e as any).errno??(e as any).code)==='55000'}assert(refused,'invalid '+label+' refuses native configuration collection');
  await sql.unsafe('ROLLBACK TO SAVEPOINT invalid_configuration');await sql.unsafe('RELEASE SAVEPOINT invalid_configuration');
 }
 await sql.unsafe('SAVEPOINT maximum_configuration_generation');await sql.unsafe('UPDATE truss.installation_admission SET configuration_generation=9223372036854775807');
 const maximumConfiguration=await collectCatalogConfigurationBasis(connection,prepared,epochReport,epochBasis);assert(maximumConfiguration.configurationGeneration==='9223372036854775807','maximum int64 native configuration generation never passes through JavaScript number');
 await sql.unsafe('ROLLBACK TO SAVEPOINT maximum_configuration_generation');await sql.unsafe('RELEASE SAVEPOINT maximum_configuration_generation');
 await recheckOriginalCatalogEpochContextBasis(epochBasis,connection,prepared,epochReport);assert(true,'original epoch basis survives exact native context and registry recheck');
 await sql.unsafe('SAVEPOINT changed_epoch_cut');await sql.unsafe('UPDATE truss.prop_def SET name=name');
 let staleEpoch=false;try{await recheckOriginalCatalogEpochContextBasis(epochBasis,connection,prepared,epochReport)}catch(e){staleEpoch=((e as any).errno??(e as any).code)==='55000'}assert(staleEpoch,'later catalog effects invalidate original epoch-context cut');
 await sql.unsafe('ROLLBACK TO SAVEPOINT changed_epoch_cut');await sql.unsafe('RELEASE SAVEPOINT changed_epoch_cut');
 await recheckOriginalCatalogEpochContextBasis(epochBasis,connection,prepared,epochReport);assert(true,'rollback restores original epoch-context correspondence');
 await sql.unsafe('ROLLBACK');
 let endedConfiguration=false;try{await recheckOriginalCatalogConfigurationBasis(configurationBasis,connection,prepared,epochReport,epochBasis)}catch(e){endedConfiguration=((e as any).errno??(e as any).code)==='55000'}assert(endedConfiguration,'ended native transaction cannot reuse original configuration basis');
 await sql.unsafe('BEGIN');await sql.unsafe(await Bun.file('docs/helix/04-build/evidence/source-epoch-storage.owner-export.sql').text());
 await sql.unsafe(await Bun.file('docs/helix/04-build/evidence/operation-configuration-storage.owner-export.sql').text());
 for(const component of ['source-epoch-immutability','source-epoch-lock','source-epoch-issue','catalog-epoch-context','operation-configuration-context-admission','operation-configuration-immutability','operation-configuration-current','catalog-admission-configuration'])await sql.unsafe(await Bun.file('packages/postgresql/native/'+component+'.sql').text());
 await sql.unsafe("INSERT INTO truss.installation_marker VALUES (1,'truss-bootstrap-marker/0.1.0','component-installation','component-only',decode(repeat('00',32),'hex'),'component',decode(repeat('00',32),'hex'),'owned-fixture','truss',now(),'component-clock-unqualified')");
 const capsuleEpoch=await sql.unsafe("SELECT truss.runtime_issue_source_epoch('component-installation',NULL,'component-incarnation',decode('0102','hex'),decode('0304','hex')) AS epoch");
 const capsuleStart=await sql.unsafe('SELECT truss.runtime_capture_catalog_prestate() AS bytes');
 const admitCapsule=(profileHex:string|null='0405')=>sql.unsafe("SELECT * FROM truss.runtime_admit_operation_with_configuration_context('catalog-acceptance',decode('01','hex'),decode($1,'hex'),decode($2,'hex'),decode('04','hex'),decode('05','hex'),decode('06','hex'),decode($3,'hex'),decode('010203','hex'),'component-installation',$4,'component-incarnation',decode($5,'hex'))",[prepared.original.originalUtf8Hex,capsuleStart[0].bytes,Buffer.from(retainedAsserted).toString('hex'),capsuleEpoch[0].epoch,profileHex]);
 const refuseCapsule=async(label:string,run:()=>Promise<unknown>,expectedCode='55000')=>{await sql.unsafe('SAVEPOINT capsule_refusal');let refused=false;try{await run()}catch(e){refused=((e as any).errno??(e as any).code)===expectedCode}assert(refused,label);await sql.unsafe('ROLLBACK TO SAVEPOINT capsule_refusal');await sql.unsafe('RELEASE SAVEPOINT capsule_refusal');};
 await refuseCapsule('pre-effect admission refuses missing current configuration',admitCapsule);
 const missingEffects=await sql.unsafe('SELECT count(*)::text AS n FROM truss.row_home_operation');assert(missingEffects[0].n==='0','missing pre-effect capture publishes no operation parent');
 await sql.unsafe("INSERT INTO truss.installation_admission (head_id,installation_id_utf8,source_epoch_utf8,configuration_generation,key_reuse,journal_mode,configuration_bytes,selected_binding_bytes,installed_inventory_bytes) VALUES (1,convert_to('component-installation','UTF8'),convert_to($1,'UTF8'),9223372036854775807,'forbid','engine',convert_to($2,'UTF8'),convert_to($3,'UTF8'),convert_to($4,'UTF8'))",[capsuleEpoch[0].epoch,originalConfiguration,originalBinding,originalInventory]);
 await refuseCapsule('missing configuration capture profile refuses before capsule effects',()=>admitCapsule(null),'22023');
 for(const [label,mutation] of [
  ['installation',"UPDATE truss.installation_admission SET installation_id_utf8=convert_to('foreign','UTF8')"],
  ['epoch',"UPDATE truss.installation_admission SET source_epoch_utf8=convert_to('foreign','UTF8')"],
  ['aggregate artifact bounds',"UPDATE truss.installation_admission SET configuration_bytes=convert_to(repeat('a',16777217),'UTF8')"],
 ] as const){await sql.unsafe('SAVEPOINT capsule_admission_input');await sql.unsafe(mutation);await refuseCapsule('pre-effect capture refuses '+label,admitCapsule);await sql.unsafe('ROLLBACK TO SAVEPOINT capsule_admission_input');await sql.unsafe('RELEASE SAVEPOINT capsule_admission_input');}
 await sql.unsafe('SAVEPOINT capsule_insert_failure');
 await sql.unsafe("CREATE FUNCTION truss.fixture_capsule_insert_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fixture capsule failure' USING ERRCODE='55000'; END; $$; CREATE TRIGGER fixture_capsule_insert_failure BEFORE INSERT ON truss.operation_configuration FOR EACH ROW EXECUTE FUNCTION truss.fixture_capsule_insert_failure()");
 await refuseCapsule('failed capsule sibling rolls back admission statement',admitCapsule);
 const failedParent=await sql.unsafe('SELECT count(*)::text AS n FROM truss.row_home_operation');assert(failedParent[0].n==='0','capsule insertion failure leaves no operation parent');
 await sql.unsafe('ROLLBACK TO SAVEPOINT capsule_insert_failure');await sql.unsafe('RELEASE SAVEPOINT capsule_insert_failure');
 await sql.unsafe('SAVEPOINT whole_capsule_admission');const admittedCapsule=await admitCapsule();
 const capturedCapsule=await sql.unsafe("SELECT c.configuration_generation::text AS generation,encode(c.configuration_bytes,'hex') AS configuration,encode(c.selected_binding_bytes,'hex') AS binding,encode(c.installed_inventory_bytes,'hex') AS inventory,encode(c.admission_profile_bytes,'hex') AS profile,c.original_context_sha256=sha256(o.original_context_bytes) AS context_exact FROM truss.operation_configuration c JOIN truss.row_home_operation o USING(original_writer_xid,operation_ordinal)");
 assert(capturedCapsule.length===1&&capturedCapsule[0].generation==='9223372036854775807'&&capturedCapsule[0].configuration===Buffer.from(originalConfiguration).toString('hex')&&capturedCapsule[0].binding===Buffer.from(originalBinding).toString('hex')&&capturedCapsule[0].inventory===Buffer.from(originalInventory).toString('hex')&&capturedCapsule[0].profile==='0405'&&capturedCapsule[0].context_exact===true,'pre-effect capsule preserves maximum bigint, all original bytes, profile and parent context before catalog staging');
 const unstagedCatalog=await sql.unsafe('SELECT count(*)::text AS n FROM truss.type_def');assert(unstagedCatalog[0].n==='0','configuration capsule exists before any new catalog definition effect');
 const capsuleStage=await stageNewCatalogCohort(connection,prepared,homes,{}),capsuleReport=await collectCatalogReportPreparation(connection,prepared,capsuleStage.provisionalRevision,owner,fieldOwner),capsuleCut=capsuleReport.documentBasis.nativeObservation;
 const capsuleEpochBasis=await collectCatalogEpochContextBasis(connection,prepared,capsuleReport,new Uint8Array([1,2,3]));
 const mutableConfigurationProfile=new Uint8Array([4,5]),collectCapsule=collectCatalogAdmissionConfigurationBasis(connection,prepared,capsuleReport,capsuleEpochBasis,mutableConfigurationProfile);
 mutableConfigurationProfile[0]=255;const capsuleHostBasis=await collectCapsule;
 assert(capsuleHostBasis.configurationGeneration==='9223372036854775807'&&capsuleHostBasis.scope==='original_pre_effect_configuration_byte_basis_only'&&Buffer.from(capsuleHostBasis.configurationProfile.bytesBase64,'base64').toString('hex')==='0405','original capsule host projection snapshots profile bytes before asynchronous observation');
 assert(Buffer.from(capsuleHostBasis.configuration.bytesBase64,'base64').toString('utf8')===originalConfiguration&&Buffer.from(capsuleHostBasis.selectedBinding.bytesBase64,'base64').toString('utf8')===originalBinding&&Buffer.from(capsuleHostBasis.installedInventory.bytesBase64,'base64').toString('utf8')===originalInventory,'original capsule host projection preserves all native artifact bytes');
 requireOriginalCatalogAdmissionConfigurationBasis(capsuleHostBasis,connection,prepared,capsuleReport,capsuleEpochBasis);assert(true,'original capsule host issuance retains exact operation/report/epoch/executor custody');
 let copiedCapsule=false;try{requireOriginalCatalogAdmissionConfigurationBasis({...capsuleHostBasis},connection,prepared,capsuleReport,capsuleEpochBasis)}catch(e){copiedCapsule=(e as Error).message==='Original admission configuration collector custody required'}assert(copiedCapsule,'copied capsule projection cannot borrow original collector custody');
 await refuseCapsule('wrong configuration profile refuses original capsule projection',()=>collectCatalogAdmissionConfigurationBasis(connection,prepared,capsuleReport,capsuleEpochBasis,new Uint8Array([4,6])));
 await recheckOriginalCatalogAdmissionConfigurationBasis(capsuleHostBasis,connection,prepared,capsuleReport,capsuleEpochBasis);assert(true,'original capsule projection survives exact native and profile recheck');
 const requireCurrentCapsule=()=>sql.unsafe('SELECT truss.runtime_require_operation_configuration_current($1,$2,$3)',[capsuleCut.writerXid,capsuleCut.operationOrdinal,capsuleCut.effectGeneration]);
 await requireCurrentCapsule();assert(true,'current configuration matches immutable pre-effect capture at staged observation');
 for(const [label,mutation] of [
  ['generation',"UPDATE truss.installation_admission SET configuration_generation=0"],
  ['key reuse',"UPDATE truss.installation_admission SET key_reuse='allow'"],
  ['journal mode',"UPDATE truss.installation_admission SET journal_mode='trigger'"],
  ['configuration',"UPDATE truss.installation_admission SET configuration_bytes=decode('ff','hex')"],
  ['binding',"UPDATE truss.installation_admission SET selected_binding_bytes=decode('ff','hex')"],
  ['inventory',"UPDATE truss.installation_admission SET installed_inventory_bytes=decode('ff','hex')"],
  ['oversized current artifact',"UPDATE truss.installation_admission SET configuration_bytes=convert_to(repeat('a',16777217),'UTF8')"],
 ] as const){await sql.unsafe('SAVEPOINT changed_capsule_current');await sql.unsafe(mutation);await refuseCapsule('same-operation changed '+label+' fails original capsule comparison',requireCurrentCapsule);await refuseCapsule('changed current '+label+' refuses issued host capsule use',()=>recheckOriginalCatalogAdmissionConfigurationBasis(capsuleHostBasis,connection,prepared,capsuleReport,capsuleEpochBasis));const retained=await sql.unsafe("SELECT encode(configuration_bytes,'hex') AS bytes FROM truss.operation_configuration");assert(retained[0].bytes===capturedCapsule[0].configuration,'changed current '+label+' preserves historical capsule');await sql.unsafe('ROLLBACK TO SAVEPOINT changed_capsule_current');await sql.unsafe('RELEASE SAVEPOINT changed_capsule_current');}
 for(const [label,mutation] of [['update',"UPDATE truss.operation_configuration SET configuration_bytes=decode('ff','hex')"],['delete','DELETE FROM truss.operation_configuration'],['truncate','TRUNCATE truss.operation_configuration']] as const)await refuseCapsule('immutable capsule refuses '+label,()=>sql.unsafe(mutation));
 await requireCurrentCapsule();assert(true,'savepoint restoration preserves original capsule/current correspondence');
 await sql.unsafe('ROLLBACK TO SAVEPOINT whole_capsule_admission');await sql.unsafe('RELEASE SAVEPOINT whole_capsule_admission');
 const rollbackCapsule=await sql.unsafe('SELECT (SELECT count(*)::text FROM truss.operation_configuration) AS capsules,(SELECT count(*)::text FROM truss.row_home_operation) AS operations,(SELECT count(*)::text FROM truss.type_def) AS types');assert(rollbackCapsule[0].capsules==='0'&&rollbackCapsule[0].operations==='0'&&rollbackCapsule[0].types==='0','whole admission rollback removes capsule, parent and staged effects');
 await refuseCapsule('rolled-back operation cannot reuse capsule observation',requireCurrentCapsule);
 await sql.unsafe('ROLLBACK');
 let endedCapsule=false;try{await recheckOriginalCatalogAdmissionConfigurationBasis(capsuleHostBasis,connection,prepared,capsuleReport,capsuleEpochBasis)}catch(e){endedCapsule=((e as any).errno??(e as any).code)==='55000'}assert(endedCapsule,'ended operation cannot reuse original host capsule projection');
 const sourcePins=Object.fromEntries(await Promise.all([...components,'operation-asserted-origin-admission','catalog-captured-context','source-epoch-immutability','source-epoch-lock','source-epoch-issue','operation-epoch-context-admission','catalog-epoch-context','catalog-original-configuration','operation-configuration-context-admission','operation-configuration-immutability','operation-configuration-current','catalog-admission-configuration'].map(async component=>[component,new Bun.CryptoHasher('sha256').update(await Bun.file('packages/postgresql/native/'+component+'.sql').arrayBuffer()).digest('hex')])));
 sourcePins['operation-configuration-storage.owner-export.sql']=new Bun.CryptoHasher('sha256').update(await Bun.file('docs/helix/04-build/evidence/operation-configuration-storage.owner-export.sql').arrayBuffer()).digest('hex');
 sourcePins['source-epoch-storage.owner-export.sql']=new Bun.CryptoHasher('sha256').update(await Bun.file('docs/helix/04-build/evidence/source-epoch-storage.owner-export.sql').arrayBuffer()).digest('hex');
 const receipt={sourcePins,admissionConfigurationBasisProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-admission-configuration-basis.ts').arrayBuffer()).digest('hex'),configurationAdmissionDerivationSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('scripts/build-configuration-context-admission.py').arrayBuffer()).digest('hex'),configurationBasisProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-configuration-basis.ts').arrayBuffer()).digest('hex'),epochContextBasisProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-epoch-context-basis.ts').arrayBuffer()).digest('hex'),capturedOriginBasisProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-captured-origin-basis.ts').arrayBuffer()).digest('hex'),assertedOriginBasisProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-asserted-origin-basis.ts').arrayBuffer()).digest('hex'),coreAssertionIdentityProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-core-assertion-identities.ts').arrayBuffer()).digest('hex'),originalExecutionBasisProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-original-execution-basis.ts').arrayBuffer()).digest('hex'),reportCorrespondenceProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-report-correspondence.ts').arrayBuffer()).digest('hex'),reportPreparationProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-report-preparation.ts').arrayBuffer()).digest('hex'),assertionProfiles:{declarations:composed.ownerObservations.profile,fields:composed.ownerObservations.fieldProfile},reportDocumentProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-report-document-basis.ts').arrayBuffer()).digest('hex'),defaultHomeProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-default-homes.ts').arrayBuffer()).digest('hex'),stageProducerSha256:new Bun.CryptoHasher('sha256').update(await Bun.file('packages/umf-bun/src/catalog-new-stage.ts').arrayBuffer()).digest('hex'),originalInputSha256:new Bun.CryptoHasher('sha256').update(Buffer.from(prepared.original.originalUtf8Hex,'hex')).digest('hex'),engine:version[0].server_version,umfProfile:preparation.umfProfile,checks,scope:'Actual original complete declared new catalog staging and atomic refusal only. Root profile/authority, retained lifecycle, acceptance report/head/finalizer and public entrypoint are unqualified.'};await Bun.write('docs/helix/04-build/evidence/catalog-new-cohort.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({checks:checks.length}));
}finally{await sql.close()}
