ALTER TABLE c.object ADD CONSTRAINT ck_t1_p1_required CHECK (type_id <> 1 OR (jsonb_typeof((props->'1')) IS NOT NULL AND jsonb_typeof((props->'1')) <> 'null')); -- rule Customer.id:required
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p1_value CHECK (type_id <> 1 OR NOT (jsonb_typeof((props->'1')) IS NOT NULL AND jsonb_typeof((props->'1')) <> 'null') OR (jsonb_typeof((props->'1')) = 'number' AND scale(((props->'1') #>> '{}')::numeric) = 0 AND ((props->'1') #>> '{}')::numeric BETWEEN -9223372036854775808 AND 9223372036854775807)); -- rule Customer.id:value
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p2_required CHECK (type_id <> 1 OR (jsonb_typeof((props->'2')) IS NOT NULL AND jsonb_typeof((props->'2')) <> 'null')); -- rule Customer.code:required
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p2_value CHECK (type_id <> 1 OR NOT (jsonb_typeof((props->'2')) IS NOT NULL AND jsonb_typeof((props->'2')) <> 'null') OR (jsonb_typeof((props->'2')) = 'string' AND length(((props->'2') #>> '{}')) <= 20)); -- rule Customer.code:value
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p3_required CHECK (type_id <> 1 OR (jsonb_typeof((props->'3')) IS NOT NULL AND jsonb_typeof((props->'3')) <> 'null')); -- rule Customer.name:required
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p3_value CHECK (type_id <> 1 OR NOT (jsonb_typeof((props->'3')) IS NOT NULL AND jsonb_typeof((props->'3')) <> 'null') OR (jsonb_typeof((props->'3')) = 'string' AND length(((props->'3') #>> '{}')) <= 100)); -- rule Customer.name:value
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p4_value CHECK (type_id <> 1 OR NOT (jsonb_typeof((props->'4')) IS NOT NULL AND jsonb_typeof((props->'4')) <> 'null') OR (jsonb_typeof((props->'4')) = 'string' AND length(((props->'4') #>> '{}')) <= 200)); -- rule Customer.email:value
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p5_required CHECK (type_id <> 1 OR (jsonb_typeof((props->'5')) IS NOT NULL AND jsonb_typeof((props->'5')) <> 'null')); -- rule Customer.createdAt:required
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p5_value CHECK (type_id <> 1 OR NOT (jsonb_typeof((props->'5')) IS NOT NULL AND jsonb_typeof((props->'5')) <> 'null') OR (jsonb_typeof((props->'5')) = 'string' AND ((props->'5') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,9})?(Z|[+-][0-9]{2}:[0-9]{2})?$')); -- rule Customer.createdAt:value
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p6_array CHECK (type_id <> 1 OR NOT (jsonb_typeof((props->'6')) IS NOT NULL AND jsonb_typeof((props->'6')) <> 'null') OR (jsonb_typeof((props->'6')) = 'array' AND NOT jsonb_path_exists((props->'6'), '$[*] ? (@.type() != "string" || !(@ like_regex "^.{0,30}$" flag "s"))'))); -- rule Customer.tags:array
ALTER TABLE c.object ADD CONSTRAINT ck_t1_p7_map CHECK (type_id <> 1 OR NOT (jsonb_typeof((props->'7')) IS NOT NULL AND jsonb_typeof((props->'7')) <> 'null') OR (jsonb_typeof((props->'7')) = 'object' AND NOT jsonb_path_exists((props->'7'), '$.* ? (@.type() != "string" || !(@ like_regex "^.{0,100}$" flag "s"))'))); -- rule Customer.attributes:map
ALTER TABLE c.object ADD CONSTRAINT ck_t2_p8_required CHECK (type_id <> 2 OR (jsonb_typeof((props->'8')) IS NOT NULL AND jsonb_typeof((props->'8')) <> 'null')); -- rule Address.street:required
ALTER TABLE c.object ADD CONSTRAINT ck_t2_p8_value CHECK (type_id <> 2 OR NOT (jsonb_typeof((props->'8')) IS NOT NULL AND jsonb_typeof((props->'8')) <> 'null') OR (jsonb_typeof((props->'8')) = 'string' AND length(((props->'8') #>> '{}')) <= 200)); -- rule Address.street:value
ALTER TABLE c.object ADD CONSTRAINT ck_t2_p9_required CHECK (type_id <> 2 OR (jsonb_typeof((props->'9')) IS NOT NULL AND jsonb_typeof((props->'9')) <> 'null')); -- rule Address.city:required
ALTER TABLE c.object ADD CONSTRAINT ck_t2_p9_value CHECK (type_id <> 2 OR NOT (jsonb_typeof((props->'9')) IS NOT NULL AND jsonb_typeof((props->'9')) <> 'null') OR (jsonb_typeof((props->'9')) = 'string' AND length(((props->'9') #>> '{}')) <= 100)); -- rule Address.city:value
ALTER TABLE c.object ADD CONSTRAINT ck_t2_p10_value CHECK (type_id <> 2 OR NOT (jsonb_typeof((props->'10')) IS NOT NULL AND jsonb_typeof((props->'10')) <> 'null') OR (jsonb_typeof((props->'10')) = 'string' AND length(((props->'10') #>> '{}')) <= 20)); -- rule Address.postalCode:value
ALTER TABLE c.object ADD CONSTRAINT ck_t2_p11_required CHECK (type_id <> 2 OR (jsonb_typeof((props->'11')) IS NOT NULL AND jsonb_typeof((props->'11')) <> 'null')); -- rule Address.country:required
ALTER TABLE c.object ADD CONSTRAINT ck_t2_p11_value CHECK (type_id <> 2 OR NOT (jsonb_typeof((props->'11')) IS NOT NULL AND jsonb_typeof((props->'11')) <> 'null') OR (jsonb_typeof((props->'11')) = 'string' AND length(((props->'11') #>> '{}')) <= 2)); -- rule Address.country:value
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p12_required CHECK (type_id <> 3 OR (jsonb_typeof((props->'12')) IS NOT NULL AND jsonb_typeof((props->'12')) <> 'null')); -- rule Order.id:required
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p12_value CHECK (type_id <> 3 OR NOT (jsonb_typeof((props->'12')) IS NOT NULL AND jsonb_typeof((props->'12')) <> 'null') OR (jsonb_typeof((props->'12')) = 'number' AND scale(((props->'12') #>> '{}')::numeric) = 0 AND ((props->'12') #>> '{}')::numeric BETWEEN -9223372036854775808 AND 9223372036854775807)); -- rule Order.id:value
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p13_required CHECK (type_id <> 3 OR (jsonb_typeof((props->'13')) IS NOT NULL AND jsonb_typeof((props->'13')) <> 'null')); -- rule Order.placedAt:required
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p13_value CHECK (type_id <> 3 OR NOT (jsonb_typeof((props->'13')) IS NOT NULL AND jsonb_typeof((props->'13')) <> 'null') OR (jsonb_typeof((props->'13')) = 'string' AND ((props->'13') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,9})?(Z|[+-][0-9]{2}:[0-9]{2})?$')); -- rule Order.placedAt:value
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p14_required CHECK (type_id <> 3 OR (jsonb_typeof((props->'14')) IS NOT NULL AND jsonb_typeof((props->'14')) <> 'null')); -- rule Order.status:required
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p14_value CHECK (type_id <> 3 OR NOT (jsonb_typeof((props->'14')) IS NOT NULL AND jsonb_typeof((props->'14')) <> 'null') OR (jsonb_typeof((props->'14')) = 'string' AND length(((props->'14') #>> '{}')) <= 20)); -- rule Order.status:value
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p15_value CHECK (type_id <> 3 OR NOT (jsonb_typeof((props->'15')) IS NOT NULL AND jsonb_typeof((props->'15')) <> 'null') OR (jsonb_typeof((props->'15')) = 'string' AND length(((props->'15') #>> '{}')) <= 20)); -- rule Order.channel:value
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p16_required CHECK (type_id <> 3 OR (jsonb_typeof((props->'16')) IS NOT NULL AND jsonb_typeof((props->'16')) <> 'null')); -- rule Order.total:required
ALTER TABLE c.object ADD CONSTRAINT ck_t3_p16_value CHECK (type_id <> 3 OR NOT (jsonb_typeof((props->'16')) IS NOT NULL AND jsonb_typeof((props->'16')) <> 'null') OR (jsonb_typeof((props->'16')) = 'number' AND scale(((props->'16') #>> '{}')::numeric) <= 2 AND abs(((props->'16') #>> '{}')::numeric) < 1e12)); -- rule Order.total:value
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p17_required CHECK (type_id <> 4 OR (jsonb_typeof((props->'17')) IS NOT NULL AND jsonb_typeof((props->'17')) <> 'null')); -- rule OrderLine.id:required
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p17_value CHECK (type_id <> 4 OR NOT (jsonb_typeof((props->'17')) IS NOT NULL AND jsonb_typeof((props->'17')) <> 'null') OR (jsonb_typeof((props->'17')) = 'number' AND scale(((props->'17') #>> '{}')::numeric) = 0 AND ((props->'17') #>> '{}')::numeric BETWEEN -9223372036854775808 AND 9223372036854775807)); -- rule OrderLine.id:value
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p18_required CHECK (type_id <> 4 OR (jsonb_typeof((props->'18')) IS NOT NULL AND jsonb_typeof((props->'18')) <> 'null')); -- rule OrderLine.lineNo:required
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p18_value CHECK (type_id <> 4 OR NOT (jsonb_typeof((props->'18')) IS NOT NULL AND jsonb_typeof((props->'18')) <> 'null') OR (jsonb_typeof((props->'18')) = 'number' AND scale(((props->'18') #>> '{}')::numeric) = 0 AND ((props->'18') #>> '{}')::numeric BETWEEN -32768 AND 32767)); -- rule OrderLine.lineNo:value
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p19_required CHECK (type_id <> 4 OR (jsonb_typeof((props->'19')) IS NOT NULL AND jsonb_typeof((props->'19')) <> 'null')); -- rule OrderLine.quantity:required
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p19_value CHECK (type_id <> 4 OR NOT (jsonb_typeof((props->'19')) IS NOT NULL AND jsonb_typeof((props->'19')) <> 'null') OR (jsonb_typeof((props->'19')) = 'number' AND scale(((props->'19') #>> '{}')::numeric) = 0 AND ((props->'19') #>> '{}')::numeric BETWEEN -2147483648 AND 2147483647)); -- rule OrderLine.quantity:value
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p20_required CHECK (type_id <> 4 OR (jsonb_typeof((props->'20')) IS NOT NULL AND jsonb_typeof((props->'20')) <> 'null')); -- rule OrderLine.unitPrice:required
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p20_value CHECK (type_id <> 4 OR NOT (jsonb_typeof((props->'20')) IS NOT NULL AND jsonb_typeof((props->'20')) <> 'null') OR (jsonb_typeof((props->'20')) = 'number' AND scale(((props->'20') #>> '{}')::numeric) <= 2 AND abs(((props->'20') #>> '{}')::numeric) < 1e10)); -- rule OrderLine.unitPrice:value
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p21_required CHECK (type_id <> 4 OR (jsonb_typeof((props->'21')) IS NOT NULL AND jsonb_typeof((props->'21')) <> 'null')); -- rule OrderLine.lineTotal:required
ALTER TABLE c.object ADD CONSTRAINT ck_t4_p21_value CHECK (type_id <> 4 OR NOT (jsonb_typeof((props->'21')) IS NOT NULL AND jsonb_typeof((props->'21')) <> 'null') OR (jsonb_typeof((props->'21')) = 'number' AND scale(((props->'21') #>> '{}')::numeric) <= 2 AND abs(((props->'21') #>> '{}')::numeric) < 1e12)); -- rule OrderLine.lineTotal:value
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p22_required CHECK (type_id <> 5 OR (jsonb_typeof((props->'22')) IS NOT NULL AND jsonb_typeof((props->'22')) <> 'null')); -- rule Product.id:required
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p22_value CHECK (type_id <> 5 OR NOT (jsonb_typeof((props->'22')) IS NOT NULL AND jsonb_typeof((props->'22')) <> 'null') OR (jsonb_typeof((props->'22')) = 'number' AND scale(((props->'22') #>> '{}')::numeric) = 0 AND ((props->'22') #>> '{}')::numeric BETWEEN -9223372036854775808 AND 9223372036854775807)); -- rule Product.id:value
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p23_required CHECK (type_id <> 5 OR (jsonb_typeof((props->'23')) IS NOT NULL AND jsonb_typeof((props->'23')) <> 'null')); -- rule Product.sku:required
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p23_value CHECK (type_id <> 5 OR NOT (jsonb_typeof((props->'23')) IS NOT NULL AND jsonb_typeof((props->'23')) <> 'null') OR (jsonb_typeof((props->'23')) = 'string' AND length(((props->'23') #>> '{}')) <= 32)); -- rule Product.sku:value
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p24_required CHECK (type_id <> 5 OR (jsonb_typeof((props->'24')) IS NOT NULL AND jsonb_typeof((props->'24')) <> 'null')); -- rule Product.name:required
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p24_value CHECK (type_id <> 5 OR NOT (jsonb_typeof((props->'24')) IS NOT NULL AND jsonb_typeof((props->'24')) <> 'null') OR (jsonb_typeof((props->'24')) = 'string' AND length(((props->'24') #>> '{}')) <= 200)); -- rule Product.name:value
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p25_required CHECK (type_id <> 5 OR (jsonb_typeof((props->'25')) IS NOT NULL AND jsonb_typeof((props->'25')) <> 'null')); -- rule Product.price:required
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p25_value CHECK (type_id <> 5 OR NOT (jsonb_typeof((props->'25')) IS NOT NULL AND jsonb_typeof((props->'25')) <> 'null') OR (jsonb_typeof((props->'25')) = 'number' AND scale(((props->'25') #>> '{}')::numeric) <= 2 AND abs(((props->'25') #>> '{}')::numeric) < 1e10)); -- rule Product.price:value
ALTER TABLE c.object ADD CONSTRAINT ck_t5_p26_value CHECK (type_id <> 5 OR NOT (jsonb_typeof((props->'26')) IS NOT NULL AND jsonb_typeof((props->'26')) <> 'null') OR (jsonb_typeof((props->'26')) = 'string' AND ((props->'26') #>> '{}') ~ '^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$' AND length(decode(((props->'26') #>> '{}'), 'base64')) <= 65536)); -- rule Product.image:value
ALTER TABLE c.object ADD CONSTRAINT ck_t1_declared_only CHECK (type_id <> 1 OR (props - ARRAY['1','2','3','4','5','6','7']::text[]) = '{}'::jsonb); -- rule Customer:declared-properties
ALTER TABLE c.object ADD CONSTRAINT ck_t2_declared_only CHECK (type_id <> 2 OR (props - ARRAY['8','9','10','11']::text[]) = '{}'::jsonb); -- rule Address:declared-properties
ALTER TABLE c.object ADD CONSTRAINT ck_t3_declared_only CHECK (type_id <> 3 OR (props - ARRAY['12','13','14','15','16']::text[]) = '{}'::jsonb); -- rule Order:declared-properties
ALTER TABLE c.object ADD CONSTRAINT ck_t4_declared_only CHECK (type_id <> 4 OR (props - ARRAY['17','18','19','20','21']::text[]) = '{}'::jsonb); -- rule OrderLine:declared-properties
ALTER TABLE c.object ADD CONSTRAINT ck_t5_declared_only CHECK (type_id <> 5 OR (props - ARRAY['22','23','24','25','26']::text[]) = '{}'::jsonb); -- rule Product:declared-properties
ALTER TABLE c.object ADD CONSTRAINT ck_t4_inv_line_total CHECK (type_id <> 4 OR ((props->>'21')::numeric = (props->>'19')::numeric * (props->>'20')::numeric)); -- rule OrderLine:invariant:line-total
